import { Brand } from '../types.ts';

export const SEED_BRANDS: Brand[] = [
  // Whisky
  { id: 'b_royalstag', name: 'Royal Stag', slug: 'royal-stag', countryOfOrigin: 'India', logoUrl: '', description: 'Iconic blended Indian whisky from Pernod Ricard.' },
  { id: 'b_blenderspride', name: 'Blenders Pride', slug: 'blenders-pride', countryOfOrigin: 'India', logoUrl: '', description: 'Premium blended malt whisky.' },
  { id: 'b_imperialblue', name: 'Imperial Blue', slug: 'imperial-blue', countryOfOrigin: 'India', logoUrl: '', description: 'Superior grain and Scotch malt blended whisky.' },
  { id: 'b_mcdowell', name: "McDowell's No.1", slug: 'mcdowells-no1', countryOfOrigin: 'India', logoUrl: '', description: 'Flagship spirits brand from United Spirits / Diageo.' },
  { id: 'b_blackdog', name: 'Black Dog', slug: 'black-dog', countryOfOrigin: 'Scotland', logoUrl: '', description: 'Triple Gold Reserve blended Scotch whisky.' },
  { id: 'b_100pipers', name: '100 Pipers', slug: '100-pipers', countryOfOrigin: 'Scotland', logoUrl: '', description: 'Smooth blended Scotch whisky.' },
  { id: 'b_ballantines', name: "Ballantine's", slug: 'ballantines', countryOfOrigin: 'Scotland', logoUrl: '', description: 'World-renowned blended Scotch whisky.' },
  { id: 'b_chivas', name: 'Chivas Regal', slug: 'chivas-regal', countryOfOrigin: 'Scotland', logoUrl: '', description: '12 Year Old luxury blended Scotch.' },
  { id: 'b_johnniewalker', name: 'Johnnie Walker', slug: 'johnnie-walker', countryOfOrigin: 'Scotland', logoUrl: '', description: 'Iconic Scotch whisky brand (Red & Black Label).' },
  { id: 'b_jameson', name: 'Jameson', slug: 'jameson', countryOfOrigin: 'Ireland', logoUrl: '', description: 'Triple-distilled Irish whiskey.' },
  { id: 'b_jackdaniels', name: "Jack Daniel's", slug: 'jack-daniels', countryOfOrigin: 'United States', logoUrl: '', description: 'Old No. 7 Tennessee sour mash whiskey.' },
  { id: 'b_dewars', name: "Dewar's", slug: 'dewars', countryOfOrigin: 'Scotland', logoUrl: '', description: 'Double-aged blended Scotch whisky.' },
  { id: 'b_teachers', name: "Teacher's", slug: 'teachers', countryOfOrigin: 'Scotland', logoUrl: '', description: 'Highland Cream blended Scotch whisky.' },
  { id: 'b_antiquity', name: 'Antiquity', slug: 'antiquity', countryOfOrigin: 'India', logoUrl: '', description: 'Ultra premium blue blended whisky.' },
  { id: 'b_signature', name: 'Signature', slug: 'signature', countryOfOrigin: 'India', logoUrl: '', description: 'Master crafted rare aged blended whisky.' },
  { id: 'b_royalchallenge', name: 'Royal Challenge', slug: 'royal-challenge', countryOfOrigin: 'India', logoUrl: '', description: 'Finest premium grain blended whisky.' },
  { id: 'b_rockford', name: 'Rockford Reserve', slug: 'rockford-reserve', countryOfOrigin: 'India', logoUrl: '', description: 'Finest blended reserve whisky.' },
  { id: 'b_officerschoice', name: "Officer's Choice", slug: 'officers-choice', countryOfOrigin: 'India', logoUrl: '', description: 'Widely popular Indian deluxe whisky.' },
  { id: 'b_sterlingreserve', name: 'Sterling Reserve', slug: 'sterling-reserve', countryOfOrigin: 'India', logoUrl: '', description: 'B7 premium blended whisky.' },

  // Beer
  { id: 'b_kingfisher', name: 'Kingfisher', slug: 'kingfisher', countryOfOrigin: 'India', logoUrl: '', description: 'The King of Good Times; premium & strong lagers.' },
  { id: 'b_budweiser', name: 'Budweiser', slug: 'budweiser', countryOfOrigin: 'United States', logoUrl: '', description: 'The King of Beers; Premium & Magnum strong.' },
  { id: 'b_heineken', name: 'Heineken', slug: 'heineken', countryOfOrigin: 'Netherlands', logoUrl: '', description: 'World-famous Dutch pure malt lager.' },
  { id: 'b_corona', name: 'Corona Extra', slug: 'corona-extra', countryOfOrigin: 'Mexico', logoUrl: '', description: 'Classic Mexican refreshing lager.' },
  { id: 'b_carlsberg', name: 'Carlsberg', slug: 'carlsberg', countryOfOrigin: 'Denmark', logoUrl: '', description: 'Danish pilsner & Elephant strong lager.' },
  { id: 'b_bira91', name: 'Bira 91', slug: 'bira-91', countryOfOrigin: 'India', logoUrl: '', description: 'Modern craft beers (Blonde, White, Boom).' },
  { id: 'b_tuborg', name: 'Tuborg', slug: 'tuborg', countryOfOrigin: 'Denmark', logoUrl: '', description: 'Green premium quality lager.' },
  { id: 'b_fosters', name: "Foster's", slug: 'fosters', countryOfOrigin: 'Australia', logoUrl: '', description: 'Australian lager beer.' },
  { id: 'b_miller', name: 'Miller', slug: 'miller', countryOfOrigin: 'United States', logoUrl: '', description: 'High Life American lager.' },
  { id: 'b_hoegaarden', name: 'Hoegaarden', slug: 'hoegaarden', countryOfOrigin: 'Belgium', logoUrl: '', description: 'Authentic Belgian wheat beer.' },
  { id: 'b_asahi', name: 'Asahi', slug: 'asahi', countryOfOrigin: 'Japan', logoUrl: '', description: 'Super Dry Japanese karakuchi lager.' },

  // Vodka
  { id: 'b_smirnoff', name: 'Smirnoff', slug: 'smirnoff', countryOfOrigin: 'United Kingdom', logoUrl: '', description: 'Triple distilled crystal vodka.' },
  { id: 'b_absolut', name: 'Absolut', slug: 'absolut', countryOfOrigin: 'Sweden', logoUrl: '', description: 'Pure Swedish winter wheat vodka.' },
  { id: 'b_magicmoments', name: 'Magic Moments', slug: 'magic-moments', countryOfOrigin: 'India', logoUrl: '', description: 'India’s top selling grain vodka.' },
  { id: 'b_romanov', name: 'Romanov', slug: 'romanov', countryOfOrigin: 'India', logoUrl: '', description: 'Classic pure Russian-style vodka.' },
  { id: 'b_whitemischief', name: 'White Mischief', slug: 'white-mischief', countryOfOrigin: 'India', logoUrl: '', description: 'Ultra pure party vodka.' },
  { id: 'b_greygoose', name: 'Grey Goose', slug: 'grey-goose', countryOfOrigin: 'France', logoUrl: '', description: 'French luxury wheat vodka from Cognac.' },
  { id: 'b_belvedere', name: 'Belvedere', slug: 'belvedere', countryOfOrigin: 'Poland', logoUrl: '', description: 'Polish rye luxury vodka.' },
  { id: 'b_finlandia', name: 'Finlandia', slug: 'finlandia', countryOfOrigin: 'Finland', logoUrl: '', description: 'Pure glacial spring water vodka.' },
  { id: 'b_skyy', name: 'Skyy', slug: 'skyy', countryOfOrigin: 'United States', logoUrl: '', description: 'Quadruple distilled American vodka.' },

  // Rum
  { id: 'b_oldmonk', name: 'Old Monk', slug: 'old-monk', countryOfOrigin: 'India', logoUrl: '', description: 'Legendary vatted dark Indian rum.' },
  { id: 'b_bacardi', name: 'Bacardi', slug: 'bacardi', countryOfOrigin: 'Puerto Rico', logoUrl: '', description: 'Superior white, black & gold rums.' },
  { id: 'b_captainmorgan', name: 'Captain Morgan', slug: 'captain-morgan', countryOfOrigin: 'Jamaica', logoUrl: '', description: 'Original spiced Caribbean gold rum.' },
  { id: 'b_contessa', name: 'Contessa', slug: 'contessa', countryOfOrigin: 'India', logoUrl: '', description: 'Special reserve XXX dark rum.' },
  { id: 'b_havanaclub', name: 'Havana Club', slug: 'havana-club', countryOfOrigin: 'Cuba', logoUrl: '', description: 'Authentic aged Cuban rum.' },

  // Gin
  { id: 'b_bombaysapphire', name: 'Bombay Sapphire', slug: 'bombay-sapphire', countryOfOrigin: 'United Kingdom', logoUrl: '', description: 'Vapour-infused London dry gin.' },
  { id: 'b_gordons', name: "Gordon's", slug: 'gordons', countryOfOrigin: 'United Kingdom', logoUrl: '', description: 'Classic London dry gin.' },
  { id: 'b_tanqueray', name: 'Tanqueray', slug: 'tanqueray', countryOfOrigin: 'United Kingdom', logoUrl: '', description: 'Four-times distilled London dry gin.' },
  { id: 'b_hendricks', name: "Hendrick's", slug: 'hendricks', countryOfOrigin: 'Scotland', logoUrl: '', description: 'Cucumber and rose petal infused Scottish gin.' },
  { id: 'b_greaterthan', name: 'Greater Than', slug: 'greater-than', countryOfOrigin: 'India', logoUrl: '', description: 'India’s pioneering London dry craft gin.' },
  { id: 'b_hapusa', name: 'Hapusa', slug: 'hapusa', countryOfOrigin: 'India', logoUrl: '', description: 'Himalayan juniper berry craft gin.' },
  { id: 'b_blueriband', name: 'Blue Riband', slug: 'blue-riband', countryOfOrigin: 'India', logoUrl: '', description: 'Classic Indian cocktail gin.' },
  { id: 'b_beefeater', name: 'Beefeater', slug: 'beefeater', countryOfOrigin: 'United Kingdom', logoUrl: '', description: 'Authentic 9-botanical London dry gin.' },

  // Brandy
  { id: 'b_mansionhouse', name: 'Mansion House', slug: 'mansion-house', countryOfOrigin: 'India', logoUrl: '', description: 'French pure grape brandy.' },
  { id: 'b_honeybee', name: 'Honey Bee', slug: 'honey-bee', countryOfOrigin: 'India', logoUrl: '', description: 'Rich blended grape brandy.' },
  { id: 'b_morpheus', name: 'Morpheus', slug: 'morpheus', countryOfOrigin: 'India', logoUrl: '', description: 'XO premium French style brandy.' },
  { id: 'b_stremy', name: 'St-Rémy', slug: 'st-remy', countryOfOrigin: 'France', logoUrl: '', description: 'Authentic French VSOP brandy.' },
  { id: 'b_hennessy', name: 'Hennessy', slug: 'hennessy', countryOfOrigin: 'France', logoUrl: '', description: 'World’s foremost cognac house.' },

  // Wine
  { id: 'b_sula', name: 'Sula Vineyards', slug: 'sula', countryOfOrigin: 'India', logoUrl: '', description: 'Nashik estate wines and sparkling tropicale.' },
  { id: 'b_fratelli', name: 'Fratelli', slug: 'fratelli', countryOfOrigin: 'India', logoUrl: '', description: 'Indo-Italian viticulture estate wines.' },
  { id: 'b_groverzampa', name: 'Grover Zampa', slug: 'grover-zampa', countryOfOrigin: 'India', logoUrl: '', description: 'Pioneering Indian fine reserve wines.' },
  { id: 'b_jacobscreek', name: "Jacob's Creek", slug: 'jacobs-creek', countryOfOrigin: 'Australia', logoUrl: '', description: 'Australian Barossa Valley wines.' },
  { id: 'b_fourseasons', name: 'Four Seasons', slug: 'four-seasons', countryOfOrigin: 'India', logoUrl: '', description: 'Barrique reserve Indian wines.' },
  { id: 'b_york', name: 'York Winery', slug: 'york', countryOfOrigin: 'India', logoUrl: '', description: 'Arros handcrafted barrel-aged wines.' },
  { id: 'b_bigbanyan', name: 'Big Banyan', slug: 'big-banyan', countryOfOrigin: 'India', logoUrl: '', description: 'Cabernet and Merlot varietals.' },
  { id: 'b_hardys', name: 'Hardys', slug: 'hardys', countryOfOrigin: 'Australia', logoUrl: '', description: 'Varietal reserve Australian wines.' },
  { id: 'b_yellowtail', name: '[yellow tail]', slug: 'yellow-tail', countryOfOrigin: 'Australia', logoUrl: '', description: 'Crisp and fruit-forward Australian wines.' },

  // Tequila & Sparkling
  { id: 'b_josecuervo', name: 'Jose Cuervo', slug: 'jose-cuervo', countryOfOrigin: 'Mexico', logoUrl: '', description: 'World’s oldest tequila brand.' },
  { id: 'b_donjulio', name: 'Don Julio', slug: 'don-julio', countryOfOrigin: 'Mexico', logoUrl: '', description: 'Handcrafted 100% blue agave tequila.' },
  { id: 'b_patron', name: 'Patrón', slug: 'patron', countryOfOrigin: 'Mexico', logoUrl: '', description: 'Ultra-premium artisanal tequila.' },
  { id: 'b_1800tequila', name: '1800 Tequila', slug: '1800-tequila', countryOfOrigin: 'Mexico', logoUrl: '', description: '100% agave Reposado and Blanco.' },
  { id: 'b_eljimador', name: 'El Jimador', slug: 'el-jimador', countryOfOrigin: 'Mexico', logoUrl: '', description: 'Handmade Mexican blue agave tequila.' },
  { id: 'b_moetchandon', name: 'Moët & Chandon', slug: 'moet-chandon', countryOfOrigin: 'France', logoUrl: '', description: 'Prestigious Épernay Champagne house.' },
  { id: 'b_chandon', name: 'Chandon', slug: 'chandon', countryOfOrigin: 'India', logoUrl: '', description: 'Méthode traditionnelle sparkling wine from Nashik.' },
  { id: 'b_freixenet', name: 'Freixenet', slug: 'freixenet', countryOfOrigin: 'Spain', logoUrl: '', description: 'Renowned Cordon Negro Cava.' },
  { id: 'b_martini', name: 'Martini', slug: 'martini', countryOfOrigin: 'Italy', logoUrl: '', description: 'Italian Asti DOCG sparkling wine.' },

  // Water & Non-Alcoholic Drinks
  { id: 'b_bisleri', name: 'Bisleri', slug: 'bisleri', countryOfOrigin: 'India', logoUrl: '', description: 'India’s most trusted mineral water brand.' },
  { id: 'b_kinley', name: 'Kinley', slug: 'kinley', countryOfOrigin: 'India', logoUrl: '', description: 'Packaged water & carbonated soda from Coca-Cola.' },
  { id: 'b_aquafina', name: 'Aquafina', slug: 'aquafina', countryOfOrigin: 'India', logoUrl: '', description: 'Purified drinking water from PepsiCo.' },
  { id: 'b_bailley', name: 'Bailley', slug: 'bailley', countryOfOrigin: 'India', logoUrl: '', description: 'Packaged drinking water from Parle Agro.' },
  { id: 'b_himalayan', name: 'Himalayan', slug: 'himalayan', countryOfOrigin: 'India', logoUrl: '', description: 'Natural mineral water from the Shivalik range.' },
  { id: 'b_vedica', name: 'Vedica', slug: 'vedica', countryOfOrigin: 'India', logoUrl: '', description: 'Natural mountain spring water from Bisleri.' },
  { id: 'b_tatacopper', name: 'Tata Copper+', slug: 'tata-copper', countryOfOrigin: 'India', logoUrl: '', description: 'Copper-enriched pure drinking water.' },

  // Soft Drinks & Mixers
  { id: 'b_cocacola', name: 'Coca-Cola', slug: 'coca-cola', countryOfOrigin: 'United States', logoUrl: '', description: 'The world’s classic cola.' },
  { id: 'b_pepsi', name: 'Pepsi', slug: 'pepsi', countryOfOrigin: 'United States', logoUrl: '', description: 'Bold and refreshing cola.' },
  { id: 'b_sprite', name: 'Sprite', slug: 'sprite', countryOfOrigin: 'United States', logoUrl: '', description: 'Clear lemon-lime refreshment.' },
  { id: 'b_7up', name: '7UP', slug: '7up', countryOfOrigin: 'United States', logoUrl: '', description: 'Crisp lemon-lime soda.' },
  { id: 'b_fanta', name: 'Fanta', slug: 'fanta', countryOfOrigin: 'United States', logoUrl: '', description: 'Sparkling orange flavour.' },
  { id: 'b_thumsup', name: 'Thums Up', slug: 'thums-up', countryOfOrigin: 'India', logoUrl: '', description: 'Charged strong Indian cola.' },
  { id: 'b_limca', name: 'Limca', slug: 'limca', countryOfOrigin: 'India', logoUrl: '', description: 'Fresh lime and lemon drink.' },
  { id: 'b_mountaindew', name: 'Mountain Dew', slug: 'mountain-dew', countryOfOrigin: 'United States', logoUrl: '', description: 'Citrus flavoured exhilarating soda.' },
  { id: 'b_mirinda', name: 'Mirinda', slug: 'mirinda', countryOfOrigin: 'United States', logoUrl: '', description: 'Fizzy tangy orange drink.' },
  { id: 'b_schweppes', name: 'Schweppes', slug: 'schweppes', countryOfOrigin: 'Switzerland', logoUrl: '', description: 'Tonic water, ginger ale and club soda.' },
  { id: 'b_fevertree', name: 'Fever-Tree', slug: 'fever-tree', countryOfOrigin: 'United Kingdom', logoUrl: '', description: 'Artisanal natural tonic waters and mixers.' },
  { id: 'b_svami', name: 'Svami', slug: 'svami', countryOfOrigin: 'India', logoUrl: '', description: 'Progressive Indian botanical craft mixers.' },
  { id: 'b_paperboat', name: 'Paper Boat', slug: 'paper-boat', countryOfOrigin: 'India', logoUrl: '', description: 'Nostalgic Indian drinks and sparkling water.' },

  // Energy Drinks & Juices
  { id: 'b_redbull', name: 'Red Bull', slug: 'red-bull', countryOfOrigin: 'Austria', logoUrl: '', description: 'World leader in energy drinks.' },
  { id: 'b_monster', name: 'Monster Energy', slug: 'monster-energy', countryOfOrigin: 'United States', logoUrl: '', description: 'High-octane energy drinks.' },
  { id: 'b_sting', name: 'Sting', slug: 'sting', countryOfOrigin: 'India', logoUrl: '', description: 'Caffeinated energy drink from PepsiCo.' },
  { id: 'b_hellenergy', name: 'Hell Energy', slug: 'hell-energy', countryOfOrigin: 'Hungary', logoUrl: '', description: 'Classic European energy drink.' },
  { id: 'b_cloud9', name: 'Cloud 9', slug: 'cloud-9', countryOfOrigin: 'India', logoUrl: '', description: 'Original energy boost drink.' },
  { id: 'b_tzinga', name: 'Tzinga', slug: 'tzinga', countryOfOrigin: 'India', logoUrl: '', description: 'Energy drink pouch and cans.' },
  { id: 'b_real', name: 'Real', slug: 'real', countryOfOrigin: 'India', logoUrl: '', description: 'Dabur Real 100% fruit juices.' },
  { id: 'b_tropicana', name: 'Tropicana', slug: 'tropicana', countryOfOrigin: 'United States', logoUrl: '', description: 'Pure 100% juice and fruit drinks.' },
  { id: 'b_bnatural', name: 'B-Natural', slug: 'b-natural', countryOfOrigin: 'India', logoUrl: '', description: 'ITC pure fruit juices.' },
  { id: 'b_minutemaid', name: 'Minute Maid', slug: 'minute-maid', countryOfOrigin: 'United States', logoUrl: '', description: 'Pulpy orange and fruit drinks.' },
  { id: 'b_appyfizz', name: 'Appy Fizz', slug: 'appy-fizz', countryOfOrigin: 'India', logoUrl: '', description: 'Sparkling apple juice drink from Parle Agro.' },
  { id: 'b_maaza', name: 'Maaza', slug: 'maaza', countryOfOrigin: 'India', logoUrl: '', description: 'Real Alphonso mango pulp drink.' },
  { id: 'b_slice', name: 'Slice', slug: 'slice', countryOfOrigin: 'India', logoUrl: '', description: 'Thick mango drink from PepsiCo.' },
  { id: 'b_frooti', name: 'Frooti', slug: 'frooti', countryOfOrigin: 'India', logoUrl: '', description: 'Fresh mango treat from Parle Agro.' },

  // Food & Munchies
  { id: 'b_lays', name: "Lay's", slug: 'lays', countryOfOrigin: 'India', logoUrl: '', description: 'Classic Salted, Magic Masala & Cream Onion potato chips.' },
  { id: 'b_bingo', name: 'Bingo!', slug: 'bingo', countryOfOrigin: 'India', logoUrl: '', description: 'Mad Angles and Tedhe Medhe spicy snacks.' },
  { id: 'b_pringles', name: 'Pringles', slug: 'pringles', countryOfOrigin: 'Malaysia', logoUrl: '', description: 'Crisp stacked potato crisps.' },
  { id: 'b_unclechipps', name: 'Uncle Chipps', slug: 'uncle-chipps', countryOfOrigin: 'India', logoUrl: '', description: 'Bole Mere Lips, I Love Uncle Chipps!' },
  { id: 'b_haldirams', name: "Haldiram's", slug: 'haldirams', countryOfOrigin: 'India', logoUrl: '', description: 'Nagpur & Delhi namkeen, bhujia and ready meals.' },
  { id: 'b_bikaji', name: 'Bikaji', slug: 'bikaji', countryOfOrigin: 'India', logoUrl: '', description: 'Authentic Bikaneri bhujia and sev.' },
  { id: 'b_balaji', name: 'Balaji', slug: 'balaji', countryOfOrigin: 'India', logoUrl: '', description: 'Ratlami sev, wafers and savoury snacks.' },
  { id: 'b_nutraj', name: 'Nutraj', slug: 'nutraj', countryOfOrigin: 'India', logoUrl: '', description: 'Premium California almonds, cashews and trail mix.' },
  { id: 'b_cornitos', name: 'Cornitos', slug: 'cornitos', countryOfOrigin: 'India', logoUrl: '', description: 'Crisp corn nacho crisps.' },
  { id: 'b_doritos', name: 'Doritos', slug: 'doritos', countryOfOrigin: 'India', logoUrl: '', description: 'Nacho Cheese & Sweet Chilli tortilla chips.' },
  { id: 'b_makino', name: 'Makino', slug: 'makino', countryOfOrigin: 'India', logoUrl: '', description: 'Jalapeno & salsa nacho crisps.' },
  { id: 'b_actii', name: 'Act II', slug: 'act-ii', countryOfOrigin: 'India', logoUrl: '', description: 'Instant butter lovers and salted microwave popcorn.' },
  { id: 'b_tooyumm', name: 'Too Yumm!', slug: 'too-yumm', countryOfOrigin: 'India', logoUrl: '', description: 'Baked karare and gourmet munchies.' },
  { id: 'b_4700bc', name: '4700BC', slug: '4700bc', countryOfOrigin: 'India', logoUrl: '', description: 'Gourmet artisanal cheese and caramel popcorn.' },
  { id: 'b_mtr', name: 'MTR', slug: 'mtr', countryOfOrigin: 'India', logoUrl: '', description: 'Ready-to-eat authentic curries and meals.' },
  { id: 'b_kitchensofindia', name: 'Kitchens of India', slug: 'kitchens-of-india', countryOfOrigin: 'India', logoUrl: '', description: 'ITC gourmet ready feast curries.' },

  // Party Essentials
  { id: 'b_homeone', name: 'Home One', slug: 'home-one', countryOfOrigin: 'India', logoUrl: '', description: 'Paper napkins, disposable plates, bowls and cups.' },
  { id: 'b_origami', name: 'Origami', slug: 'origami', countryOfOrigin: 'India', logoUrl: '', description: 'Soft table napkins, paper straws and cups.' },
  { id: 'b_ecosoul', name: 'EcoSoul', slug: 'ecosoul', countryOfOrigin: 'India', logoUrl: '', description: '100% natural areca palm leaf plates, bowls and wooden cutlery.' },
  { id: 'b_partytime', name: 'PartyTime Essentials', slug: 'partytime-essentials', countryOfOrigin: 'India', logoUrl: '', description: 'Red solo cups, tumblers, ice bags, openers and party balloons.' },
  { id: 'b_freshwrap', name: 'Freshwrap', slug: 'freshwrap', countryOfOrigin: 'India', logoUrl: '', description: 'Food grade aluminium foil and cling film.' },
];
