import { Category } from '../types.ts';

export const SEED_CATEGORIES: Category[] = [
  // Alcohol Categories
  {
    id: 'cat_whisky',
    name: 'Whisky',
    slug: 'whisky',
    description: 'Blended Scotch, single malts and Indian premium whiskies.',
    imageUrl: '/images/categories/whisky.webp',
    subcategories: ['Indian Whisky', 'Indian Premium', 'Blended Scotch', 'Single Malt', 'Irish Whiskey', 'Bourbon'],
    isActive: true,
  },
  {
    id: 'cat_beer',
    name: 'Beer',
    slug: 'beer',
    description: 'Chilled lagers, strong beers, wheat beers and imported crafts.',
    imageUrl: '/images/categories/beer.webp',
    subcategories: ['Lager', 'Strong Beer', 'Craft Wheat', 'Imported Beer', 'Multipack'],
    isActive: true,
  },
  {
    id: 'cat_vodka',
    name: 'Vodka',
    slug: 'vodka',
    description: 'Grain vodkas, triple-distilled, flavoured and European luxury spirits.',
    imageUrl: '/images/categories/vodka.webp',
    subcategories: ['Grain Vodka', 'Flavoured Vodka', 'Luxury Vodka'],
    isActive: true,
  },
  {
    id: 'cat_rum',
    name: 'Rum',
    slug: 'rum',
    description: 'Dark vatted rum, white rum, spiced gold and Caribbean reserve.',
    imageUrl: '/images/categories/rum.webp',
    subcategories: ['Dark Rum', 'White Rum', 'Spiced Gold Rum'],
    isActive: true,
  },
  {
    id: 'cat_gin',
    name: 'Gin',
    slug: 'gin',
    description: 'London dry gins, Himalayan botanical and Indian artisanal craft gins.',
    imageUrl: '/images/categories/gin.webp',
    subcategories: ['London Dry', 'Craft Botanical', 'Flavoured Gin'],
    isActive: true,
  },
  {
    id: 'cat_brandy',
    name: 'Brandy',
    slug: 'brandy',
    description: 'Pure French grape brandy, VSOP and vintage cognacs.',
    imageUrl: '/images/categories/brandy.webp',
    subcategories: ['Indian Grape Brandy', 'French VSOP', 'Cognac'],
    isActive: true,
  },
  {
    id: 'cat_wine',
    name: 'Wine',
    slug: 'wine',
    description: 'Red, white, rosé and estate bottled reserve wines.',
    imageUrl: '/images/categories/wine.webp',
    subcategories: ['Red Wine', 'White Wine', 'Rosé', 'Dessert Wine'],
    isActive: true,
  },
  {
    id: 'cat_tequila',
    name: 'Tequila',
    slug: 'tequila',
    description: '100% blue agave Blanco, Reposado and Añejo tequilas.',
    imageUrl: '/images/categories/tequila.webp',
    subcategories: ['Blanco', 'Reposado', 'Añejo'],
    isActive: true,
  },
  {
    id: 'cat_liqueurs',
    name: 'Liqueurs',
    slug: 'liqueurs',
    description: 'Aperitifs, digestifs and party shots.',
    imageUrl: '/images/categories/liqueurs.webp',
    subcategories: ['Cream Liqueur', 'Herbal Liqueur', 'Coffee Liqueur'],
    isActive: true,
  },
  {
    id: 'cat_sparkling',
    name: 'Sparkling Wine',
    slug: 'sparkling-wine',
    description: 'Champagne, Prosecco, Cava and sparkling wines.',
    imageUrl: '/images/categories/sparkling-wine.webp',
    subcategories: ['Champagne', 'Sparkling Brut', 'Asti'],
    isActive: true,
  },
  {
    id: 'cat_premium',
    name: 'Premium / Imported',
    slug: 'premium-imported',
    description: 'Exclusive top-shelf single malts, aged cognacs and luxury spirits.',
    imageUrl: '/images/categories/premium-imported.webp',
    subcategories: ['Imported Scotch', 'Luxury Vodka', 'Aged Tequila', 'Champagne'],
    isActive: true,
  },

  // Drinks Categories
  {
    id: 'cat_water',
    name: 'Water',
    slug: 'water',
    description: 'Chilled packaged drinking water, natural mineral water and multipacks.',
    imageUrl: '/images/categories/water.webp',
    subcategories: ['Packaged Drinking Water', 'Natural Mineral Water', 'Multipack'],
    isActive: true,
  },
  {
    id: 'cat_softdrinks',
    name: 'Soft Drinks',
    slug: 'soft-drinks',
    description: 'Chilled colas, lemon-lime, orange and sparkling soda cans and bottles.',
    imageUrl: '/images/categories/soft-drinks.webp',
    subcategories: ['Cola', 'Lemon-Lime', 'Orange & Citrus', 'Can 300ml', 'Bottle 750ml'],
    isActive: true,
  },
  {
    id: 'cat_mixers',
    name: 'Soda & Mixers',
    slug: 'soda-mixers',
    description: 'Club soda, artisanal tonic water, ginger ale and cocktail mixers.',
    imageUrl: '/images/categories/soda-mixers.webp',
    subcategories: ['Club Soda', 'Tonic Water', 'Ginger Ale', 'Sparkling Water', 'Cocktail Mixers'],
    isActive: true,
  },
  {
    id: 'cat_energy',
    name: 'Energy Drinks',
    slug: 'energy-drinks',
    description: 'Caffeinated energy drinks, taurine boosters and zero-sugar cans.',
    imageUrl: '/images/categories/energy-drinks.webp',
    subcategories: ['Original Energy', 'Sugar Free', 'Multipack Cans'],
    isActive: true,
  },
  {
    id: 'cat_juices',
    name: 'Juices',
    slug: 'juices',
    description: '100% fruit juices, nectars, cranberry cocktail mixers and mango drinks.',
    imageUrl: '/images/categories/juices.webp',
    subcategories: ['Fruit Juice 1L', 'Cranberry Mixer', 'Mango Drinks', 'Sparkling Fruit'],
    isActive: true,
  },

  // Food Categories
  {
    id: 'cat_snacks',
    name: 'Chips & Namkeen',
    slug: 'chips-namkeen',
    description: 'Crispy potato chips, aloo bhujia, sev and crunchy namkeen.',
    imageUrl: '/images/categories/chips-namkeen.webp',
    subcategories: ['Potato Chips', 'Aloo Bhujia', 'Sev & Mixture', 'Namkeen'],
    isActive: true,
  },
  {
    id: 'cat_nuts',
    name: 'Peanuts & Nuts',
    slug: 'peanuts-nuts',
    description: 'Salted peanuts, masala nuts, cashews, almonds and party trail mix.',
    imageUrl: '/images/categories/peanuts-nuts.webp',
    subcategories: ['Salted Peanuts', 'Masala Peanuts', 'Cashews', 'Almonds', 'Trail Mix'],
    isActive: true,
  },
  {
    id: 'cat_nachos',
    name: 'Nachos',
    slug: 'nachos',
    description: 'Crisp corn tortilla nachos, cheese dips and spicy salsa pairings.',
    imageUrl: '/images/categories/nachos.webp',
    subcategories: ['Cheese Nachos', 'Barbeque & Chilli', 'Jalapeno'],
    isActive: true,
  },
  {
    id: 'cat_popcorn',
    name: 'Popcorn',
    slug: 'popcorn',
    description: 'Butter popcorn, classic salted and gourmet cheese munchies.',
    imageUrl: '/images/categories/popcorn.webp',
    subcategories: ['Butter Lovers', 'Salted Popcorn', 'Gourmet Cheese'],
    isActive: true,
  },
  {
    id: 'cat_partysnacks',
    name: 'Party Snacks',
    slug: 'party-snacks',
    description: 'Crunchy party munchies, extruded snacks and savoury bites.',
    imageUrl: '/images/categories/party-snacks.webp',
    subcategories: ['Kurkure', 'Party Mixture', 'Spicy Rings'],
    isActive: true,
  },
  {
    id: 'cat_readytoeat',
    name: 'Ready-to-Eat',
    slug: 'ready-to-eat',
    description: 'Dal makhani, rajma, paneer butter masala and late night party meals.',
    imageUrl: '/images/categories/ready-to-eat.webp',
    subcategories: ['Dal Makhani & Gravies', 'Rajma & Chana', 'Paneer Curries'],
    isActive: true,
  },

  // Party Essentials Categories
  {
    id: 'cat_party_glasses',
    name: 'Disposable Glasses',
    slug: 'disposable-glasses',
    description: 'Disposable plastic glasses, paper cups, hard plastic tumblers and red solo cups.',
    imageUrl: '/images/categories/disposable-glasses.webp',
    subcategories: ['250 ml', '300 ml', '500 ml', 'Red Solo Cups', 'Paper Cups'],
    isActive: true,
  },
  {
    id: 'cat_party_plates',
    name: 'Disposable Plates',
    slug: 'disposable-plates',
    description: 'Paper plates, 3-compartment thali plates, areca leaf and heavy plastic plates.',
    imageUrl: '/images/categories/disposable-plates.webp',
    subcategories: ['7" Plates', '9" Plates', '10" Heavy Plates', 'Compartment Plates', 'Areca Palm Leaf'],
    isActive: true,
  },
  {
    id: 'cat_party_bowls',
    name: 'Bowls',
    slug: 'bowls',
    description: 'Paper bowls, plastic snack bowls and natural areca serving bowls.',
    imageUrl: '/images/categories/bowls.webp',
    subcategories: ['Paper Bowls', 'Snack Bowls', 'Soup Bowls', 'Areca Bowls'],
    isActive: true,
  },
  {
    id: 'cat_party_cutlery',
    name: 'Cutlery',
    slug: 'cutlery',
    description: 'Disposable spoons, forks, knives, wooden cutlery and all-in-one meal combos.',
    imageUrl: '/images/categories/cutlery.webp',
    subcategories: ['Spoons', 'Forks', 'Knives', 'Wooden Cutlery', 'Combo Sets'],
    isActive: true,
  },
  {
    id: 'cat_party_napkins',
    name: 'Napkins',
    slug: 'napkins',
    description: 'Table paper napkins, cocktail napkins, 2-ply soft napkins and tissue rolls.',
    imageUrl: '/images/categories/napkins.webp',
    subcategories: ['Table Napkins', 'Cocktail Napkins', '2-Ply Napkins', '3-Ply Luxury'],
    isActive: true,
  },
  {
    id: 'cat_party_straws',
    name: 'Straws',
    slug: 'straws',
    description: 'Biodegradable paper straws, neon bendable cocktail straws and jumbo smoothie straws.',
    imageUrl: '/images/categories/straws.webp',
    subcategories: ['Paper Straws', 'Bendable Straws', 'Jumbo Straws', 'Silicone Reusable'],
    isActive: true,
  },
  {
    id: 'cat_party',
    name: 'Other Party Essentials',
    slug: 'party-essentials',
    description: 'Ice bags, toothpicks, openers, corkscrews, balloons, candles, foil and garbage bags.',
    imageUrl: '/images/categories/party-essentials.webp',
    subcategories: ['Bottle Openers & Corkscrews', 'Ice Bags & Accessories', 'Balloons & Candles', 'Foil & Wrap', 'Garbage Bags & Wipes'],
    isActive: true,
  },
];
