import { Category } from '../types.ts';

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'cat_whisky',
    name: 'Whisky',
    slug: 'whisky',
    description: 'Single malts, blended Scotch, Indian premium grains, and fine whiskies',
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Indian Malt', 'Blended Scotch', 'Single Malt', 'Premium Grain', 'Bourbon', 'Irish Whiskey'],
    isActive: true,
  },
  {
    id: 'cat_beer',
    name: 'Beer & Ciders',
    slug: 'beer',
    description: 'Chilled lagers, strong beers, craft wheat beers, and smooth ales',
    imageUrl: 'https://images.unsplash.com/photo-1608270199182-4faeb9ff7584?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Strong Lager', 'Premium Mild', 'Wheat Beer', 'Craft Beer', 'Hard Cider'],
    isActive: true,
  },
  {
    id: 'cat_vodka',
    name: 'Vodka',
    slug: 'vodka',
    description: 'Triple-distilled pure grain, flavored, and artisanal vodkas',
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Grain Vodka', 'Green Apple', 'Orange', 'Craft Vodka'],
    isActive: true,
  },
  {
    id: 'cat_rum',
    name: 'Rum',
    slug: 'rum',
    description: 'Legendary Indian dark rums, spiced blends, and Caribbean white rums',
    imageUrl: 'https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Dark Rum', 'White Rum', 'Spiced Rum', 'Flavoured Rum'],
    isActive: true,
  },
  {
    id: 'cat_gin',
    name: 'Gin',
    slug: 'gin',
    description: 'Indian craft botanical gins, London dry, and floral distillates',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Craft Botanical', 'London Dry', 'Pink Gin'],
    isActive: true,
  },
  {
    id: 'cat_brandy',
    name: 'Brandy',
    slug: 'brandy',
    description: 'Matured grape brandies and premium French blends',
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Grape Brandy', 'VSOP', 'XO'],
    isActive: true,
  },
  {
    id: 'cat_wine',
    name: 'Wine',
    slug: 'wine',
    description: 'Indian estate red wines, crisp whites, and delicate sparkling wines',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Red Wine', 'White Wine', 'Rosé', 'Sparkling Wine'],
    isActive: true,
  },
  {
    id: 'cat_tequila',
    name: 'Tequila',
    slug: 'tequila',
    description: '100% Blue Agave Blanco, Reposado, and celebratory Tequilas',
    imageUrl: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Blanco / Silver', 'Reposado', 'Añejo'],
    isActive: true,
  },
  {
    id: 'cat_liqueurs',
    name: 'Liqueurs',
    slug: 'liqueurs',
    description: 'Irish cream, coffee liqueurs, and herbal party digestifs',
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Cream Liqueur', 'Herbal Liqueur', 'Coffee Liqueur'],
    isActive: true,
  },
  {
    id: 'cat_champagne',
    name: 'Champagne & Sparkling',
    slug: 'champagne',
    description: 'Celebratory French champagne and sparkling party wines',
    imageUrl: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Brut Champagne', 'Indian Sparkling', 'Prosecco'],
    isActive: true,
  },
  {
    id: 'cat_rtd',
    name: 'Ready To Drink',
    slug: 'ready-to-drink',
    description: 'Fruity breezers, craft hard seltzers, and pre-mixed cans',
    imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Fruit Breezers', 'Hard Seltzer'],
    isActive: true,
  },
  {
    id: 'cat_mixers',
    name: 'Mixers & Tonics',
    slug: 'mixers',
    description: 'Cocktail mixers, ginger ale, tonic water, and premium club soda',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Cocktail Mixers', 'Tonic Water', 'Ginger Ale', 'Club Soda'],
    isActive: true,
  },
  {
    id: 'cat_softdrinks',
    name: 'Soft Drinks & Energy',
    slug: 'softdrinks',
    description: 'Thums Up, Coca-Cola, Sprite, Red Bull, and zero-sugar soft drinks',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Colas & Sodas', 'Energy Drinks', 'Fruit Juices', 'Zero Sugar'],
    isActive: true,
  },
  {
    id: 'cat_water',
    name: 'Water & Hydration',
    slug: 'water',
    description: 'Chilled packaged water, natural Himalayan mineral water, and sparkling soda',
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Packaged Drinking Water', 'Natural Mineral Water', 'Sparkling Water'],
    isActive: true,
  },
  {
    id: 'cat_snacks',
    name: 'Bar Snacks & Munchies',
    slug: 'snacks',
    description: 'Haldiram bhujia, salted peanuts, nachos with dip, and chakna platters',
    imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Traditional Namkeen', 'Crisps & Chips', 'Roasted Chakna', 'Nachos & Dips'],
    isActive: true,
  },
  {
    id: 'cat_party',
    name: 'Party Essentials & Ice',
    slug: 'party-essentials',
    description: 'Food-grade ice cubes, red party cups, cocktail shakers, and bottle openers',
    imageUrl: 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Party Ice Cubes', 'Barware & Openers', 'Glassware & Cups', 'Party Disposables'],
    isActive: true,
  },
];
