import { Coupon } from '../types.ts';

export const SEED_COUPONS: Coupon[] = [
  {
    id: 'coup_welcome50',
    code: 'WELCOME50',
    description: 'Flat ₹50 OFF on your first DrinkIt order in UP & Delhi (Min. ₹499)',
    discountType: 'fixed',
    discountValue: 50,
    minOrderValue: 499,
    validUntil: '2026-12-31',
    isActive: true,
    overallUsageLimit: 1000,
    overallUsageCount: 238,
    userUsageLimit: 1,
  },
  {
    id: 'coup_cheers100',
    code: 'CHEERS100',
    description: 'Flat ₹100 OFF on orders above ₹1499',
    discountType: 'fixed',
    discountValue: 100,
    minOrderValue: 1499,
    validUntil: '2026-12-31',
    isActive: true,
    overallUsageLimit: 500,
    overallUsageCount: 164,
    userUsageLimit: 3,
  },
  {
    id: 'coup_party15',
    code: 'PARTY15',
    description: '15% OFF up to ₹350 for celebrations above ₹2499',
    discountType: 'percentage',
    discountValue: 15,
    minOrderValue: 2499,
    maxDiscount: 350,
    validUntil: '2026-12-31',
    isActive: true,
    overallUsageLimit: 300,
    overallUsageCount: 82,
    userUsageLimit: 2,
  },
  {
    id: 'coup_beerfest20',
    code: 'BEERFEST20',
    description: '20% OFF (up to ₹250) on Chilled Craft Beers & Strong Lagers',
    discountType: 'percentage',
    discountValue: 20,
    minOrderValue: 799,
    maxDiscount: 250,
    validUntil: '2026-11-30',
    isActive: true,
    overallUsageLimit: 200,
    overallUsageCount: 45,
    userUsageLimit: 2,
    applicableCategoryIds: ['cat_beer'],
  },
  {
    id: 'coup_maltluxe',
    code: 'MALTLUXE',
    description: 'Flat ₹350 OFF on Fine Single Malts & Blended Whiskies',
    discountType: 'fixed',
    discountValue: 350,
    minOrderValue: 3000,
    validUntil: '2026-12-15',
    isActive: true,
    overallUsageLimit: 150,
    overallUsageCount: 29,
    userUsageLimit: 1,
    applicableCategoryIds: ['cat_whisky'],
  },
  {
    id: 'coup_munchies10',
    code: 'MUNCHIES10',
    description: '10% OFF (up to ₹100) on Tonics, Mixers & Party Snacks',
    discountType: 'percentage',
    discountValue: 10,
    minOrderValue: 299,
    maxDiscount: 100,
    validUntil: '2026-12-31',
    isActive: true,
    overallUsageLimit: 400,
    overallUsageCount: 112,
    applicableCategoryIds: ['cat_mixers', 'cat_snacks', 'cat_party'],
  },
  {
    id: 'coup_freedel',
    code: 'FREEDEL',
    description: 'Free instant 20-min delivery on carts above ₹899',
    discountType: 'fixed',
    discountValue: 35,
    minOrderValue: 899,
    validUntil: '2026-12-31',
    isActive: true,
    overallUsageLimit: 2000,
    overallUsageCount: 419,
    userUsageLimit: 5,
  }
];
