import { Category, Brand, Product, Store, StoreInventoryItem, User, Coupon, DeliveryZone, PlatformComplianceSettings } from '../types.ts';

export const SEED_CATEGORIES: Category[] = [
  {
    id: 'cat_whisky',
    name: 'Whisky',
    slug: 'whisky',
    description: 'Single malts, blended Scotch, bourbon, and fine grain whiskies',
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Single Malt', 'Blended Scotch', 'Bourbon', 'Irish Whiskey', 'Indian Malt'],
    isActive: true,
  },
  {
    id: 'cat_beer',
    name: 'Beer & Ciders',
    slug: 'beer',
    description: 'Chilled lagers, craft IPAs, stouts, wheat beers, and refreshing ciders',
    imageUrl: 'https://images.unsplash.com/photo-1608270199182-4faeb9ff7584?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Lager', 'Wheat Beer', 'Craft IPA', 'Stout', 'Strong Ale', 'Hard Cider'],
    isActive: true,
  },
  {
    id: 'cat_wine',
    name: 'Wine',
    slug: 'wine',
    description: 'Red wines, crisp whites, sparkling vintages, and delicate rosés',
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Red Wine', 'White Wine', 'Rosé', 'Sparkling Wine', 'Dessert Wine'],
    isActive: true,
  },
  {
    id: 'cat_vodka',
    name: 'Vodka',
    slug: 'vodka',
    description: 'Ultra-pure, grain, potato, and naturally infused premium vodkas',
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Plain Vodka', 'Flavoured Vodka', 'Craft Vodka'],
    isActive: true,
  },
  {
    id: 'cat_gin',
    name: 'Gin',
    slug: 'gin',
    description: 'Botanical London dry, modern craft gins, and contemporary citrus distillates',
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=500&auto=format&fit=crop&q=80',
    subcategories: ['London Dry', 'Botanical Craft', 'Pink Gin', 'Flavoured Gin'],
    isActive: true,
  },
  {
    id: 'cat_rum',
    name: 'Rum',
    slug: 'rum',
    description: 'Aged dark rums, spiced Caribbean blends, and smooth white rums',
    imageUrl: 'https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Dark Rum', 'White Rum', 'Spiced Rum', 'Overproof Rum'],
    isActive: true,
  },
  {
    id: 'cat_tequila',
    name: 'Tequila & Mezcal',
    slug: 'tequila',
    description: '100% Blue Agave Blanco, Reposado, Añejo, and smoky artisanal Mezcals',
    imageUrl: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Blanco / Silver', 'Reposado', 'Añejo', 'Artisanal Mezcal'],
    isActive: true,
  },
  {
    id: 'cat_champagne',
    name: 'Champagne',
    slug: 'champagne',
    description: 'Prestigious French champagnes and celebratory proseccos',
    imageUrl: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Brut Champagne', 'Vintage Champagne', 'Prosecco DOC'],
    isActive: true,
  },
  {
    id: 'cat_brandy',
    name: 'Brandy & Cognac',
    slug: 'brandy',
    description: 'Rich grape brandies, VSOP and XO Cognacs aged in French oak',
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Cognac VSOP', 'Cognac XO', 'Grape Brandy'],
    isActive: true,
  },
  {
    id: 'cat_liqueurs',
    name: 'Liqueurs',
    slug: 'liqueurs',
    description: 'Irish cream, coffee liqueurs, herbal bitters, and fruit digestifs',
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Cream Liqueur', 'Coffee Liqueur', 'Herbal Bitters'],
    isActive: true,
  },
  {
    id: 'cat_mixers',
    name: 'Mixers & Tonics',
    slug: 'mixers',
    description: 'Indian tonic water, ginger ale, club soda, and crafted cocktail premixes',
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Tonic Water', 'Ginger Ale', 'Club Soda', 'Cocktail Mixers'],
    isActive: true,
  },
  {
    id: 'cat_softdrinks',
    name: 'Soft Drinks & Energy',
    slug: 'softdrinks',
    description: 'Energy boosters, premium colas, zero-calorie sodas, and juices',
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Energy Drinks', 'Sparkling Sodas', 'Artisanal Juices'],
    isActive: true,
  },
  {
    id: 'cat_water',
    name: 'Mineral & Sparkling Water',
    slug: 'water',
    description: 'Natural mineral spring waters and effervescent sparkling waters',
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Sparkling Water', 'Natural Spring Mineral Water'],
    isActive: true,
  },
  {
    id: 'cat_snacks',
    name: 'Bar Snacks & Munchies',
    slug: 'snacks',
    description: 'Roasted cashews, artisanal nachos, gourmet chips, and party dips',
    imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Roasted Nuts', 'Gourmet Crisps', 'Artisanal Nachos', 'Party Pretzels'],
    isActive: true,
  },
  {
    id: 'cat_party',
    name: 'Party Essentials',
    slug: 'party-essentials',
    description: 'Ice bags, cocktail shaker sets, glassware, bottle openers, and cups',
    imageUrl: 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Ice Cubes', 'Barware & Openers', 'Disposables', 'Glasses'],
    isActive: true,
  },
  {
    id: 'cat_rtd',
    name: 'Ready To Drink',
    slug: 'ready-to-drink',
    description: 'Canned gin & tonics, hard seltzers, and pre-mixed ready cocktails',
    imageUrl: 'https://images.unsplash.com/photo-1541807084-5c52b6b3adef?w=500&auto=format&fit=crop&q=80',
    subcategories: ['Hard Seltzer', 'Canned Cocktails'],
    isActive: true,
  }
];

export const SEED_BRANDS: Brand[] = [
  { id: 'b_glenfiddich', name: 'Glenfiddich', slug: 'glenfiddich', countryOfOrigin: 'Scotland', logoUrl: '', description: 'World-renowned Speyside single malt scotch distillery since 1887.' },
  { id: 'b_jw', name: 'Johnnie Walker', slug: 'johnnie-walker', countryOfOrigin: 'Scotland', logoUrl: '', description: 'Pioneering Scotch whisky blending since 1820.' },
  { id: 'b_macallan', name: 'The Macallan', slug: 'the-macallan', countryOfOrigin: 'Scotland', logoUrl: '', description: 'Exquisite single malt scotch matured in sherry oak casks.' },
  { id: 'b_jameson', name: 'Jameson', slug: 'jameson', countryOfOrigin: 'Ireland', logoUrl: '', description: 'Triple-distilled, twice as smooth Irish whiskey.' },
  { id: 'b_amrut', name: 'Amrut', slug: 'amrut', countryOfOrigin: 'India', logoUrl: '', description: 'Award-winning Indian single malt whisky crafted in Bengaluru.' },
  { id: 'b_greygoose', name: 'Grey Goose', slug: 'grey-goose', countryOfOrigin: 'France', logoUrl: '', description: 'Ultra-premium French wheat vodka from the Cognac region.' },
  { id: 'b_absolut', name: 'Absolut', slug: 'absolut', countryOfOrigin: 'Sweden', logoUrl: '', description: 'Classic Swedish winter wheat vodka with one continuous distillation.' },
  { id: 'b_hendricks', name: "Hendrick's", slug: 'hendricks', countryOfOrigin: 'Scotland', logoUrl: '', description: 'Small-batch gin infused with Bulgarian rose petal and cucumber.' },
  { id: 'b_bombay', name: 'Bombay Sapphire', slug: 'bombay-sapphire', countryOfOrigin: 'United Kingdom', logoUrl: '', description: 'Vapour-infused gin with 10 hand-selected exotic botanicals.' },
  { id: 'b_bacardi', name: 'Bacardi', slug: 'bacardi', countryOfOrigin: 'Puerto Rico', logoUrl: '', description: 'Superior white and gold rum crafting since 1862.' },
  { id: 'b_oldmonk', name: 'Old Monk', slug: 'old-monk', countryOfOrigin: 'India', logoUrl: '', description: 'Iconic Indian vatted dark rum with rich notes of vanilla and oak.' },
  { id: 'b_corona', name: 'Corona', slug: 'corona', countryOfOrigin: 'Mexico', logoUrl: '', description: 'Crisp Mexican pale lager traditionally served with a lime wedge.' },
  { id: 'b_heineken', name: 'Heineken', slug: 'heineken', countryOfOrigin: 'Netherlands', logoUrl: '', description: 'World-famous 100% pure malt premium European lager.' },
  { id: 'b_bira', name: 'Bira 91', slug: 'bira-91', countryOfOrigin: 'India', logoUrl: '', description: 'Playful, modern craft beer brewing flavorful wheat and blonde ales.' },
  { id: 'b_jacobs', name: "Jacob's Creek", slug: 'jacobs-creek', countryOfOrigin: 'Australia', logoUrl: '', description: 'Australia’s top quality wines crafted in the Barossa Valley.' },
  { id: 'b_sula', name: 'Sula Vineyards', slug: 'sula', countryOfOrigin: 'India', logoUrl: '', description: 'India’s premier winery from the sun-soaked terroir of Nashik.' },
  { id: 'b_moet', name: 'Moët & Chandon', slug: 'moet-chandon', countryOfOrigin: 'France', logoUrl: '', description: 'Legendary champagne house established in Épernay, France.' },
  { id: 'b_donjulio', name: 'Don Julio', slug: 'don-julio', countryOfOrigin: 'Mexico', logoUrl: '', description: 'Handcrafted luxury tequila from the Highlands of Jalisco.' },
  { id: 'b_patron', name: 'Patrón', slug: 'patron', countryOfOrigin: 'Mexico', logoUrl: '', description: 'Artisanal ultra-premium 100% Weber blue agave tequila.' },
  { id: 'b_baileys', name: 'Baileys', slug: 'baileys', countryOfOrigin: 'Ireland', logoUrl: '', description: 'Rich Irish cream blended with aged Irish whiskey and cocoa.' },
  { id: 'b_schweppes', name: 'Schweppes', slug: 'schweppes', countryOfOrigin: 'United Kingdom', logoUrl: '', description: 'The original master of effervescent tonics and sparkling mixers.' },
  { id: 'b_redbull', name: 'Red Bull', slug: 'red-bull', countryOfOrigin: 'Austria', logoUrl: '', description: 'Vitalizes body and mind with premium energy drink formulations.' }
];

export const SEED_PRODUCTS: Product[] = [
  // WHISKY
  {
    id: 'prod_jw_black',
    name: 'Johnnie Walker Black Label 12 Year Old',
    slug: 'johnnie-walker-black-label-12-yo',
    brandId: 'b_jw',
    brandName: 'Johnnie Walker',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Blended Scotch',
    price: 3250,
    mrp: 3600,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'An iconic blended scotch crafted from whiskies aged at least 12 years from the four corners of Scotland.',
    tastingNotes: ['Sweet vanilla', 'Dark fruits', 'Creamy toffee', 'Signature peat smoke'],
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=600&auto=format&fit=crop&q=80',
    country: 'Scotland',
    isBestseller: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 412,
    isActive: true
  },
  {
    id: 'prod_glen_12',
    name: 'Glenfiddich 12 Year Old Single Malt',
    slug: 'glenfiddich-12-year-old',
    brandId: 'b_glenfiddich',
    brandName: 'Glenfiddich',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Single Malt',
    price: 5400,
    mrp: 5900,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Carefully matured in the finest American oak and European oak sherry casks for at least 12 years.',
    tastingNotes: ['Fresh green pear', 'Subtle oak', 'Creamy butterscotch', 'Malt sweetness'],
    imageUrl: 'https://images.unsplash.com/photo-1582819509237-d5b75f20ff7a?w=600&auto=format&fit=crop&q=80',
    country: 'Scotland',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 290,
    isActive: true
  },
  {
    id: 'prod_amrut_fusion',
    name: 'Amrut Fusion Single Malt Indian Whisky',
    slug: 'amrut-fusion-single-malt',
    brandId: 'b_amrut',
    brandName: 'Amrut',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Malt',
    price: 4600,
    mrp: 5000,
    volume: '750 ml',
    alcoholByVolume: 50.0,
    isAlcoholic: true,
    description: 'Crafted using a fusion of Scottish peated barley and unpeated Indian barley, aged in Bengaluru.',
    tastingNotes: ['Heavy peat smoke', 'Spiced orange marmalade', 'Oak tannin', 'Dark chocolate'],
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isNewArrival: true,
    rating: 4.9,
    reviewCount: 154,
    isActive: true
  },
  {
    id: 'prod_jameson_original',
    name: 'Jameson Irish Whiskey',
    slug: 'jameson-irish-whiskey',
    brandId: 'b_jameson',
    brandName: 'Jameson',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Irish Whiskey',
    price: 2400,
    mrp: 2700,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Triple distilled Irish whiskey delivering exceptional balance of spicy, nutty and vanilla notes.',
    tastingNotes: ['Smooth vanilla', 'Toasted wood', 'Honey', 'Mild spice'],
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&auto=format&fit=crop&q=80',
    country: 'Ireland',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 380,
    isActive: true
  },
  {
    id: 'prod_macallan_12',
    name: 'The Macallan Double Cask 12 YO',
    slug: 'the-macallan-double-cask-12',
    brandId: 'b_macallan',
    brandName: 'The Macallan',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Single Malt',
    price: 8900,
    mrp: 9800,
    volume: '700 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'The harmonious union of American and European oak sherry seasoned casks delivering warm spices and honey.',
    tastingNotes: ['Fudge', 'Candied citrus', 'Ginger', 'Warm oak'],
    imageUrl: 'https://images.unsplash.com/photo-1582819509237-d5b75f20ff7a?w=600&auto=format&fit=crop&q=80',
    country: 'Scotland',
    isFeatured: true,
    rating: 5.0,
    reviewCount: 185,
    isActive: true
  },

  // BEER
  {
    id: 'prod_corona_extra_6pk',
    name: 'Corona Extra Premium Beer (Pack of 6)',
    slug: 'corona-extra-pack-of-6',
    brandId: 'b_corona',
    brandName: 'Corona',
    categoryId: 'cat_beer',
    categoryName: 'Beer & Ciders',
    subcategory: 'Lager',
    price: 1350,
    mrp: 1500,
    volume: '6 x 330 ml',
    alcoholByVolume: 4.5,
    isAlcoholic: true,
    description: 'Golden pale lager with a refreshing, crisp taste and a smooth finish. Best enjoyed ice-cold with a wedge of lime.',
    tastingNotes: ['Crisp malt', 'Subtle sweetness', 'Clean finish'],
    imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSONTwPDD_MHZXHehN53eEOZhHWywAwpsTDKd69_QYa1w&s=10',
    country: 'Mexico',
    isBestseller: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 520,
    isActive: true
  },
  {
    id: 'prod_heineken_pint',
    name: 'Heineken Original Lager (Pack of 4)',
    slug: 'heineken-original-lager-pack-of-4',
    brandId: 'b_heineken',
    brandName: 'Heineken',
    categoryId: 'cat_beer',
    categoryName: 'Beer & Ciders',
    subcategory: 'Lager',
    price: 760,
    mrp: 840,
    volume: '4 x 330 ml',
    alcoholByVolume: 5.0,
    isAlcoholic: true,
    description: 'Premium malt lager brewed with 100% natural ingredients and Heineken signature A-yeast.',
    tastingNotes: ['Fruity yeast notes', 'Mild hop bitterness', 'Clean barley finish'],
    imageUrl: 'https://images.unsplash.com/photo-1618886614638-80e3c15cd819?w=600&auto=format&fit=crop&q=80',
    country: 'Netherlands',
    isBestseller: true,
    rating: 4.6,
    reviewCount: 310,
    isActive: true
  },
  {
    id: 'prod_bira_white',
    name: 'Bira 91 White Ale (Pack of 6 Cans)',
    slug: 'bira-91-white-ale-pack-of-6',
    brandId: 'b_bira',
    brandName: 'Bira 91',
    categoryId: 'cat_beer',
    categoryName: 'Beer & Ciders',
    subcategory: 'Wheat Beer',
    price: 990,
    mrp: 1100,
    volume: '6 x 500 ml',
    alcoholByVolume: 4.7,
    isAlcoholic: true,
    description: 'Delightfully hazy wheat beer infused with orange peel and fresh coriander seeds for an aromatic refresh.',
    tastingNotes: ['Zesty citrus', 'Spiced coriander', 'Velvety wheat body'],
    imageUrl: 'https://images.unsplash.com/photo-1535958636474-b021ee887b13?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 440,
    isActive: true
  },

  // WINE
  {
    id: 'prod_sula_shiraz',
    name: 'Sula Vineyards Dindori Reserve Shiraz',
    slug: 'sula-dindori-reserve-shiraz',
    brandId: 'b_sula',
    brandName: 'Sula Vineyards',
    categoryId: 'cat_wine',
    categoryName: 'Wine',
    subcategory: 'Red Wine',
    price: 1450,
    mrp: 1650,
    volume: '750 ml',
    alcoholByVolume: 13.5,
    isAlcoholic: true,
    description: 'Estate-bottled lush red wine aged in American oak barrels, offering rich berries and peppery spices.',
    tastingNotes: ['Black cherries', 'Vanilla oak', 'Cracked black pepper'],
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isFeatured: true,
    rating: 4.7,
    reviewCount: 215,
    isActive: true
  },
  {
    id: 'prod_jacobs_cab_sauv',
    name: "Jacob's Creek Classic Cabernet Sauvignon",
    slug: 'jacobs-creek-cabernet-sauvignon',
    brandId: 'b_jacobs',
    brandName: "Jacob's Creek",
    categoryId: 'cat_wine',
    categoryName: 'Wine',
    subcategory: 'Red Wine',
    price: 1350,
    mrp: 1550,
    volume: '750 ml',
    alcoholByVolume: 13.9,
    isAlcoholic: true,
    description: 'Medium-bodied Australian red showcasing dark cassis fruit, gentle mint and toasted cedar notes.',
    tastingNotes: ['Cassis', 'Blackberry jam', 'Subtle mint', 'Soft tannins'],
    imageUrl: 'https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?w=600&auto=format&fit=crop&q=80',
    country: 'Australia',
    isBestseller: true,
    rating: 4.6,
    reviewCount: 198,
    isActive: true
  },

  // GIN
  {
    id: 'prod_hendricks_gin',
    name: "Hendrick's Handcrafted Scottish Gin",
    slug: 'hendricks-handcrafted-gin',
    brandId: 'b_hendricks',
    brandName: "Hendrick's",
    categoryId: 'cat_gin',
    categoryName: 'Gin',
    subcategory: 'Botanical Craft',
    price: 4200,
    mrp: 4600,
    volume: '700 ml',
    alcoholByVolume: 41.4,
    isAlcoholic: true,
    description: 'Curiously infused with essence of rose and cucumber alongside 11 fine botanicals.',
    tastingNotes: ['Floral rose', 'Crisp cucumber', 'Juniper berry', 'Zesty citrus'],
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    country: 'Scotland',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 340,
    isActive: true
  },
  {
    id: 'prod_bombay_sapphire',
    name: 'Bombay Sapphire Distilled London Dry Gin',
    slug: 'bombay-sapphire-london-dry-gin',
    brandId: 'b_bombay',
    brandName: 'Bombay Sapphire',
    categoryId: 'cat_gin',
    categoryName: 'Gin',
    subcategory: 'London Dry',
    price: 2600,
    mrp: 2900,
    volume: '750 ml',
    alcoholByVolume: 47.0,
    isAlcoholic: true,
    description: 'Vapour-infused with almond, lemon peel, liquorice, juniper, orris root, angelica and coriander.',
    tastingNotes: ['Bright citrus', 'Piney juniper', 'Warm spice', 'Clean herbal finish'],
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=600&auto=format&fit=crop&q=80',
    country: 'United Kingdom',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 410,
    isActive: true
  },

  // VODKA
  {
    id: 'prod_greygoose_vodka',
    name: 'Grey Goose Premium French Vodka',
    slug: 'grey-goose-vodka-750ml',
    brandId: 'b_greygoose',
    brandName: 'Grey Goose',
    categoryId: 'cat_vodka',
    categoryName: 'Vodka',
    subcategory: 'Plain Vodka',
    price: 4100,
    mrp: 4500,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Distilled once using continuous column process from soft winter wheat grown in Picardy, France.',
    tastingNotes: ['Delicate floral', 'Sweet brioche', 'Almond cream finish'],
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&auto=format&fit=crop&q=80',
    country: 'France',
    isFeatured: true,
    rating: 4.8,
    reviewCount: 360,
    isActive: true
  },
  {
    id: 'prod_absolut_blue',
    name: 'Absolut Blue Original Vodka',
    slug: 'absolut-blue-original-vodka',
    brandId: 'b_absolut',
    brandName: 'Absolut',
    categoryId: 'cat_vodka',
    categoryName: 'Vodka',
    subcategory: 'Plain Vodka',
    price: 2150,
    mrp: 2400,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Iconic Swedish vodka produced in Åhus with rich winter wheat, completely free of added sugar.',
    tastingNotes: ['Grain warmth', 'Subtle dried fruit', 'Crisp neutral finish'],
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=600&auto=format&fit=crop&q=80',
    country: 'Sweden',
    isBestseller: true,
    rating: 4.6,
    reviewCount: 295,
    isActive: true
  },

  // RUM
  {
    id: 'prod_oldmonk_7yr',
    name: 'Old Monk XXX Vatted Dark Rum',
    slug: 'old-monk-xxx-dark-rum',
    brandId: 'b_oldmonk',
    brandName: 'Old Monk',
    categoryId: 'cat_rum',
    categoryName: 'Rum',
    subcategory: 'Dark Rum',
    price: 850,
    mrp: 950,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'The legendary Indian dark rum blended and aged in oak vats for a distinct molasses and caramel profile.',
    tastingNotes: ['Sweet molasses', 'Roasted coffee bean', 'Vanilla spice', 'Heavy oak'],
    imageUrl: 'https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 880,
    isActive: true
  },
  {
    id: 'prod_bacardi_carta_blanca',
    name: 'Bacardi Carta Blanca Superior White Rum',
    slug: 'bacardi-carta-blanca-white-rum',
    brandId: 'b_bacardi',
    brandName: 'Bacardi',
    categoryId: 'cat_rum',
    categoryName: 'Rum',
    subcategory: 'White Rum',
    price: 1350,
    mrp: 1500,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Aged in white oak barrels and charcoal filtered for the ideal Mojito and Daiquiri cocktail base.',
    tastingNotes: ['Fresh citrus', 'Coconut', 'Vanilla blossom', 'Crisp clean finish'],
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&auto=format&fit=crop&q=80',
    country: 'Puerto Rico',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 310,
    isActive: true
  },

  // TEQUILA
  {
    id: 'prod_donjulio_blanco',
    name: 'Don Julio Blanco 100% Blue Agave',
    slug: 'don-julio-blanco-tequila',
    brandId: 'b_donjulio',
    brandName: 'Don Julio',
    categoryId: 'cat_tequila',
    categoryName: 'Tequila & Mezcal',
    subcategory: 'Blanco / Silver',
    price: 6200,
    mrp: 6800,
    volume: '750 ml',
    alcoholByVolume: 38.0,
    isAlcoholic: true,
    description: 'Crisp agave flavor with hints of citrus, bottled immediately after distillation for maximum purity.',
    tastingNotes: ['Crisp agave', 'Fresh lemon zest', 'Peppery warmth'],
    imageUrl: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=600&auto=format&fit=crop&q=80',
    country: 'Mexico',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 160,
    isActive: true
  },
  {
    id: 'prod_patron_reposado',
    name: 'Patrón Reposado Handcrafted Tequila',
    slug: 'patron-reposado-tequila',
    brandId: 'b_patron',
    brandName: 'Patrón',
    categoryId: 'cat_tequila',
    categoryName: 'Tequila & Mezcal',
    subcategory: 'Reposado',
    price: 7400,
    mrp: 8100,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Aged in oak barrels for over two months to combine the fresh taste of silver with the oakiness of añejo.',
    tastingNotes: ['Fresh agave', 'Warm honey', 'Light floral oak'],
    imageUrl: 'https://images.unsplash.com/photo-1516627145497-ae6968895b74?w=600&auto=format&fit=crop&q=80',
    country: 'Mexico',
    isNewArrival: true,
    rating: 4.8,
    reviewCount: 120,
    isActive: true
  },

  // CHAMPAGNE
  {
    id: 'prod_moet_imperial',
    name: 'Moët & Chandon Impérial Brut Champagne',
    slug: 'moet-chandon-imperial-brut',
    brandId: 'b_moet',
    brandName: 'Moët & Chandon',
    categoryId: 'cat_champagne',
    categoryName: 'Champagne',
    subcategory: 'Brut Champagne',
    price: 7900,
    mrp: 8600,
    volume: '750 ml',
    alcoholByVolume: 12.0,
    isAlcoholic: true,
    description: 'The iconic champagne created in 1869, sparkling with vibrant apple, citrus, brioche and mineral nuance.',
    tastingNotes: ['Green apple', 'White peach', 'Brioche', 'Fine persistent bubbles'],
    imageUrl: 'https://images.unsplash.com/photo-1563227812-0ea4c22e6cc8?w=600&auto=format&fit=crop&q=80',
    country: 'France',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 280,
    isActive: true
  },

  // LIQUEURS
  {
    id: 'prod_baileys_irish_cream',
    name: 'Baileys The Original Irish Cream Liqueur',
    slug: 'baileys-original-irish-cream',
    brandId: 'b_baileys',
    brandName: 'Baileys',
    categoryId: 'cat_liqueurs',
    categoryName: 'Liqueurs',
    subcategory: 'Cream Liqueur',
    price: 2450,
    mrp: 2750,
    volume: '750 ml',
    alcoholByVolume: 17.0,
    isAlcoholic: true,
    description: 'Luscious fusion of fresh Irish dairy cream and aged Irish whiskey with hints of rich chocolate and vanilla.',
    tastingNotes: ['Sweet cream', 'Rich milk chocolate', 'Warm vanilla caramel'],
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&auto=format&fit=crop&q=80',
    country: 'Ireland',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 390,
    isActive: true
  },

  // MIXERS & TONICS (Non-alcoholic)
  {
    id: 'prod_schweppes_tonic_4pk',
    name: 'Schweppes Indian Tonic Water (Pack of 4)',
    slug: 'schweppes-tonic-water-pack-of-4',
    brandId: 'b_schweppes',
    brandName: 'Schweppes',
    categoryId: 'cat_mixers',
    categoryName: 'Mixers & Tonics',
    subcategory: 'Tonic Water',
    price: 240,
    mrp: 280,
    volume: '4 x 250 ml',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'The golden standard tonic with quinine and delicate citrus, perfect for crafting classic Gin & Tonics.',
    tastingNotes: ['Bitter quinine', 'Citrus essence', 'Crisp effervescence'],
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    country: 'United Kingdom',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 460,
    isActive: true
  },
  {
    id: 'prod_schweppes_ginger_ale',
    name: 'Schweppes Sparkling Ginger Ale (Pack of 4)',
    slug: 'schweppes-ginger-ale-pack-of-4',
    brandId: 'b_schweppes',
    brandName: 'Schweppes',
    categoryId: 'cat_mixers',
    categoryName: 'Mixers & Tonics',
    subcategory: 'Ginger Ale',
    price: 240,
    mrp: 280,
    volume: '4 x 250 ml',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Crisp spicy ginger soda, marvelous for highballs, dark rums, or sipping over cracked ice.',
    tastingNotes: ['Spicy ginger root', 'Caramel sweetness', 'Effervescent fizz'],
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    country: 'United Kingdom',
    rating: 4.6,
    reviewCount: 210,
    isActive: true
  },

  // SOFT DRINKS & ENERGY
  {
    id: 'prod_redbull_4pk',
    name: 'Red Bull Energy Drink (Pack of 4)',
    slug: 'red-bull-energy-drink-pack-of-4',
    brandId: 'b_redbull',
    brandName: 'Red Bull',
    categoryId: 'cat_softdrinks',
    categoryName: 'Soft Drinks & Energy',
    subcategory: 'Energy Drinks',
    price: 480,
    mrp: 520,
    volume: '4 x 250 ml',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Vitalizes body and mind with taurine, B-group vitamins, and pure Alpine water. Classic party mixer.',
    tastingNotes: ['Sweet and tangy', 'Sharp energetic notes'],
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80',
    country: 'Austria',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 650,
    isActive: true
  },

  // SNACKS & MUNCHIES
  {
    id: 'prod_gourmet_cashews',
    name: 'DrinkIt Select Roasted & Salted Jumbo Cashews',
    slug: 'roasted-salted-cashews-200g',
    brandId: 'b_amrut',
    brandName: 'DrinkIt Pantry',
    categoryId: 'cat_snacks',
    categoryName: 'Bar Snacks & Munchies',
    subcategory: 'Roasted Nuts',
    price: 380,
    mrp: 450,
    volume: '200 g',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Hand-picked premium Grade W-180 jumbo cashew nuts gently dry-roasted and dusted with Himalayan pink salt.',
    tastingNotes: ['Crunchy buttery richness', 'Subtle pink salt'],
    imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 380,
    isActive: true
  },
  {
    id: 'prod_cheese_nachos',
    name: 'Artisanal Corn Nachos with Cheese Dip',
    slug: 'artisanal-nachos-cheese-dip',
    brandId: 'b_corona',
    brandName: 'DrinkIt Pantry',
    categoryId: 'cat_snacks',
    categoryName: 'Bar Snacks & Munchies',
    subcategory: 'Artisanal Nachos',
    price: 190,
    mrp: 230,
    volume: '150 g + 50 g dip',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Stone-ground yellow corn tortilla crisps served with a creamy jalapeño cheddar cheese dip.',
    tastingNotes: ['Crispy roasted corn', 'Tangy jalapeño cheddar'],
    imageUrl: 'https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    rating: 4.7,
    reviewCount: 220,
    isActive: true
  },

  // PARTY ESSENTIALS
  {
    id: 'prod_crystal_ice_pack',
    name: 'Crystal Clear Food-Grade Ice Cubes (1 kg Pack)',
    slug: 'crystal-ice-cubes-1kg',
    brandId: 'b_schweppes',
    brandName: 'DrinkIt Essentials',
    categoryId: 'cat_party',
    categoryName: 'Party Essentials',
    subcategory: 'Ice Cubes',
    price: 90,
    mrp: 120,
    volume: '1000 g',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'RO purified, slow-frozen triple-filtered crystal ice cubes. Melts slowly to preserve your drink balance.',
    tastingNotes: ['Zero odor', 'Ultra clear', 'Slow melting'],
    imageUrl: 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 940,
    isActive: true
  },
  {
    id: 'prod_cocktail_shaker_set',
    name: 'Stainless Steel Cocktail Shaker & Bar Jigger',
    slug: 'cocktail-shaker-and-jigger-set',
    brandId: 'b_hendricks',
    brandName: 'DrinkIt Essentials',
    categoryId: 'cat_party',
    categoryName: 'Party Essentials',
    subcategory: 'Barware & Openers',
    price: 799,
    mrp: 1199,
    volume: '750 ml + 30/60ml',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Professional grade 304 stainless steel cocktail shaker with built-in strainer and dual peg measure.',
    tastingNotes: ['Mirror polished', 'Dishwasher safe', 'Leak proof'],
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    rating: 4.8,
    reviewCount: 160,
    isActive: true
  }
];

export const SEED_STORES: Store[] = [
  {
    id: 'store_indiranagar',
    name: 'DrinkIt Hub — Indiranagar Central',
    code: 'BLR-IND-01',
    address: '100 Feet Road, HAL 2nd Stage, Indiranagar',
    area: 'Indiranagar',
    city: 'Bengaluru',
    state: 'Karnataka',
    postalCodes: ['560038', '560008', '560075', '560001'],
    latitude: 12.9784,
    longitude: 77.6408,
    serviceRadiusKm: 6.5,
    operatingHours: { open: '09:00', close: '23:30' },
    isActive: true,
    deliveryEnabled: true,
  },
  {
    id: 'store_koramangala',
    name: 'DrinkIt Hub — Koramangala South',
    code: 'BLR-KOR-02',
    address: '80 Feet Road, 4th Block, Koramangala',
    area: 'Koramangala',
    city: 'Bengaluru',
    state: 'Karnataka',
    postalCodes: ['560034', '560095', '560047', '560029'],
    latitude: 12.9352,
    longitude: 77.6245,
    serviceRadiusKm: 6.0,
    operatingHours: { open: '09:30', close: '23:30' },
    isActive: true,
    deliveryEnabled: true,
  },
  {
    id: 'store_hsr',
    name: 'DrinkIt Hub — HSR Layout & BTM',
    code: 'BLR-HSR-03',
    address: '27th Main Road, Sector 1, HSR Layout',
    area: 'HSR Layout',
    city: 'Bengaluru',
    state: 'Karnataka',
    postalCodes: ['560102', '560068', '560076', '560030'],
    latitude: 12.9121,
    longitude: 77.6446,
    serviceRadiusKm: 5.5,
    operatingHours: { open: '10:00', close: '23:00' },
    isActive: true,
    deliveryEnabled: true,
  },
  {
    id: 'store_whitefield',
    name: 'DrinkIt Hub — Whitefield Tech Corridor',
    code: 'BLR-WHI-04',
    address: 'ITPL Main Road, Prestige Shantiniketan, Whitefield',
    area: 'Whitefield',
    city: 'Bengaluru',
    state: 'Karnataka',
    postalCodes: ['560066', '560067', '560048', '560037'],
    latitude: 12.9868,
    longitude: 77.7346,
    serviceRadiusKm: 7.0,
    operatingHours: { open: '10:00', close: '23:00' },
    isActive: true,
    deliveryEnabled: true,
  },
  {
    id: 'store_phagwara',
    name: 'DrinkIt Hub — Phagwara & LPU Express',
    code: 'PB-PHG-01',
    address: 'GT Road, Near LPU Main Gate, Phagwara',
    area: 'LPU & Phagwara',
    city: 'Phagwara',
    state: 'Punjab',
    postalCodes: ['144411', '144401', '144402'],
    latitude: 31.2554,
    longitude: 75.7037,
    serviceRadiusKm: 8.0,
    operatingHours: { open: '10:00', close: '23:00' },
    isActive: true,
    deliveryEnabled: true,
  }
];

export const SEED_DELIVERY_ZONES: DeliveryZone[] = [
  {
    id: 'zone_indiranagar',
    name: 'Indiranagar & CBD Core Zone',
    city: 'Bengaluru',
    state: 'Karnataka',
    postalCodes: ['560038', '560008', '560075', '560001'],
    associatedStoreId: 'store_indiranagar',
    isActive: true,
    minOrderValue: 299,
    baseDeliveryFee: 35
  },
  {
    id: 'zone_koramangala',
    name: 'Koramangala & Domlur Express Zone',
    city: 'Bengaluru',
    state: 'Karnataka',
    postalCodes: ['560034', '560095', '560047', '560029'],
    associatedStoreId: 'store_koramangala',
    isActive: true,
    minOrderValue: 299,
    baseDeliveryFee: 35
  },
  {
    id: 'zone_hsr',
    name: 'HSR Layout & Bellandur Zone',
    city: 'Bengaluru',
    state: 'Karnataka',
    postalCodes: ['560102', '560068', '560076', '560030'],
    associatedStoreId: 'store_hsr',
    isActive: true,
    minOrderValue: 299,
    baseDeliveryFee: 40
  },
  {
    id: 'zone_whitefield',
    name: 'Whitefield & ITPL Zone',
    city: 'Bengaluru',
    state: 'Karnataka',
    postalCodes: ['560066', '560067', '560048', '560037'],
    associatedStoreId: 'store_whitefield',
    isActive: true,
    minOrderValue: 399,
    baseDeliveryFee: 45
  },
  {
    id: 'zone_phagwara',
    name: 'LPU & Phagwara Express Delivery Zone',
    city: 'Phagwara',
    state: 'Punjab',
    postalCodes: ['144411', '144401', '144402'],
    associatedStoreId: 'store_phagwara',
    isActive: true,
    minOrderValue: 299,
    baseDeliveryFee: 30
  }
];

export const SEED_COUPONS: Coupon[] = [
  {
    id: 'coup_welcome50',
    code: 'WELCOME50',
    description: 'Flat ₹50 OFF on your first DrinkIt order (Min. ₹499)',
    discountType: 'fixed',
    discountValue: 50,
    minOrderValue: 499,
    validUntil: '2026-12-31',
    isActive: true,
    overallUsageLimit: 1000,
    overallUsageCount: 238,
    userUsageLimit: 1, // 1 per user account (first order)
  },
  {
    id: 'coup_cheers100',
    code: 'CHEERS100',
    description: 'Flat ₹100 OFF on orders above ₹1499',
    discountType: 'fixed',
    discountValue: 100,
    minOrderValue: 1499,
    validUntil: '2026-12-31',
    isActive: true,
    overallUsageLimit: 500,
    overallUsageCount: 164,
    userUsageLimit: 3,
  },
  {
    id: 'coup_party15',
    code: 'PARTY15',
    description: '15% OFF up to ₹350 for celebrations above ₹2499',
    discountType: 'percentage',
    discountValue: 15,
    minOrderValue: 2499,
    maxDiscount: 350,
    validUntil: '2026-12-31',
    isActive: true,
    overallUsageLimit: 300,
    overallUsageCount: 82,
    userUsageLimit: 2,
  },
  {
    id: 'coup_beerfest20',
    code: 'BEERFEST20',
    description: '20% OFF (up to ₹250) on Chilled Craft Beers & Ciders',
    discountType: 'percentage',
    discountValue: 20,
    minOrderValue: 799,
    maxDiscount: 250,
    validUntil: '2026-11-30',
    isActive: true,
    overallUsageLimit: 200,
    overallUsageCount: 45,
    userUsageLimit: 2,
    applicableCategoryIds: ['cat_beer'], // Category restriction
  },
  {
    id: 'coup_maltluxe',
    code: 'MALTLUXE',
    description: 'Flat ₹350 OFF on Fine Single Malts & Blended Whiskies',
    discountType: 'fixed',
    discountValue: 350,
    minOrderValue: 3000,
    validUntil: '2026-12-15',
    isActive: true,
    overallUsageLimit: 150,
    overallUsageCount: 29,
    userUsageLimit: 1,
    applicableCategoryIds: ['cat_whisky'], // Category restriction
  },
  {
    id: 'coup_munchies10',
    code: 'MUNCHIES10',
    description: '10% OFF (up to ₹100) on Tonics, Mixers & Party Snacks',
    discountType: 'percentage',
    discountValue: 10,
    minOrderValue: 299,
    maxDiscount: 100,
    validUntil: '2026-12-31',
    isActive: true,
    overallUsageLimit: 400,
    overallUsageCount: 112,
    applicableCategoryIds: ['cat_mixers', 'cat_snacks'], // Multi-category restriction
  },
  {
    id: 'coup_freedel',
    code: 'FREEDEL',
    description: 'Free instant 20-min delivery on carts above ₹899',
    discountType: 'fixed',
    discountValue: 35,
    minOrderValue: 899,
    validUntil: '2026-12-31',
    isActive: true,
    overallUsageLimit: 2000,
    overallUsageCount: 419,
    userUsageLimit: 5,
  }
];

export const SEED_COMPLIANCE_SETTINGS: PlatformComplianceSettings = {
  legalDrinkingAge: 21,
  jurisdiction: 'Karnataka, India (State Excise Act Compliant)',
  dryDayActive: false,
  dryDayReason: '',
  maxBottlesPerOrder: 6,
  operatingHoursOnly: true,
  requireIdProofAtDoorstep: true
};

export const SEED_USERS: User[] = [
  {
    id: 'usr_admin',
    name: 'Aarav Sharma (Admin)',
    email: 'admin@drinkit.demo',
    passwordHash: 'admin123',
    role: 'admin',
    phone: '+91 98765 43210',
    dateOfBirth: '1990-05-15',
    age: 36,
    isAgeVerified: true,
    ageVerifiedAt: '2026-01-01T00:00:00Z',
    jurisdiction: 'Karnataka',
    addresses: [],
    createdAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'usr_store',
    name: 'Rohan Verma (Store Lead)',
    email: 'store@drinkit.demo',
    passwordHash: 'store123',
    role: 'staff',
    phone: '+91 98765 43211',
    dateOfBirth: '1994-08-20',
    age: 32,
    isAgeVerified: true,
    ageVerifiedAt: '2026-01-01T00:00:00Z',
    jurisdiction: 'Karnataka',
    addresses: [],
    createdAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'usr_delivery',
    name: 'Vikram Singh (Rider)',
    email: 'delivery@drinkit.demo',
    passwordHash: 'delivery123',
    role: 'delivery',
    phone: '+91 98765 43212',
    dateOfBirth: '1998-11-10',
    age: 27,
    isAgeVerified: true,
    ageVerifiedAt: '2026-01-01T00:00:00Z',
    jurisdiction: 'Karnataka',
    addresses: [],
    createdAt: '2026-01-01T00:00:00Z'
  },
  {
    id: 'usr_customer',
    name: 'Pooja Nair (Customer)',
    email: 'customer@drinkit.demo',
    passwordHash: 'customer123',
    role: 'customer',
    phone: '+91 98765 43213',
    dateOfBirth: '1997-03-24',
    age: 29,
    isAgeVerified: true,
    ageVerifiedAt: '2026-02-14T10:00:00Z',
    jurisdiction: 'Karnataka',
    addresses: [
      {
        id: 'addr_1',
        label: 'home',
        fullName: 'Pooja Nair',
        phone: '+91 98765 43213',
        addressLine1: 'Flat 402, Green Glen Heights, 12th Main',
        addressLine2: 'HAL 2nd Stage, Indiranagar',
        landmark: 'Near Corner House Ice Cream',
        city: 'Bengaluru',
        state: 'Karnataka',
        postalCode: '560038',
        latitude: 12.9785,
        longitude: 77.6409,
        isDefault: true
      },
      {
        id: 'addr_2',
        label: 'work',
        fullName: 'Pooja Nair',
        phone: '+91 98765 43213',
        addressLine1: 'Level 5, WeWork Prestige Tech Park',
        addressLine2: 'Outer Ring Road, Kadubeesanahalli',
        city: 'Bengaluru',
        state: 'Karnataka',
        postalCode: '560103',
        latitude: 12.9372,
        longitude: 77.6946,
        isDefault: false
      }
    ],
    createdAt: '2026-02-01T00:00:00Z'
  },
  {
    id: 'usr_rahul',
    name: 'Rahul Mehta',
    email: 'rahul.mehta@example.com',
    passwordHash: 'pass123',
    role: 'customer',
    phone: '+91 98112 34567',
    dateOfBirth: '1993-07-12',
    age: 33,
    isAgeVerified: true,
    ageVerifiedAt: '2026-01-15T00:00:00Z',
    jurisdiction: 'Karnataka',
    addresses: [],
    createdAt: '2026-01-10T00:00:00Z'
  },
  {
    id: 'usr_sneha',
    name: 'Sneha Reddy',
    email: 'sneha.reddy@example.com',
    passwordHash: 'pass123',
    role: 'customer',
    phone: '+91 98223 45678',
    dateOfBirth: '1996-10-05',
    age: 29,
    isAgeVerified: true,
    ageVerifiedAt: '2026-02-01T00:00:00Z',
    jurisdiction: 'Karnataka',
    addresses: [],
    createdAt: '2026-01-28T00:00:00Z'
  },
  {
    id: 'usr_ananya',
    name: 'Ananya Rao',
    email: 'ananya.rao@example.com',
    passwordHash: 'pass123',
    role: 'customer',
    phone: '+91 98334 56789',
    dateOfBirth: '1995-04-18',
    age: 31,
    isAgeVerified: true,
    ageVerifiedAt: '2026-02-10T00:00:00Z',
    jurisdiction: 'Karnataka',
    addresses: [],
    createdAt: '2026-02-05T00:00:00Z'
  },
  {
    id: 'usr_dev',
    name: 'Devansh Kulkarni',
    email: 'dev.kulkarni@example.com',
    passwordHash: 'pass123',
    role: 'customer',
    phone: '+91 98445 67890',
    dateOfBirth: '1992-12-30',
    age: 33,
    isAgeVerified: true,
    ageVerifiedAt: '2026-02-20T00:00:00Z',
    jurisdiction: 'Karnataka',
    addresses: [],
    createdAt: '2026-02-18T00:00:00Z'
  }
];
