import { Store, DeliveryZone, PlatformComplianceSettings } from '../types.ts';

export const SEED_STORES: Store[] = [
  // 1. NOIDA / DELHI NCR (PRIMARY DEFAULT STORE)
  {
    id: 'store_noida_sec18',
    name: 'DrinkIt Hub — Noida Sector 18 & NCR Core',
    code: 'UP-NOI-01',
    address: 'Atta Market, Pocket E, Sector 18, Noida',
    area: 'Sector 18 & Central Noida',
    city: 'Noida',
    state: 'Uttar Pradesh',
    postalCodes: ['201301', '201303', '201304', '201307'],
    latitude: 28.5708,
    longitude: 77.3271,
    serviceRadiusKm: 6.5,
    operatingHours: { open: '10:00', close: '23:00' },
    isActive: true,
    deliveryEnabled: true,
  },
  // 2. SOUTH DELHI
  {
    id: 'store_south_delhi',
    name: 'DrinkIt Hub — South Delhi & Saket',
    code: 'DL-STH-01',
    address: 'Community Centre, Saket District Centre, New Delhi',
    area: 'Saket & Greater Kailash',
    city: 'New Delhi',
    state: 'Delhi',
    postalCodes: ['110017', '110048', '110019', '110016', '110024'],
    latitude: 28.5244,
    longitude: 77.2167,
    serviceRadiusKm: 6.0,
    operatingHours: { open: '10:00', close: '22:00' },
    isActive: true,
    deliveryEnabled: true,
  },
  // 3. CENTRAL DELHI / CONNAUGHT PLACE
  {
    id: 'store_central_delhi',
    name: 'DrinkIt Hub — Central Delhi & Connaught Place',
    code: 'DL-CEN-02',
    address: 'Outer Circle, Connaught Place, New Delhi',
    area: 'Connaught Place & Barakhamba',
    city: 'New Delhi',
    state: 'Delhi',
    postalCodes: ['110001', '110002', '110003', '110005'],
    latitude: 28.6315,
    longitude: 77.2167,
    serviceRadiusKm: 5.5,
    operatingHours: { open: '10:00', close: '22:00' },
    isActive: true,
    deliveryEnabled: true,
  },
  // 4. GHAZIABAD / INDIRAPURAM
  {
    id: 'store_indirapuram',
    name: 'DrinkIt Hub — Indirapuram & Vaishali',
    code: 'UP-GZB-01',
    address: 'Kala Patthar Road, Nyay Khand 2, Indirapuram, Ghaziabad',
    area: 'Indirapuram & Vaishali',
    city: 'Ghaziabad',
    state: 'Uttar Pradesh',
    postalCodes: ['201014', '201010', '201012', '201016'],
    latitude: 28.6434,
    longitude: 77.3704,
    serviceRadiusKm: 6.0,
    operatingHours: { open: '10:00', close: '23:00' },
    isActive: true,
    deliveryEnabled: true,
  },
  // 5. LUCKNOW / GOMTI NAGAR
  {
    id: 'store_lucknow_gomtinagar',
    name: 'DrinkIt Hub — Lucknow Gomti Nagar Central',
    code: 'UP-LKO-01',
    address: 'Vipin Khand, Near Riverside Mall, Gomti Nagar, Lucknow',
    area: 'Gomti Nagar & Hazratganj',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    postalCodes: ['226010', '226001', '226016', '226024'],
    latitude: 26.8500,
    longitude: 80.9995,
    serviceRadiusKm: 7.0,
    operatingHours: { open: '10:00', close: '23:00' },
    isActive: true,
    deliveryEnabled: true,
  },
  // 6. GREATER NOIDA
  {
    id: 'store_greater_noida',
    name: 'DrinkIt Hub — Greater Noida Knowledge Park',
    code: 'UP-GNOI-02',
    address: 'Commercial Belt, Alpha 1, Greater Noida',
    area: 'Pari Chowk & Alpha 1',
    city: 'Greater Noida',
    state: 'Uttar Pradesh',
    postalCodes: ['201308', '201306', '201310'],
    latitude: 28.4744,
    longitude: 77.5040,
    serviceRadiusKm: 7.5,
    operatingHours: { open: '10:00', close: '23:00' },
    isActive: true,
    deliveryEnabled: true,
  },
  // 7. KANPUR
  {
    id: 'store_kanpur_civillines',
    name: 'DrinkIt Hub — Kanpur Civil Lines',
    code: 'UP-KNP-01',
    address: 'The Mall Road, Civil Lines, Kanpur',
    area: 'Civil Lines & Swaroop Nagar',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    postalCodes: ['208001', '208002', '208005'],
    latitude: 26.4716,
    longitude: 80.3458,
    serviceRadiusKm: 6.0,
    operatingHours: { open: '10:00', close: '23:00' },
    isActive: true,
    deliveryEnabled: true,
  },
  // 8. AGRA
  {
    id: 'store_agra_tajganj',
    name: 'DrinkIt Hub — Agra Tajganj & Sanjay Place',
    code: 'UP-AGR-01',
    address: 'Fatehabad Road, Tajganj, Agra',
    area: 'Tajganj & Sanjay Place',
    city: 'Agra',
    state: 'Uttar Pradesh',
    postalCodes: ['282001', '282002', '282004'],
    latitude: 27.1610,
    longitude: 78.0421,
    serviceRadiusKm: 6.0,
    operatingHours: { open: '10:00', close: '23:00' },
    isActive: true,
    deliveryEnabled: true,
  },
  // 9. VARANASI
  {
    id: 'store_varanasi_sigra',
    name: 'DrinkIt Hub — Varanasi Sigra & Cantt',
    code: 'UP-VNS-01',
    address: 'Vidyapeeth Road, Sigra, Varanasi',
    area: 'Sigra & Cantt',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    postalCodes: ['221002', '221005', '221010'],
    latitude: 25.3176,
    longitude: 82.9739,
    serviceRadiusKm: 6.0,
    operatingHours: { open: '10:00', close: '23:00' },
    isActive: true,
    deliveryEnabled: true,
  },
];

export const SEED_DELIVERY_ZONES: DeliveryZone[] = [
  {
    id: 'zone_noida_sec18',
    name: 'Noida Sector 18 & Central NCR Zone',
    city: 'Noida',
    state: 'Uttar Pradesh',
    postalCodes: ['201301', '201303', '201304', '201307'],
    associatedStoreId: 'store_noida_sec18',
    isActive: true,
    minOrderValue: 299,
    baseDeliveryFee: 35,
  },
  {
    id: 'zone_south_delhi',
    name: 'South Delhi & Greater Kailash Zone',
    city: 'New Delhi',
    state: 'Delhi',
    postalCodes: ['110017', '110048', '110019', '110016', '110024'],
    associatedStoreId: 'store_south_delhi',
    isActive: true,
    minOrderValue: 299,
    baseDeliveryFee: 40,
  },
  {
    id: 'zone_central_delhi',
    name: 'Central Delhi & Connaught Place Zone',
    city: 'New Delhi',
    state: 'Delhi',
    postalCodes: ['110001', '110002', '110003', '110005'],
    associatedStoreId: 'store_central_delhi',
    isActive: true,
    minOrderValue: 299,
    baseDeliveryFee: 35,
  },
  {
    id: 'zone_indirapuram',
    name: 'Ghaziabad Indirapuram & Vaishali Zone',
    city: 'Ghaziabad',
    state: 'Uttar Pradesh',
    postalCodes: ['201014', '201010', '201012', '201016'],
    associatedStoreId: 'store_indirapuram',
    isActive: true,
    minOrderValue: 299,
    baseDeliveryFee: 30,
  },
  {
    id: 'zone_lucknow_gomtinagar',
    name: 'Lucknow Gomti Nagar & Hazratganj Express Zone',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    postalCodes: ['226010', '226001', '226016', '226024'],
    associatedStoreId: 'store_lucknow_gomtinagar',
    isActive: true,
    minOrderValue: 299,
    baseDeliveryFee: 30,
  },
  {
    id: 'zone_greater_noida',
    name: 'Greater Noida & Pari Chowk Zone',
    city: 'Greater Noida',
    state: 'Uttar Pradesh',
    postalCodes: ['201308', '201306', '201310'],
    associatedStoreId: 'store_greater_noida',
    isActive: true,
    minOrderValue: 349,
    baseDeliveryFee: 35,
  },
  {
    id: 'zone_kanpur_civillines',
    name: 'Kanpur Civil Lines & Swaroop Nagar Zone',
    city: 'Kanpur',
    state: 'Uttar Pradesh',
    postalCodes: ['208001', '208002', '208005'],
    associatedStoreId: 'store_kanpur_civillines',
    isActive: true,
    minOrderValue: 299,
    baseDeliveryFee: 30,
  },
  {
    id: 'zone_agra_tajganj',
    name: 'Agra Tajganj & Sanjay Place Zone',
    city: 'Agra',
    state: 'Uttar Pradesh',
    postalCodes: ['282001', '282002', '282004'],
    associatedStoreId: 'store_agra_tajganj',
    isActive: true,
    minOrderValue: 299,
    baseDeliveryFee: 30,
  },
  {
    id: 'zone_varanasi_sigra',
    name: 'Varanasi Sigra & Ghats Zone',
    city: 'Varanasi',
    state: 'Uttar Pradesh',
    postalCodes: ['221002', '221005', '221010'],
    associatedStoreId: 'store_varanasi_sigra',
    isActive: true,
    minOrderValue: 299,
    baseDeliveryFee: 30,
  },
];

export const SEED_COMPLIANCE_SETTINGS: PlatformComplianceSettings = {
  legalDrinkingAge: 21, // 21 in Uttar Pradesh; 25 enforced for Delhi per state excise
  jurisdiction: 'Uttar Pradesh & Delhi NCR (State Excise Act Compliant)',
  dryDayActive: false,
  dryDayReason: '',
  maxBottlesPerOrder: 6,
  maxVolumeLitresPerOrder: 9.0,
  operatingHoursOnly: false,
  operatingHoursStart: '10:00',
  operatingHoursEnd: '23:00',
  requireIdProofAtDoorstep: true,
  verificationExpiryDays: 365,
  restrictedPostalCodes: ['201099', '110099'],
  exciseLicenseNumber: 'UP-EXC-2026-RET-9042 / DL-L10-2026-771',
  exciseLicenseValidUntil: '2027-03-31',
};
