import { Product } from '../types.ts';

const VERIFIED_AT = '2026-09-26';

export const DRINKS_PRODUCTS: Product[] = [
  // --- WATER ---
  {
    id: 'prod_bisleri_1l',
    name: 'Bisleri Packaged Drinking Water',
    slug: 'bisleri-packaged-drinking-water',
    brandId: 'b_bisleri',
    brandName: 'Bisleri',
    categoryId: 'cat_water',
    categoryName: 'Water',
    subcategory: 'Packaged Drinking Water',
    price: 20,
    mrp: 20,
    volume: '1 L Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: '10-step purified drinking water with added minerals.',
    tastingNotes: ['Pure', 'Minerals', 'Refreshing'],
    imageUrl: '/images/products/drinks/bisleri-packaged-drinking-water.webp',
    imageSource: 'Bisleri Official Brand Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 310,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
    variants: [
      { id: 'var_bis_500', productId: 'prod_bisleri_1l', name: '500 ml', volume: '500 ml', price: 10, mrp: 10, sku: 'BIS-500', isActive: true },
      { id: 'var_bis_1000', productId: 'prod_bisleri_1l', name: '1 L', volume: '1 L', price: 20, mrp: 20, sku: 'BIS-1000', isActive: true },
      { id: 'var_bis_2000', productId: 'prod_bisleri_1l', name: '2 L', volume: '2 L', price: 35, mrp: 35, sku: 'BIS-2000', isActive: true },
      { id: 'var_bis_6pack', productId: 'prod_bisleri_1l', name: '1L x 6 Pack', volume: '6 x 1L Pack', price: 120, mrp: 120, sku: 'BIS-6PACK', isActive: true },
    ],
  },
  {
    id: 'prod_kinley_water_1l',
    name: 'Kinley Packaged Drinking Water',
    slug: 'kinley-drinking-water',
    brandId: 'b_kinley',
    brandName: 'Kinley',
    categoryId: 'cat_water',
    categoryName: 'Water',
    subcategory: 'Packaged Drinking Water',
    price: 20,
    mrp: 20,
    volume: '1 L Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Reverse osmosis purified water with added minerals from Coca-Cola.',
    tastingNotes: ['Clean', 'Crisp'],
    imageUrl: '/images/products/drinks/kinley-drinking-water.webp',
    imageSource: 'Coca-Cola India Brand Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 145,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_aquafina_water_1l',
    name: 'Aquafina Purified Drinking Water',
    slug: 'aquafina-drinking-water',
    brandId: 'b_aquafina',
    brandName: 'Aquafina',
    categoryId: 'cat_water',
    categoryName: 'Water',
    subcategory: 'Packaged Drinking Water',
    price: 20,
    mrp: 20,
    volume: '1 L Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: '7-step Hydro-7 filtration system purified water from PepsiCo.',
    tastingNotes: ['Crisp Pure Finish'],
    imageUrl: '/images/products/drinks/aquafina-drinking-water.webp',
    imageSource: 'PepsiCo India Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 88,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_himalayan_natural_water',
    name: 'Himalayan Natural Mineral Water',
    slug: 'himalayan-natural-mineral-water',
    brandId: 'b_himalayan',
    brandName: 'Himalayan',
    categoryId: 'cat_water',
    categoryName: 'Water',
    subcategory: 'Natural Mineral Water',
    price: 65,
    mrp: 65,
    volume: '1 L Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Source bottled at Dhaula Kuan in the Shivalik range of Himalayas with natural electrolytes.',
    tastingNotes: ['Silky Alkaline', 'Mountain Fresh'],
    imageUrl: '/images/products/drinks/himalayan-natural-mineral-water.webp',
    imageSource: 'Tata Consumer Products',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.9,
    reviewCount: 76,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_vedica_water_1l',
    name: 'Vedica Himalayan Spring Water',
    slug: 'vedica-spring-water',
    brandId: 'b_vedica',
    brandName: 'Vedica',
    categoryId: 'cat_water',
    categoryName: 'Water',
    subcategory: 'Natural Mineral Water',
    price: 60,
    mrp: 60,
    volume: '1 L Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Natural mountain spring water with balanced alkaline pH and rich mineral composition.',
    tastingNotes: ['Alkaline', 'Smooth Spring Water'],
    imageUrl: '/images/products/drinks/vedica-spring-water.webp',
    imageSource: 'Bisleri Vedica Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.8,
    reviewCount: 45,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- SOFT DRINKS ---
  {
    id: 'prod_coca_cola_750',
    name: 'Coca-Cola Original Taste Chilled Soft Drink',
    slug: 'coca-cola-original-750',
    brandId: 'b_cocacola',
    brandName: 'Coca-Cola',
    categoryId: 'cat_softdrinks',
    categoryName: 'Soft Drinks',
    subcategory: 'Cola',
    price: 40,
    mrp: 40,
    volume: '750 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'The world’s favorite carbonated beverage, served chilled for parties.',
    tastingNotes: ['Fizzy Cola', 'Sweet Vanilla Spice'],
    imageUrl: '/images/products/drinks/coca-cola-original-750.webp',
    imageSource: 'Coca-Cola India Brand Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 280,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
    variants: [
      { id: 'var_coke_300c', productId: 'prod_coca_cola_750', name: '300 ml Can', volume: '300 ml Can', price: 40, mrp: 40, sku: 'COKE-300C', isActive: true },
      { id: 'var_coke_750b', productId: 'prod_coca_cola_750', name: '750 ml Bottle', volume: '750 ml Bottle', price: 40, mrp: 40, sku: 'COKE-750B', isActive: true },
      { id: 'var_coke_2000b', productId: 'prod_coca_cola_750', name: '2 L Party Pack', volume: '2 L Bottle', price: 95, mrp: 95, sku: 'COKE-2L', isActive: true },
    ],
  },
  {
    id: 'prod_thums_up_750',
    name: 'Thums Up Charged Strong Taste Soft Drink',
    slug: 'thums-up-strong-750',
    brandId: 'b_thumsup',
    brandName: 'Thums Up',
    categoryId: 'cat_softdrinks',
    categoryName: 'Soft Drinks',
    subcategory: 'Cola',
    price: 40,
    mrp: 40,
    volume: '750 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Taste the Thunder! India’s strongest spiced cola, ideal party mixer for dark spirits.',
    tastingNotes: ['Spicy Cola', 'High Fizz Kick'],
    imageUrl: '/images/products/drinks/thums-up-strong-750.webp',
    imageSource: 'Coca-Cola India Brand Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 340,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
    variants: [
      { id: 'var_tu_300c', productId: 'prod_thums_up_750', name: '300 ml Can', volume: '300 ml Can', price: 40, mrp: 40, sku: 'TU-300C', isActive: true },
      { id: 'var_tu_750b', productId: 'prod_thums_up_750', name: '750 ml Bottle', volume: '750 ml Bottle', price: 40, mrp: 40, sku: 'TU-750B', isActive: true },
    ],
  },
  {
    id: 'prod_sprite_750',
    name: 'Sprite Lemon-Lime Refreshing Soft Drink',
    slug: 'sprite-lemon-lime-750',
    brandId: 'b_sprite',
    brandName: 'Sprite',
    categoryId: 'cat_softdrinks',
    categoryName: 'Soft Drinks',
    subcategory: 'Lemon-Lime',
    price: 40,
    mrp: 40,
    volume: '750 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Clear, crisp lemon-lime refreshment with 100% natural flavors.',
    tastingNotes: ['Zesty Lemon', 'Crisp Lime', 'Clear Fizz'],
    imageUrl: '/images/products/drinks/sprite-lemon-lime-750.webp',
    imageSource: 'Coca-Cola India Brand Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 220,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_pepsi_750',
    name: 'Pepsi Cola Chilled Soft Drink',
    slug: 'pepsi-cola-750',
    brandId: 'b_pepsi',
    brandName: 'Pepsi',
    categoryId: 'cat_softdrinks',
    categoryName: 'Soft Drinks',
    subcategory: 'Cola',
    price: 40,
    mrp: 40,
    volume: '750 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Bold and refreshing cola beverage, chilled and delivered fast.',
    tastingNotes: ['Bold Citrus Cola', 'Sweet Sparkle'],
    imageUrl: '/images/products/drinks/pepsi-cola-750.webp',
    imageSource: 'PepsiCo India Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 160,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_mountain_dew_750',
    name: 'Mountain Dew Exhilarating Citrus Soda',
    slug: 'mountain-dew-750',
    brandId: 'b_mountaindew',
    brandName: 'Mountain Dew',
    categoryId: 'cat_softdrinks',
    categoryName: 'Soft Drinks',
    subcategory: 'Lemon-Lime',
    price: 40,
    mrp: 40,
    volume: '750 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Darr Ke Aage Jeet Hai! Energizing citrus flavored soda.',
    tastingNotes: ['Electric Citrus', 'Tangy Sweetness'],
    imageUrl: '/images/products/drinks/mountain-dew-750.webp',
    imageSource: 'PepsiCo India Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 110,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_limca_750',
    name: 'Limca Fresh Lime & Lemon Fizzy Drink',
    slug: 'limca-lime-lemon-750',
    brandId: 'b_limca',
    brandName: 'Limca',
    categoryId: 'cat_softdrinks',
    categoryName: 'Soft Drinks',
    subcategory: 'Lemon-Lime',
    price: 40,
    mrp: 40,
    volume: '750 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'India’s pioneer cloudy lemon-lime fizzy soft drink.',
    tastingNotes: ['Cloudy Lime', 'Tangy Lemon'],
    imageUrl: '/images/products/drinks/limca-lime-lemon-750.webp',
    imageSource: 'Coca-Cola India Brand Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 95,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- SODA & MIXERS ---
  {
    id: 'prod_schweppes_tonic',
    name: 'Schweppes Classic Tonic Water Can',
    slug: 'schweppes-tonic-water-can',
    brandId: 'b_schweppes',
    brandName: 'Schweppes',
    categoryId: 'cat_mixers',
    categoryName: 'Soda & Mixers',
    subcategory: 'Tonic Water',
    price: 60,
    mrp: 60,
    volume: '300 ml Can',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'The definitive tonic water crafted with quinine for gin, vodka and mocktails.',
    tastingNotes: ['Crisp Quinine', 'Zesty Citrus Bitterness'],
    imageUrl: '/images/products/drinks/schweppes-tonic-water-can.webp',
    imageSource: 'Schweppes International Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 165,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_schweppes_ginger_ale',
    name: 'Schweppes Ginger Ale Can',
    slug: 'schweppes-ginger-ale-can',
    brandId: 'b_schweppes',
    brandName: 'Schweppes',
    categoryId: 'cat_mixers',
    categoryName: 'Soda & Mixers',
    subcategory: 'Ginger Ale',
    price: 60,
    mrp: 60,
    volume: '300 ml Can',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Delicately carbonated mixer infused with subtle real ginger aromatics.',
    tastingNotes: ['Subtle Ginger Warmth', 'Gentle Sweetness'],
    imageUrl: '/images/products/drinks/schweppes-ginger-ale-can.webp',
    imageSource: 'Schweppes International Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 88,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_kinley_soda_750',
    name: 'Kinley Extra Punch Carbonated Water Club Soda',
    slug: 'kinley-club-soda-750',
    brandId: 'b_kinley',
    brandName: 'Kinley',
    categoryId: 'cat_mixers',
    categoryName: 'Soda & Mixers',
    subcategory: 'Club Soda',
    price: 20,
    mrp: 20,
    volume: '750 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Crisp carbonated club soda with extra fizz, perfect mixer for whisky and juices.',
    tastingNotes: ['High Effervescence', 'Clean Neutral Palate'],
    imageUrl: '/images/products/drinks/kinley-club-soda-750.webp',
    imageSource: 'Coca-Cola India Brand Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 310,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_fever_tree_tonic',
    name: 'Fever-Tree Premium Indian Tonic Water',
    slug: 'fever-tree-indian-tonic',
    brandId: 'b_fevertree',
    brandName: 'Fever-Tree',
    categoryId: 'cat_mixers',
    categoryName: 'Soda & Mixers',
    subcategory: 'Tonic Water',
    price: 160,
    mrp: 160,
    volume: '200 ml Glass Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Blended with spring water and highest quality quinine from the fever trees of DR Congo.',
    tastingNotes: ['Natural Quinine', 'Bitter Orange Essence'],
    imageUrl: '/images/products/drinks/fever-tree-indian-tonic.webp',
    imageSource: 'Fever-Tree Official Global Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'United Kingdom',
    rating: 4.9,
    reviewCount: 65,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Verified Importer MRP List',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_svami_tonic',
    name: 'Svami Light Indian Craft Tonic Water',
    slug: 'svami-light-tonic',
    brandId: 'b_svami',
    brandName: 'Svami',
    categoryId: 'cat_mixers',
    categoryName: 'Soda & Mixers',
    subcategory: 'Tonic Water',
    price: 95,
    mrp: 95,
    volume: '250 ml Glass Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Progressive Indian low calorie craft tonic water with balanced citrus and quinine.',
    tastingNotes: ['Zesty Lime', 'Mild Quinine', 'Low Sugar'],
    imageUrl: '/images/products/drinks/svami-light-tonic.webp',
    imageSource: 'Svami Drinks Official Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.8,
    reviewCount: 55,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- ENERGY DRINKS ---
  {
    id: 'prod_redbull_250',
    name: 'Red Bull Energy Drink Chilled Can',
    slug: 'red-bull-energy-can-250',
    brandId: 'b_redbull',
    brandName: 'Red Bull',
    categoryId: 'cat_energy',
    categoryName: 'Energy Drinks',
    subcategory: 'Original Energy',
    price: 125,
    mrp: 125,
    volume: '250 ml Can',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Red Bull Gives You Wiiings! Vitalizes body and mind with high-grade caffeine and taurine.',
    tastingNotes: ['Crisp Energy Berry', 'Sweet Tang'],
    imageUrl: '/images/products/drinks/red-bull-energy-can-250.webp',
    imageSource: 'Red Bull India Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Austria',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 380,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
    variants: [
      { id: 'var_rb_250', productId: 'prod_redbull_250', name: '250 ml Can', volume: '250 ml Can', price: 125, mrp: 125, sku: 'RB-250C', isActive: true },
      { id: 'var_rb_350', productId: 'prod_redbull_250', name: '350 ml Tall Can', volume: '350 ml Can', price: 165, mrp: 165, sku: 'RB-350C', isActive: true },
      { id: 'var_rb_4pack', productId: 'prod_redbull_250', name: '250ml x 4 Pack', volume: '4 x 250ml Pack', price: 480, mrp: 500, sku: 'RB-4PACK', isActive: true },
    ],
  },
  {
    id: 'prod_monster_energy_350',
    name: 'Monster Energy Original Caffeinated Drink',
    slug: 'monster-energy-original-350',
    brandId: 'b_monster',
    brandName: 'Monster Energy',
    categoryId: 'cat_energy',
    categoryName: 'Energy Drinks',
    subcategory: 'Original Energy',
    price: 125,
    mrp: 125,
    volume: '350 ml Can',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Unleash the Beast! A powerful punch with smooth drinking flavor.',
    tastingNotes: ['Exotic Sweet Fruit', 'Full Energy Punch'],
    imageUrl: '/images/products/drinks/monster-energy-original-350.webp',
    imageSource: 'Monster Energy Official Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'United States',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 190,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_sting_energy_250',
    name: 'Sting Energy Drink Pet Bottle',
    slug: 'sting-energy-drink',
    brandId: 'b_sting',
    brandName: 'Sting',
    categoryId: 'cat_energy',
    categoryName: 'Energy Drinks',
    subcategory: 'Original Energy',
    price: 20,
    mrp: 20,
    volume: '250 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Electrifying berry energy surge with taurine and caffeine from PepsiCo.',
    tastingNotes: ['Sweet Berry', 'Energy Spark'],
    imageUrl: '/images/products/drinks/sting-energy-drink.webp',
    imageSource: 'PepsiCo India Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 220,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- JUICES ---
  {
    id: 'prod_real_mixed_fruit_1l',
    name: 'Real Fruit Power Mixed Fruit Juice',
    slug: 'real-mixed-fruit-juice-1l',
    brandId: 'b_real',
    brandName: 'Real',
    categoryId: 'cat_juices',
    categoryName: 'Juices',
    subcategory: 'Fruit Juice 1L',
    price: 130,
    mrp: 130,
    volume: '1 L Tetrapack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Blend of 9 wholesome fruits packed with no added preservatives.',
    tastingNotes: ['Guava', 'Banana', 'Mango', 'Apple'],
    imageUrl: '/images/products/drinks/real-mixed-fruit-juice-1l.webp',
    imageSource: 'Dabur India Brand Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 175,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_real_cranberry_1l',
    name: 'Real Fruit Power Cranberry Juice Cocktail Mixer',
    slug: 'real-cranberry-juice-1l',
    brandId: 'b_real',
    brandName: 'Real',
    categoryId: 'cat_juices',
    categoryName: 'Juices',
    subcategory: 'Cranberry Mixer',
    price: 145,
    mrp: 145,
    volume: '1 L Tetrapack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Tangy red cranberry beverage, ideal mixer for Cosmopolitans, vodkas and mocktails.',
    tastingNotes: ['Tart Cranberry', 'Ruby Sweetness'],
    imageUrl: '/images/products/drinks/real-cranberry-juice-1l.webp',
    imageSource: 'Dabur India Brand Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 210,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_appy_fizz_600',
    name: 'Appy Fizz Sparkling Apple Juice Drink',
    slug: 'appy-fizz-600',
    brandId: 'b_appyfizz',
    brandName: 'Appy Fizz',
    categoryId: 'cat_juices',
    categoryName: 'Juices',
    subcategory: 'Sparkling Fruit',
    price: 40,
    mrp: 40,
    volume: '600 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Sparkling apple drink with rich carbonated fizz.',
    tastingNotes: ['Crisp Green Apple', 'Sparkling Fizz'],
    imageUrl: '/images/products/drinks/appy-fizz-600.webp',
    imageSource: 'Parle Agro Brand Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 165,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_maaza_mango_600',
    name: 'Maaza Mango Real Pulp Beverage',
    slug: 'maaza-mango-drink-600',
    brandId: 'b_maaza',
    brandName: 'Maaza',
    categoryId: 'cat_juices',
    categoryName: 'Juices',
    subcategory: 'Mango Drinks',
    price: 38,
    mrp: 38,
    volume: '600 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Rich Alphonso and Totapuri mango pulp fruit beverage.',
    tastingNotes: ['Rich Alphonso Mango', 'Sweet Pulp'],
    imageUrl: '/images/products/drinks/maaza-mango-drink-600.webp',
    imageSource: 'Coca-Cola India Brand Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 130,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  }
];
