import { Product } from '../types.ts';

const VERIFIED_AT = '2026-09-26';

export const EXTRA_PRODUCTS: Product[] = [
  // --- VODKA EXPANSION ---
  {
    id: 'prod_romanov_vodka',
    name: 'Romanov Pure Grain Vodka',
    slug: 'romanov-pure-vodka',
    brandId: 'b_romanov',
    brandName: 'Romanov',
    categoryId: 'cat_vodka',
    categoryName: 'Vodka',
    subcategory: 'Grain Vodka',
    price: 520,
    mrp: 520,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Crisp grain neutral vodka filtered for pure cocktail mixing.',
    tastingNotes: ['Neutral Spirit', 'Clean Finish'],
    imageUrl: '/images/products/vodka/romanov-pure-vodka.webp',
    imageSource: 'United Spirits Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.4,
    reviewCount: 35,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_white_mischief',
    name: 'White Mischief Ultra Pure Vodka',
    slug: 'white-mischief-vodka',
    brandId: 'b_whitemischief',
    brandName: 'White Mischief',
    categoryId: 'cat_vodka',
    categoryName: 'Vodka',
    subcategory: 'Grain Vodka',
    price: 480,
    mrp: 480,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Triple-distilled party vodka, easy to mix with orange and cranberry.',
    tastingNotes: ['Smooth Vodka', 'Mild Citrus'],
    imageUrl: '/images/products/vodka/white-mischief-vodka.webp',
    imageSource: 'United Spirits Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.3,
    reviewCount: 40,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_belvedere_vodka',
    name: 'Belvedere Polish Luxury Rye Vodka',
    slug: 'belvedere-luxury-vodka',
    brandId: 'b_belvedere',
    brandName: 'Belvedere',
    categoryId: 'cat_premium',
    categoryName: 'Premium / Imported',
    subcategory: 'Luxury Vodka',
    price: 4250,
    mrp: 4250,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Quadruple-distilled from 100% Polish Dankowskie Rye with zero additives.',
    tastingNotes: ['Vanilla Cream', 'Soft Rye Spice', 'Almond Clotted Cream'],
    imageUrl: '/images/products/alcohol/belvedere-luxury-vodka.webp',
    imageSource: 'Moët Hennessy Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Poland',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 78,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- RUM EXPANSION ---
  {
    id: 'prod_bacardi_black',
    name: 'Bacardi Carta Negra Superior Black Rum',
    slug: 'bacardi-carta-negra-black-rum',
    brandId: 'b_bacardi',
    brandName: 'Bacardi',
    categoryId: 'cat_rum',
    categoryName: 'Rum',
    subcategory: 'Dark Rum',
    price: 980,
    mrp: 980,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Medium-bodied black rum crafted in heavily charred oak barrels.',
    tastingNotes: ['Sweet Molasses', 'Tropical Fruit', 'Dark Toffee'],
    imageUrl: '/images/products/rum/bacardi-carta-negra-black-rum.webp',
    imageSource: 'Bacardi Global Brands',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Puerto Rico',
    rating: 4.7,
    reviewCount: 65,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_mcdowells_celebration',
    name: "McDowell's No.1 Celebration Dark Rum",
    slug: 'mcdowells-celebration-rum',
    brandId: 'b_mcdowell',
    brandName: "McDowell's No.1",
    categoryId: 'cat_rum',
    categoryName: 'Rum',
    subcategory: 'Dark Rum',
    price: 490,
    mrp: 490,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Distinctive dark rum infused with genuine oak flavors and warm caramel.',
    tastingNotes: ['Caramel', 'Oak Warmth'],
    imageUrl: '/images/products/rum/mcdowells-celebration-rum.webp',
    imageSource: 'Diageo India Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.5,
    reviewCount: 125,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_havana_club_3yo',
    name: 'Havana Club 3 Años Cuban White Rum',
    slug: 'havana-club-3-anos',
    brandId: 'b_havanaclub',
    brandName: 'Havana Club',
    categoryId: 'cat_rum',
    categoryName: 'Rum',
    subcategory: 'White Rum',
    price: 1450,
    mrp: 1450,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Authentic Cuban white rum naturally aged for 3 years in ex-bourbon casks.',
    tastingNotes: ['Sugarcane', 'Citrus Vanilla', 'Oak Spice'],
    imageUrl: '/images/products/rum/havana-club-3-anos.webp',
    imageSource: 'Pernod Ricard Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Cuba',
    rating: 4.8,
    reviewCount: 45,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- GIN EXPANSION ---
  {
    id: 'prod_tanqueray_gin',
    name: 'Tanqueray London Dry Gin',
    slug: 'tanqueray-london-dry-gin',
    brandId: 'b_tanqueray',
    brandName: 'Tanqueray',
    categoryId: 'cat_gin',
    categoryName: 'Gin',
    subcategory: 'London Dry',
    price: 2200,
    mrp: 2200,
    volume: '750 ml',
    alcoholByVolume: 43.1,
    isAlcoholic: true,
    description: 'Four times distilled with classic juniper, coriander, angelica and liquorice.',
    tastingNotes: ['Piney Juniper', 'Zesty Coriander', 'Warm Spice'],
    imageUrl: '/images/products/gin/tanqueray-london-dry-gin.webp',
    imageSource: 'Diageo Official Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'United Kingdom',
    rating: 4.8,
    reviewCount: 92,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_hapusa_gin',
    name: 'Hapusa Himalayan Indian Craft Gin',
    slug: 'hapusa-himalayan-craft-gin',
    brandId: 'b_hapusa',
    brandName: 'Hapusa',
    categoryId: 'cat_gin',
    categoryName: 'Gin',
    subcategory: 'Craft Botanical',
    price: 2800,
    mrp: 2800,
    volume: '750 ml',
    alcoholByVolume: 43.0,
    isAlcoholic: true,
    description: 'Himalayan juniper berries distilled with Gondhoraj lime, turmeric, mango and raw coriander.',
    tastingNotes: ['Pine Forest', 'Wild Wild Herbs', 'Earthy Spices'],
    imageUrl: '/images/products/gin/hapusa-himalayan-craft-gin.webp',
    imageSource: 'NAO Spirits India',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 58,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- BRANDY EXPANSION ---
  {
    id: 'prod_morpheus_xo_brandy',
    name: 'Morpheus Blue XO Premium Brandy',
    slug: 'morpheus-xo-brandy',
    brandId: 'b_morpheus',
    brandName: 'Morpheus',
    categoryId: 'cat_brandy',
    categoryName: 'Brandy',
    subcategory: 'French VSOP',
    price: 1100,
    mrp: 1100,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Aged in oak casks from French grapes, full-bodied with warm honey aroma.',
    tastingNotes: ['Honey', 'Vanilla Oak', 'Warm Grape'],
    imageUrl: '/images/products/brandy/morpheus-xo-brandy.webp',
    imageSource: 'Radico Khaitan Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.6,
    reviewCount: 48,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_hennessy_vs_cognac',
    name: 'Hennessy Very Special Cognac',
    slug: 'hennessy-vs-cognac',
    brandId: 'b_hennessy',
    brandName: 'Hennessy',
    categoryId: 'cat_premium',
    categoryName: 'Premium / Imported',
    subcategory: 'Cognac',
    price: 5400,
    mrp: 5400,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'A blend of some 40 eaux-de-vie from Cognac, aged in new French oak barrels.',
    tastingNotes: ['Toasted Almond', 'Fresh Toast', 'Grape Fruity Palate'],
    imageUrl: '/images/products/alcohol/hennessy-vs-cognac.webp',
    imageSource: 'Moët Hennessy Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'France',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 65,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- WINE EXPANSION ---
  {
    id: 'prod_fratelli_shiraz',
    name: 'Fratelli Classic Shiraz Red Wine',
    slug: 'fratelli-classic-shiraz',
    brandId: 'b_fratelli',
    brandName: 'Fratelli',
    categoryId: 'cat_wine',
    categoryName: 'Wine',
    subcategory: 'Red Wine',
    price: 850,
    mrp: 850,
    volume: '750 ml',
    alcoholByVolume: 13.5,
    isAlcoholic: true,
    description: 'Estate grown Akluj vineyard red wine with ruby red hints and spicy berries.',
    tastingNotes: ['Dark Berry', 'Spicy Black Pepper', 'Supple Tannin'],
    imageUrl: '/images/products/wine/fratelli-classic-shiraz.webp',
    imageSource: 'Fratelli Wines Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 55,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Wine Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_grover_la_reserve',
    name: 'Grover Zampa La Réserve Red Wine',
    slug: 'grover-zampa-la-reserve',
    brandId: 'b_groverzampa',
    brandName: 'Grover Zampa',
    categoryId: 'cat_wine',
    categoryName: 'Wine',
    subcategory: 'Red Wine',
    price: 1200,
    mrp: 1200,
    volume: '750 ml',
    alcoholByVolume: 13.5,
    isAlcoholic: true,
    description: 'Handpicked Cabernet Sauvignon & Shiraz matured in French oak barrels.',
    tastingNotes: ['Chocolate', 'Roasted Coffee Bean', 'Dark Cherry'],
    imageUrl: '/images/products/wine/grover-zampa-la-reserve.webp',
    imageSource: 'Grover Zampa Vineyards',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.8,
    reviewCount: 68,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Wine Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_yellow_tail_shiraz',
    name: 'Yellow Tail Shiraz Australian Red Wine',
    slug: 'yellow-tail-shiraz',
    brandId: 'b_yellowtail',
    brandName: '[yellow tail]',
    categoryId: 'cat_wine',
    categoryName: 'Wine',
    subcategory: 'Red Wine',
    price: 1550,
    mrp: 1550,
    volume: '750 ml',
    alcoholByVolume: 13.5,
    isAlcoholic: true,
    description: 'Fruit-forward vibrant red with juicy blackberry and warm vanilla notes.',
    tastingNotes: ['Crushed Blackberry', 'Sweet Spiced Oak'],
    imageUrl: '/images/products/wine/yellow-tail-shiraz.webp',
    imageSource: 'Casella Family Brands',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Australia',
    rating: 4.7,
    reviewCount: 42,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- TEQUILA & SPARKLING EXPANSION ---
  {
    id: 'prod_don_julio_blanco',
    name: 'Don Julio Blanco 100% Blue Agave Tequila',
    slug: 'don-julio-blanco-tequila',
    brandId: 'b_donjulio',
    brandName: 'Don Julio',
    categoryId: 'cat_premium',
    categoryName: 'Premium / Imported',
    subcategory: 'Blanco',
    price: 6500,
    mrp: 6500,
    volume: '750 ml',
    alcoholByVolume: 38.0,
    isAlcoholic: true,
    description: 'Crisp agave flavor with clean citrus and sweet finish crafted in the highlands of Jalisco.',
    tastingNotes: ['Fresh Agave', 'Crisp Lemon', 'Sweet Grass'],
    imageUrl: '/images/products/alcohol/don-julio-blanco-tequila.webp',
    imageSource: 'Diageo Mexico Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Mexico',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 50,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_patron_silver',
    name: 'Patrón Silver Artisanal Tequila',
    slug: 'patron-silver-tequila',
    brandId: 'b_patron',
    brandName: 'Patrón',
    categoryId: 'cat_premium',
    categoryName: 'Premium / Imported',
    subcategory: 'Blanco',
    price: 6800,
    mrp: 6800,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Handmade in small batches from finest 100% Weber Blue Agave in copper pot stills.',
    tastingNotes: ['Light Pepper', 'Smooth Fresh Agave', 'Citrus'],
    imageUrl: '/images/products/alcohol/patron-silver-tequila.webp',
    imageSource: 'Bacardi Global Brands',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Mexico',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 62,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_freixenet_cordon_negro',
    name: 'Freixenet Cordon Negro Brut Cava',
    slug: 'freixenet-cordon-negro-brut',
    brandId: 'b_freixenet',
    brandName: 'Freixenet',
    categoryId: 'cat_sparkling',
    categoryName: 'Sparkling Wine',
    subcategory: 'Sparkling Brut',
    price: 1850,
    mrp: 1850,
    volume: '750 ml',
    alcoholByVolume: 11.5,
    isAlcoholic: true,
    description: 'Crisp Spanish Cava in distinctive matte black bottle with fine persistent bubbles.',
    tastingNotes: ['Green Apple', 'Pear', 'Crisp Brioche'],
    imageUrl: '/images/products/wine/freixenet-cordon-negro-brut.webp',
    imageSource: 'Henkell Freixenet Global',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Spain',
    rating: 4.8,
    reviewCount: 45,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- DRINKS EXTRA ---
  {
    id: 'prod_7up_750',
    name: '7UP Refreshing Clear Lemon-Lime Drink',
    slug: '7up-lemon-lime-750',
    brandId: 'b_7up',
    brandName: '7UP',
    categoryId: 'cat_softdrinks',
    categoryName: 'Soft Drinks',
    subcategory: 'Lemon-Lime',
    price: 40,
    mrp: 40,
    volume: '750 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: '100% natural lemon and lime flavors, chilled for instant thirst quenching.',
    tastingNotes: ['Crisp Lime', 'Cool Lemon'],
    imageUrl: '/images/products/drinks/7up-lemon-lime-750.webp',
    imageSource: 'PepsiCo India Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 155,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_fanta_750',
    name: 'Fanta Orange Flavored Carbonated Drink',
    slug: 'fanta-orange-750',
    brandId: 'b_fanta',
    brandName: 'Fanta',
    categoryId: 'cat_softdrinks',
    categoryName: 'Soft Drinks',
    subcategory: 'Orange & Citrus',
    price: 40,
    mrp: 40,
    volume: '750 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Bright bubbly orange fruit drink with zesty fizzy bubbles.',
    tastingNotes: ['Tangy Sweet Orange'],
    imageUrl: '/images/products/drinks/fanta-orange-750.webp',
    imageSource: 'Coca-Cola India Brand Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 110,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_mirinda_750',
    name: 'Mirinda Sparkling Orange Soft Drink',
    slug: 'mirinda-orange-750',
    brandId: 'b_mirinda',
    brandName: 'Mirinda',
    categoryId: 'cat_softdrinks',
    categoryName: 'Soft Drinks',
    subcategory: 'Orange & Citrus',
    price: 40,
    mrp: 40,
    volume: '750 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Fizzy tangy orange soft drink with intense fruit burst.',
    tastingNotes: ['Bold Sweet Citrus'],
    imageUrl: '/images/products/drinks/mirinda-orange-750.webp',
    imageSource: 'PepsiCo India Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.6,
    reviewCount: 88,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_hell_energy_250',
    name: 'Hell Energy Classic Drink Can',
    slug: 'hell-energy-can-250',
    brandId: 'b_hellenergy',
    brandName: 'Hell Energy',
    categoryId: 'cat_energy',
    categoryName: 'Energy Drinks',
    subcategory: 'Original Energy',
    price: 60,
    mrp: 60,
    volume: '250 ml Can',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'European formula with 32mg/100ml caffeine, vitamins B2, B3, B5, B6, B12 and zero preservatives.',
    tastingNotes: ['Classic Energy Tutti Frutti'],
    imageUrl: '/images/products/drinks/hell-energy-can-250.webp',
    imageSource: 'Hell Energy Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Hungary',
    rating: 4.7,
    reviewCount: 95,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_tropicana_orange_1l',
    name: 'Tropicana 100% Real Orange Juice',
    slug: 'tropicana-orange-1l',
    brandId: 'b_tropicana',
    brandName: 'Tropicana',
    categoryId: 'cat_juices',
    categoryName: 'Juices',
    subcategory: 'Fruit Juice 1L',
    price: 140,
    mrp: 140,
    volume: '1 L Tetrapack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: '100% real orange juice with no added sugar, rich in vitamin C.',
    tastingNotes: ['Sun-Ripened Orange', 'Pure Citrus'],
    imageUrl: '/images/products/drinks/tropicana-orange-1l.webp',
    imageSource: 'PepsiCo India Tropicana Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 130,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_paperboat_aamras',
    name: 'Paper Boat Aamras Alphonso Mango Treat',
    slug: 'paper-boat-aamras-250',
    brandId: 'b_paperboat',
    brandName: 'Paper Boat',
    categoryId: 'cat_juices',
    categoryName: 'Juices',
    subcategory: 'Mango Drinks',
    price: 35,
    mrp: 35,
    volume: '250 ml Pouch',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: '45% real mango pulp traditional aamras made from authentic Indian mangoes.',
    tastingNotes: ['Homestyle Mango Pulp', 'Cardamom Touch'],
    imageUrl: '/images/products/drinks/paper-boat-aamras-250.webp',
    imageSource: 'Hector Beverages Paper Boat Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 240,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- SNACKS & PARTY ESSENTIALS EXTRA ---
  {
    id: 'prod_lays_cream_onion',
    name: "Lay's American Style Cream & Onion Potato Chips",
    slug: 'lays-cream-onion',
    brandId: 'b_lays',
    brandName: "Lay's",
    categoryId: 'cat_snacks',
    categoryName: 'Chips & Namkeen',
    subcategory: 'Potato Chips',
    price: 20,
    mrp: 20,
    volume: '50g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Classic American style sour cream and herb green onion seasoning.',
    tastingNotes: ['Sour Cream', 'Green Herb Onion'],
    imageUrl: '/images/products/snacks/lays-cream-onion.webp',
    imageSource: 'PepsiCo India Frito-Lay',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 310,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_bingo_mad_angles',
    name: 'Bingo! Mad Angles Achaari Masti Snack',
    slug: 'bingo-mad-angles-achaari',
    brandId: 'b_bingo',
    brandName: 'Bingo!',
    categoryId: 'cat_partysnacks',
    categoryName: 'Party Snacks',
    subcategory: 'Spicy Rings',
    price: 20,
    mrp: 20,
    volume: '66g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Triangular crispy rice and corn chips coated in spicy mango pickle masala.',
    tastingNotes: ['Achaari Mango Pickle', 'Crispy Rice Corn'],
    imageUrl: '/images/products/party/bingo-mad-angles-achaari.webp',
    imageSource: 'ITC Foods Official Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 165,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_uncle_chipps',
    name: 'Uncle Chipps Spicy Treat Potato Chips',
    slug: 'uncle-chipps-spicy-treat',
    brandId: 'b_unclechipps',
    brandName: 'Uncle Chipps',
    categoryId: 'cat_snacks',
    categoryName: 'Chips & Namkeen',
    subcategory: 'Potato Chips',
    price: 20,
    mrp: 20,
    volume: '50g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Bole Mere Lips, I Love Uncle Chipps! Golden ridged potatoes with authentic Indian spices.',
    tastingNotes: ['Classic Tangy Masala', 'Deep Ridged Crunch'],
    imageUrl: '/images/products/snacks/uncle-chipps-spicy-treat.webp',
    imageSource: 'PepsiCo India Frito-Lay',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 280,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_roasted_salted_almonds',
    name: 'Nutraj Roasted & Salted California Almonds',
    slug: 'nutraj-roasted-salted-almonds',
    brandId: 'b_nutraj',
    brandName: 'Nutraj',
    categoryId: 'cat_nuts',
    categoryName: 'Peanuts & Nuts',
    subcategory: 'Almonds',
    price: 260,
    mrp: 285,
    volume: '200g Pouch',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: '100% California almonds dry-roasted and seasoned with rock salt.',
    tastingNotes: ['Nutty Crunch', 'Fine Salt'],
    imageUrl: '/images/products/snacks/nutraj-roasted-salted-almonds.webp',
    imageSource: 'Nutraj Official Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.8,
    reviewCount: 95,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_doritos_sweet_chilli',
    name: 'Doritos Sweet Chilli Tortilla Chips',
    slug: 'doritos-sweet-chilli',
    brandId: 'b_doritos',
    brandName: 'Doritos',
    categoryId: 'cat_nachos',
    categoryName: 'Nachos',
    subcategory: 'Barbeque & Chilli',
    price: 50,
    mrp: 50,
    volume: '100g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Crisp triangular corn nachos with sweet pepper heat.',
    tastingNotes: ['Sweet Chilli Glaze', 'Corn Crunch'],
    imageUrl: '/images/products/snacks/doritos-sweet-chilli.webp',
    imageSource: 'PepsiCo India Frito-Lay',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 140,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_party_balloons_50',
    name: 'Multi-Color Metallic Party Latex Balloons',
    slug: 'metallic-party-balloons-50',
    brandId: 'b_partytime',
    brandName: 'PartyTime Essentials',
    categoryId: 'cat_party',
    categoryName: 'Other Party Essentials',
    subcategory: 'Balloons & Candles',
    price: 99,
    mrp: 125,
    volume: '50 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Vibrant chrome metallic finish high-elasticity balloons for birthdays and parties.',
    tastingNotes: ['Metallic Shimmer', 'Non-Toxic Latex'],
    imageUrl: '/images/products/party/party-balloons.webp',
    imageSource: 'PartyTime Essentials Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 160,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_birthday_candles_12',
    name: 'Metallic Spiral Birthday Celebration Candles',
    slug: 'spiral-birthday-candles-12',
    brandId: 'b_partytime',
    brandName: 'PartyTime Essentials',
    categoryId: 'cat_party',
    categoryName: 'Other Party Essentials',
    subcategory: 'Balloons & Candles',
    price: 45,
    mrp: 55,
    volume: '12 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Gold and silver spiral celebration candles with sturdy holders.',
    tastingNotes: ['Smokeless Paraffin', 'Steady Flame'],
    imageUrl: '/images/products/party/spiral-birthday-candles-12.webp',
    imageSource: 'PartyTime Essentials Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 88,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_freshwrap_foil_9m',
    name: 'Freshwrap Food Grade Aluminium Foil 9 Metres',
    slug: 'freshwrap-foil-9m',
    brandId: 'b_freshwrap',
    brandName: 'Freshwrap',
    categoryId: 'cat_party',
    categoryName: 'Other Party Essentials',
    subcategory: 'Foil & Wrap',
    price: 95,
    mrp: 105,
    volume: '9 Metres',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Bacteria resistant thick aluminum foil to keep party snacks, rolls and kebabs piping hot.',
    tastingNotes: ['11 Micron Thickness', 'Food Grade Barrier'],
    imageUrl: '/images/products/party/freshwrap-foil-9m.webp',
    imageSource: 'Hindalco Freshwrap Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 140,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_cling_film_30m',
    name: 'Freshwrap Microwave Safe Cling Film Wrap 30 Metres',
    slug: 'cling-film-wrap-30m',
    brandId: 'b_freshwrap',
    brandName: 'Freshwrap',
    categoryId: 'cat_party',
    categoryName: 'Other Party Essentials',
    subcategory: 'Foil & Wrap',
    price: 110,
    mrp: 125,
    volume: '30 Metres',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'BPA-free transparent stretch wrap with slide cutter for sealing salad bowls, dips and glasses.',
    tastingNotes: ['Airtight Cling', 'Slide Cutter'],
    imageUrl: '/images/products/party/cling-film-wrap-30m.webp',
    imageSource: 'Freshwrap Brand Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.8,
    reviewCount: 95,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_wet_wipes_80',
    name: 'Origami Disinfectant Hand & Face Wet Wipes',
    slug: 'origami-wet-wipes-80',
    brandId: 'b_origami',
    brandName: 'Origami',
    categoryId: 'cat_party',
    categoryName: 'Other Party Essentials',
    subcategory: 'Garbage Bags & Wipes',
    price: 115,
    mrp: 135,
    volume: '80 Wipes Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Alcohol-free soothing aloe vera and vitamin E wipes with resealable moisture lid.',
    tastingNotes: ['Aloe Vera Infused', 'Resealable Flip Cap'],
    imageUrl: '/images/products/party/origami-wet-wipes-80.webp',
    imageSource: 'Origami Official Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 160,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_paper_cups_200',
    name: 'Disposable Eco Paper Cups 200ml',
    slug: 'disposable-paper-cups-200',
    brandId: 'b_origami',
    brandName: 'Origami',
    categoryId: 'cat_party_glasses',
    categoryName: 'Disposable Glasses',
    subcategory: 'Paper Cups',
    price: 60,
    mrp: 70,
    volume: '50 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Leak-proof virgin paper cups for hot drinks, cold soft drinks and cocktails.',
    tastingNotes: ['Leak Proof Rim', 'Eco Friendly'],
    imageUrl: '/images/products/party/disposable-paper-cups-200.webp',
    imageSource: 'Origami Brand Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 190,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_paper_plates_7',
    name: 'Disposable Paper Snack Plates 7"',
    slug: 'disposable-paper-plates-7',
    brandId: 'b_homeone',
    brandName: 'Home One',
    categoryId: 'cat_party_plates',
    categoryName: 'Disposable Plates',
    subcategory: '7" Plates',
    price: 45,
    mrp: 50,
    volume: '25 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Compact 7-inch paper plates for serving dry snacks, cake, samosas and kebab bites.',
    tastingNotes: ['Snack Plate Standard', 'Leak Resistant'],
    imageUrl: '/images/products/party/paper-plates-9in.webp',
    imageSource: 'Home One Official Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 175,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_compartment_plates_12',
    name: '3-Compartment Thali Paper Plates 12"',
    slug: '3-compartment-thali-plates-12',
    brandId: 'b_homeone',
    brandName: 'Home One',
    categoryId: 'cat_party_plates',
    categoryName: 'Disposable Plates',
    subcategory: 'Compartment Plates',
    price: 90,
    mrp: 105,
    volume: '20 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Extra deep 3-section compartment thali plates for dinner, dal makhani, rice and snacks without mixing.',
    tastingNotes: ['Deep Section Dividers', 'Extra Heavy Duty'],
    imageUrl: '/images/products/party/paper-plates-9in.webp',
    imageSource: 'Home One Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 215,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_disposable_spoons_50',
    name: 'Disposable Food Grade White Spoons',
    slug: 'disposable-white-spoons-50',
    brandId: 'b_homeone',
    brandName: 'Home One',
    categoryId: 'cat_party_cutlery',
    categoryName: 'Cutlery',
    subcategory: 'Spoons',
    price: 40,
    mrp: 45,
    volume: '50 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Smooth edged food-grade plastic spoons for party desserts, dal and rice.',
    tastingNotes: ['Rigid Plastic', 'Safe Smooth Rim'],
    imageUrl: '/images/products/party/disposable-white-spoons-50.webp',
    imageSource: 'Home One Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 180,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_disposable_forks_50',
    name: 'Disposable Food Grade White Forks',
    slug: 'disposable-white-forks-50',
    brandId: 'b_homeone',
    brandName: 'Home One',
    categoryId: 'cat_party_cutlery',
    categoryName: 'Cutlery',
    subcategory: 'Forks',
    price: 40,
    mrp: 45,
    volume: '50 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Strong tines for snacks, salads, noodles and appetizers.',
    tastingNotes: ['Durable Prongs', 'BPA Free'],
    imageUrl: '/images/products/party/disposable-white-forks-50.webp',
    imageSource: 'Home One Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 195,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_wooden_cutlery_combo',
    name: 'Eco Birch Wooden Cutlery Set (25 Spoons + 25 Forks)',
    slug: 'eco-birch-wooden-cutlery-50',
    brandId: 'b_ecosoul',
    brandName: 'EcoSoul',
    categoryId: 'cat_party_cutlery',
    categoryName: 'Cutlery',
    subcategory: 'Wooden Cutlery',
    price: 95,
    mrp: 115,
    volume: '50 Pack (25S + 25F)',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: '100% natural smooth-finished birchwood cutlery, biodegradable and compostable.',
    tastingNotes: ['Splinter-Free Birch', 'Eco Luxe'],
    imageUrl: '/images/products/party/cutlery-combo-set.webp',
    imageSource: 'EcoSoul Home Products',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.9,
    reviewCount: 110,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_corona_multipack_6',
    name: 'Corona Extra 330ml x 6 Bottle Party Pack',
    slug: 'corona-extra-6-pack',
    brandId: 'b_corona',
    brandName: 'Corona Extra',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Multipack',
    price: 1399,
    mrp: 1440,
    volume: '6 x 330ml Pack',
    alcoholByVolume: 4.5,
    isAlcoholic: true,
    description: 'Chilled six-pack of authentic imported Corona Extra bottles in sturdy party carrier.',
    tastingNotes: ['Crisp Corn', 'Citrus Hop', 'Clean Refreshment'],
    imageUrl: '/images/products/beer/corona-extra-330ml.webp',
    imageSource: 'Grupo Modelo Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Mexico',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 160,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_budweiser_magnum_can_500',
    name: 'Budweiser Magnum Strong 500ml Can',
    slug: 'budweiser-magnum-can-500',
    brandId: 'b_budweiser',
    brandName: 'Budweiser',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Strong Beer',
    price: 165,
    mrp: 165,
    volume: '500 ml Can',
    alcoholByVolume: 6.5,
    isAlcoholic: true,
    description: 'Beechwood-aged dark golden strong beer in easy chilling aluminium can.',
    tastingNotes: ['Rich Malt', 'Smooth Alcohol Kick'],
    imageUrl: '/images/products/beer/budweiser-magnum-can-500.webp',
    imageSource: 'AB InBev India Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'United States',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 180,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_bira91_white_can_330',
    name: 'Bira 91 White Craft Wheat 330ml Can',
    slug: 'bira-91-white-can-330',
    brandId: 'b_bira91',
    brandName: 'Bira 91',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Craft Wheat',
    price: 130,
    mrp: 130,
    volume: '330 ml Can',
    alcoholByVolume: 4.7,
    isAlcoholic: true,
    description: 'Aromatic low-bitterness wheat beer with coriander seeds and orange peel.',
    tastingNotes: ['Orange Zest', 'Coriander Seed'],
    imageUrl: '/images/products/beer/bira-91-white-can-330.webp',
    imageSource: 'Bira 91 Brewery',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 120,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_bisleri_500ml',
    name: 'Bisleri Mineral Water 500ml On-The-Go',
    slug: 'bisleri-mineral-water-500ml',
    brandId: 'b_bisleri',
    brandName: 'Bisleri',
    categoryId: 'cat_water',
    categoryName: 'Water',
    subcategory: 'Packaged Drinking Water',
    price: 10,
    mrp: 10,
    volume: '500 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Purified mineral water with essential minerals in pocket size.',
    tastingNotes: ['Pure Mineral Crispness'],
    imageUrl: '/images/products/drinks/bisleri-mineral-water-500ml.webp',
    imageSource: 'Bisleri Brand Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 220,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_bisleri_2l',
    name: 'Bisleri Packaged Drinking Water 2L Party Size',
    slug: 'bisleri-water-2l',
    brandId: 'b_bisleri',
    brandName: 'Bisleri',
    categoryId: 'cat_water',
    categoryName: 'Water',
    subcategory: 'Packaged Drinking Water',
    price: 35,
    mrp: 35,
    volume: '2 L Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Large family party size pure mineral water bottle.',
    tastingNotes: ['Pure Crisp Hydration'],
    imageUrl: '/images/products/drinks/bisleri-water-2l.webp',
    imageSource: 'Bisleri Brand Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 190,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_fever_tree_ginger_beer',
    name: 'Fever-Tree Spiced Ginger Beer Bottle',
    slug: 'fever-tree-ginger-beer',
    brandId: 'b_fevertree',
    brandName: 'Fever-Tree',
    categoryId: 'cat_mixers',
    categoryName: 'Soda & Mixers',
    subcategory: 'Ginger Ale',
    price: 160,
    mrp: 160,
    volume: '200 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Brewed with 3 gingers from Nigeria, Cochin and Ivory Coast.',
    tastingNotes: ['Fiery Fresh Ginger', 'Warm Spice'],
    imageUrl: '/images/products/drinks/fever-tree-ginger-beer.webp',
    imageSource: 'Fever-Tree Global Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'United Kingdom',
    rating: 4.8,
    reviewCount: 45,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_svami_ginger_ale',
    name: 'Svami Artisanal Ginger Ale Glass Bottle',
    slug: 'svami-artisanal-ginger-ale',
    brandId: 'b_svami',
    brandName: 'Svami',
    categoryId: 'cat_mixers',
    categoryName: 'Soda & Mixers',
    subcategory: 'Ginger Ale',
    price: 95,
    mrp: 95,
    volume: '250 ml Bottle',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Low-calorie craft ginger ale brewed with real Indian ginger juice.',
    tastingNotes: ['Zesty Ginger', 'Crisp Lemon'],
    imageUrl: '/images/products/drinks/svami-artisanal-ginger-ale.webp',
    imageSource: 'Svami Brand Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 38,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_haldirams_moong_dal_200',
    name: "Haldiram's Crispy Salted Moong Dal",
    slug: 'haldirams-salted-moong-dal',
    brandId: 'b_haldirams',
    brandName: "Haldiram's",
    categoryId: 'cat_snacks',
    categoryName: 'Chips & Namkeen',
    subcategory: 'Sev & Mixture',
    price: 55,
    mrp: 55,
    volume: '200g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Golden split yellow mung beans fried and salted for light crunch.',
    tastingNotes: ['Delicate Salt', 'Crunchy Mung Pulse'],
    imageUrl: '/images/products/snacks/haldirams-salted-moong-dal.webp',
    imageSource: "Haldiram's Official",
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 165,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_bikaji_aloo_bhujia_200',
    name: 'Bikaji Aloo Bhujia Sub Kuch Masaledar',
    slug: 'bikaji-aloo-bhujia-200',
    brandId: 'b_bikaji',
    brandName: 'Bikaji',
    categoryId: 'cat_snacks',
    categoryName: 'Chips & Namkeen',
    subcategory: 'Aloo Bhujia',
    price: 50,
    mrp: 50,
    volume: '200g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Crisp potato and moth dal strands seasoned with mint and red chilli.',
    tastingNotes: ['Spicy Mint', 'Bikaneri Crunch'],
    imageUrl: '/images/products/snacks/haldirams-aloo-bhujia-150g.webp',
    imageSource: 'Bikaji Foods Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 95,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_balaji_ratlami_sev_150',
    name: 'Balaji Ratlami Sev Crunchy Namkeen',
    slug: 'balaji-ratlami-sev',
    brandId: 'b_balaji',
    brandName: 'Balaji',
    categoryId: 'cat_snacks',
    categoryName: 'Chips & Namkeen',
    subcategory: 'Sev & Mixture',
    price: 35,
    mrp: 35,
    volume: '150g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Spicy clove and carom flavored thick chickpea sev.',
    tastingNotes: ['Clove Aromatic', 'Ajwain Heat'],
    imageUrl: '/images/products/snacks/balaji-ratlami-sev.webp',
    imageSource: 'Balaji Wafers Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.6,
    reviewCount: 75,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_makino_jalapeno_nachos',
    name: 'Makino Nacho Chips Jalapeno Salsa',
    slug: 'makino-jalapeno-nachos',
    brandId: 'b_makino',
    brandName: 'Makino',
    categoryId: 'cat_nachos',
    categoryName: 'Nachos',
    subcategory: 'Jalapeno',
    price: 85,
    mrp: 90,
    volume: '150g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Crisp Mexican corn tortilla chips with tangy pickled jalapeno seasoning.',
    tastingNotes: ['Jalapeno Zest', 'Crisp Corn'],
    imageUrl: '/images/products/snacks/makino-jalapeno-nachos.webp',
    imageSource: 'Makino Foods Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 65,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_4700bc_cheese_popcorn',
    name: '4700BC Gourmet Himalayan Cheese Popcorn',
    slug: '4700bc-cheese-popcorn',
    brandId: 'b_4700bc',
    brandName: '4700BC',
    categoryId: 'cat_popcorn',
    categoryName: 'Popcorn',
    subcategory: 'Gourmet Cheese',
    price: 75,
    mrp: 85,
    volume: '75g Bag',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Artisanal popped jumbo corn coated with real aged cheddar and Himalayan pink salt.',
    tastingNotes: ['Sharp Cheddar', 'Pink Salt'],
    imageUrl: '/images/products/snacks/4700bc-cheese-popcorn.webp',
    imageSource: '4700BC Brand Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 110,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_kitchens_of_india_dal_bukhara',
    name: 'Kitchens of India Gourmet Dal Bukhara',
    slug: 'kitchens-of-india-dal-bukhara',
    brandId: 'b_kitchensofindia',
    brandName: 'Kitchens of India',
    categoryId: 'cat_readytoeat',
    categoryName: 'Ready-to-Eat',
    subcategory: 'Dal Makhani & Gravies',
    price: 160,
    mrp: 175,
    volume: '285g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Legendary ITC Maurya recipe slow-simmered whole black lentils over coal fire with tomatoes, butter and cream.',
    tastingNotes: ['Slow-Cooked Coal Smoke', 'Creamy Rich Dal'],
    imageUrl: '/images/products/snacks/kitchens-of-india-dal-bukhara.webp',
    imageSource: 'ITC Hotels Kitchens of India',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 95,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_origami_napkins_luncheon',
    name: 'Origami Luncheon Soft Table Napkins 100 Pack',
    slug: 'origami-luncheon-napkins-100',
    brandId: 'b_origami',
    brandName: 'Origami',
    categoryId: 'cat_party_napkins',
    categoryName: 'Napkins',
    subcategory: 'Table Napkins',
    price: 65,
    mrp: 75,
    volume: '100 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Thick 2-ply soft embossed table napkins for house parties and dinners.',
    tastingNotes: ['2-Ply Soft Touch', 'Luxe Embossed'],
    imageUrl: '/images/products/party/paper-napkins.webp',
    imageSource: 'Origami Official Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 160,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_silicone_party_straws_6',
    name: 'PartyTime Reusable Silicone Party Straws with Cleaner',
    slug: 'silicone-party-straws-6',
    brandId: 'b_partytime',
    brandName: 'PartyTime Essentials',
    categoryId: 'cat_party_straws',
    categoryName: 'Straws',
    subcategory: 'Silicone Reusable',
    price: 130,
    mrp: 150,
    volume: '6 Pack + Cleaner Brush',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Food grade BPA-free colorful silicone drinking straws with mini cleaning wire.',
    tastingNotes: ['BPA Free Silicone', 'Dishwasher Safe'],
    imageUrl: '/images/products/party/cocktail-straws.webp',
    imageSource: 'PartyTime Essentials Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.8,
    reviewCount: 72,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  }
];
