import { Product } from '../types.ts';

const VERIFIED_AT = '2026-09-26';

export const ALCOHOL_PRODUCTS: Product[] = [
  // --- WHISKY ---
  {
    id: 'prod_royal_stag_deluxe',
    name: 'Royal Stag Deluxe Whisky',
    slug: 'royal-stag-deluxe-whisky',
    brandId: 'b_royalstag',
    brandName: 'Royal Stag',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Whisky',
    price: 675,
    mrp: 675,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Blended Indian whisky with selected Scotch malts and Indian grain spirits.',
    tastingNotes: ['Malt', 'Oak', 'Warm finish'],
    imageUrl: '/images/products/whisky/royal-stag-deluxe-whisky.webp',
    imageSource: 'https://www.bswliquor.com/products/royal-stag-deluxe',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 142,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'UP State Excise Approved MRP & Retail Catalogue',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [
      { market: 'Lucknow & UP', state: 'Uttar Pradesh', price: 675, mrp: 675, currency: 'INR', source: 'UP Excise', sourceType: 'official', verified: true, verifiedAt: VERIFIED_AT },
      { market: 'Delhi NCR', state: 'Delhi', price: 660, mrp: 660, currency: 'INR', source: 'Delhi Excise', sourceType: 'official', verified: true, verifiedAt: VERIFIED_AT }
    ],
    variants: [
      { id: 'var_rs_180', productId: 'prod_royal_stag_deluxe', name: '180 ml', volume: '180 ml', price: 165, mrp: 165, sku: 'RS-DELUXE-180', isActive: true },
      { id: 'var_rs_375', productId: 'prod_royal_stag_deluxe', name: '375 ml', volume: '375 ml', price: 340, mrp: 340, sku: 'RS-DELUXE-375', isActive: true },
      { id: 'var_rs_750', productId: 'prod_royal_stag_deluxe', name: '750 ml', volume: '750 ml', price: 675, mrp: 675, sku: 'RS-DELUXE-750', isActive: true },
    ],
  },
  {
    id: 'prod_blenders_pride_rare',
    name: 'Blenders Pride Rare Premium Whisky',
    slug: 'blenders-pride-rare-premium-whisky',
    brandId: 'b_blenderspride',
    brandName: 'Blenders Pride',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Premium',
    price: 880,
    mrp: 880,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Blended from Indian grain spirits and imported Scotch malt.',
    tastingNotes: ['Honey', 'Oak', 'Fruit'],
    imageUrl: '/images/products/whisky/blenders-pride-rare-premium-whisky.webp',
    imageSource: 'https://www.bswliquor.com/products/blenders-pride-rare-premium',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 98,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'UP State Excise Approved MRP & Retail Catalogue',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [
      { market: 'Uttar Pradesh', state: 'Uttar Pradesh', price: 880, mrp: 880, currency: 'INR', source: 'UP Excise', sourceType: 'official', verified: true, verifiedAt: VERIFIED_AT },
      { market: 'Delhi', state: 'Delhi', price: 860, mrp: 860, currency: 'INR', source: 'Delhi Excise', sourceType: 'official', verified: true, verifiedAt: VERIFIED_AT }
    ],
    variants: [
      { id: 'var_bp_180', productId: 'prod_blenders_pride_rare', name: '180 ml', volume: '180 ml', price: 220, mrp: 220, sku: 'BP-RARE-180', isActive: true },
      { id: 'var_bp_375', productId: 'prod_blenders_pride_rare', name: '375 ml', volume: '375 ml', price: 440, mrp: 440, sku: 'BP-RARE-375', isActive: true },
      { id: 'var_bp_750', productId: 'prod_blenders_pride_rare', name: '750 ml', volume: '750 ml', price: 880, mrp: 880, sku: 'BP-RARE-750', isActive: true },
    ],
  },
  {
    id: 'prod_imperial_blue',
    name: 'Imperial Blue Superior Grain Whisky',
    slug: 'imperial-blue-grain-whisky',
    brandId: 'b_imperialblue',
    brandName: 'Imperial Blue',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Whisky',
    price: 580,
    mrp: 580,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Seagram’s Imperial Blue exquisite blend of Indian grain spirits and imported Scotch malts.',
    tastingNotes: ['Smooth Grain', 'Toffee', 'Subtle Smoke'],
    imageUrl: '/images/products/whisky/imperial-blue-grain-whisky.webp',
    imageSource: 'https://www.pernod-ricard.com/en/brands/imperial-blue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.5,
    reviewCount: 76,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Retail Price Master',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_mcdowells_no1_reserve',
    name: "McDowell's No.1 Reserve Whisky",
    slug: 'mcdowells-no1-reserve-whisky',
    brandId: 'b_mcdowell',
    brandName: "McDowell's No.1",
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Whisky',
    price: 620,
    mrp: 620,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Iconic reserve whisky blended with Scotch malts for balanced richness.',
    tastingNotes: ['Warm Caramel', 'Toasted Oak'],
    imageUrl: '/images/products/whisky/mcdowells-no1-reserve-whisky.webp',
    imageSource: 'Diageo India Official Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.4,
    reviewCount: 65,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Retail Price Master',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_black_dog_gold',
    name: 'Black Dog Triple Gold Reserve Blended Scotch',
    slug: 'black-dog-triple-gold-reserve',
    brandId: 'b_blackdog',
    brandName: 'Black Dog',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Blended Scotch',
    price: 1850,
    mrp: 1850,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Triple wood matured blended Scotch whisky crafted by Scottish master blenders.',
    tastingNotes: ['Vanilla', 'Woody Oak', 'Mellow Malt'],
    imageUrl: '/images/products/whisky/black-dog-triple-gold-reserve.webp',
    imageSource: 'Diageo India Brand Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Scotland',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 88,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Delhi & UP Excise Retail Pricing Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_100_pipers_deluxe',
    name: '100 Pipers Deluxe Blended Scotch Whisky',
    slug: '100-pipers-deluxe-scotch',
    brandId: 'b_100pipers',
    brandName: '100 Pipers',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Blended Scotch',
    price: 1650,
    mrp: 1650,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Smooth blended Scotch whisky with smoky peat notes and rich oak character.',
    tastingNotes: ['Peat Smoke', 'Vanilla', 'Dried Fruits'],
    imageUrl: '/images/products/whisky/100-pipers-deluxe-scotch.webp',
    imageSource: 'Pernod Ricard India',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Scotland',
    rating: 4.7,
    reviewCount: 54,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_ballantines_finest',
    name: "Ballantine's Finest Blended Scotch Whisky",
    slug: 'ballantines-finest-scotch',
    brandId: 'b_ballantines',
    brandName: "Ballantine's",
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Blended Scotch',
    price: 1750,
    mrp: 1750,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Europe’s No. 1 Scotch whisky, blended with over 40 malt and grain whiskies.',
    tastingNotes: ['Heather Honey', 'Spicy Apple', 'Red Apple'],
    imageUrl: '/images/products/whisky/ballantines-finest-scotch.webp',
    imageSource: 'Pernod Ricard Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Scotland',
    rating: 4.8,
    reviewCount: 67,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_chivas_regal_12',
    name: 'Chivas Regal 12 Year Old Blended Scotch Whisky',
    slug: 'chivas-regal-12-yo',
    brandId: 'b_chivas',
    brandName: 'Chivas Regal',
    categoryId: 'cat_premium',
    categoryName: 'Premium / Imported',
    subcategory: 'Blended Scotch',
    price: 3200,
    mrp: 3200,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'A blend of the finest Strathisla single malts and Strathclyde grain whiskies aged for at least 12 years.',
    tastingNotes: ['Wild Herbs', 'Honey', 'Orchard Fruit'],
    imageUrl: '/images/products/alcohol/chivas-regal-12-yo.webp',
    imageSource: 'Chivas Brothers Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Scotland',
    isFeatured: true,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 110,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_jw_red_label',
    name: 'Johnnie Walker Red Label Blended Scotch Whisky',
    slug: 'johnnie-walker-red-label',
    brandId: 'b_johnniewalker',
    brandName: 'Johnnie Walker',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Blended Scotch',
    price: 1950,
    mrp: 1950,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'The world’s best-selling Scotch whisky with bold, vibrant spices and smoky finish.',
    tastingNotes: ['Cinnamon', 'Black Pepper', 'Fresh Pear', 'Smoky Malts'],
    imageUrl: '/images/products/whisky/johnnie-walker-red-label.webp',
    imageSource: 'Diageo Global Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Scotland',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 92,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_jw_black_label',
    name: 'Johnnie Walker Black Label 12 YO Blended Scotch',
    slug: 'johnnie-walker-black-label',
    brandId: 'b_johnniewalker',
    brandName: 'Johnnie Walker',
    categoryId: 'cat_premium',
    categoryName: 'Premium / Imported',
    subcategory: 'Blended Scotch',
    price: 3450,
    mrp: 3450,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'A true icon made of around 40 whiskies, each aged for a minimum of 12 years.',
    tastingNotes: ['Dark Fruit', 'Sweet Vanilla', 'Signature Smokiness'],
    imageUrl: '/images/products/alcohol/johnnie-walker-black-label.webp',
    imageSource: 'Diageo Global Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Scotland',
    isFeatured: true,
    isBestseller: true,
    rating: 4.9,
    reviewCount: 168,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_jameson_irish',
    name: 'Jameson Triple Distilled Irish Whiskey',
    slug: 'jameson-irish-whiskey',
    brandId: 'b_jameson',
    brandName: 'Jameson',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Irish Whiskey',
    price: 2400,
    mrp: 2400,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Triple-distilled Irish whiskey aged in seasoned oak casks for exceptional smoothness.',
    tastingNotes: ['Spicy Wood', 'Sweet Vanilla', 'Sherry Nut'],
    imageUrl: '/images/products/whisky/jameson-irish-whiskey.webp',
    imageSource: 'Irish Distillers Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Ireland',
    rating: 4.8,
    reviewCount: 77,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_jack_daniels_no7',
    name: "Jack Daniel's Old No. 7 Tennessee Whiskey",
    slug: 'jack-daniels-old-no-7',
    brandId: 'b_jackdaniels',
    brandName: "Jack Daniel's",
    categoryId: 'cat_premium',
    categoryName: 'Premium / Imported',
    subcategory: 'Bourbon',
    price: 3100,
    mrp: 3100,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Charcoal mellowed drop by drop through 10 feet of sugar maple charcoal.',
    tastingNotes: ['Caramel', 'Vanilla', 'Charred Oak'],
    imageUrl: '/images/products/alcohol/jack-daniels-old-no-7.webp',
    imageSource: 'Brown-Forman Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'United States',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 135,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_dewars_white_label',
    name: "Dewar's White Label Blended Scotch Whisky",
    slug: 'dewars-white-label-scotch',
    brandId: 'b_dewars',
    brandName: "Dewar's",
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Blended Scotch',
    price: 1700,
    mrp: 1700,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Double aged for extra smoothness, featuring honey, peach and oak character.',
    tastingNotes: ['Heather Honey', 'Pear', 'Oak Finish'],
    imageUrl: '/images/products/whisky/dewars-white-label-scotch.webp',
    imageSource: 'Bacardi Global Brands',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Scotland',
    rating: 4.6,
    reviewCount: 42,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_teachers_highland_cream',
    name: "Teacher's Highland Cream Blended Scotch Whisky",
    slug: 'teachers-highland-cream',
    brandId: 'b_teachers',
    brandName: "Teacher's",
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Blended Scotch',
    price: 1550,
    mrp: 1550,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'High peat malt content yielding deep amber colour and rich smoky flavor.',
    tastingNotes: ['Smoked Malt', 'Creamy Toffee', 'Malt Crisp'],
    imageUrl: '/images/products/whisky/teachers-highland-cream.webp',
    imageSource: 'Beam Suntory Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Scotland',
    rating: 4.6,
    reviewCount: 52,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_antiquity_blue',
    name: 'Antiquity Blue Ultra Premium Whisky',
    slug: 'antiquity-blue-whisky',
    brandId: 'b_antiquity',
    brandName: 'Antiquity',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Premium',
    price: 980,
    mrp: 980,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Distilled in copper pot stills and crafted with imported Scotch malts.',
    tastingNotes: ['Malty Smoke', 'Warm Wood'],
    imageUrl: '/images/products/whisky/antiquity-blue-whisky.webp',
    imageSource: 'Diageo India Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.5,
    reviewCount: 38,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_signature_rare',
    name: 'Signature Rare Aged Blended Whisky',
    slug: 'signature-rare-aged-whisky',
    brandId: 'b_signature',
    brandName: 'Signature',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Premium',
    price: 890,
    mrp: 890,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Masterfully crafted with aged Scotch malts and fine neutral spirits.',
    tastingNotes: ['Nutty Peat', 'Sweet Malt'],
    imageUrl: '/images/products/whisky/signature-rare-aged-whisky.webp',
    imageSource: 'Diageo India Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.5,
    reviewCount: 40,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_royal_challenge',
    name: 'Royal Challenge Finest Premium Whisky',
    slug: 'royal-challenge-premium-whisky',
    brandId: 'b_royalchallenge',
    brandName: 'Royal Challenge',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Whisky',
    price: 650,
    mrp: 650,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Deep golden grain whisky charcoal-filtered for crisp taste.',
    tastingNotes: ['Charcoal Crisp', 'Smooth Grain'],
    imageUrl: '/images/products/whisky/royal-challenge-premium-whisky.webp',
    imageSource: 'Diageo India Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.4,
    reviewCount: 50,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_rockford_reserve',
    name: 'Rockford Reserve Fine Blended Whisky',
    slug: 'rockford-reserve-whisky',
    brandId: 'b_rockford',
    brandName: 'Rockford Reserve',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Premium',
    price: 740,
    mrp: 740,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Charcoal-filtered fine blended whisky with deep golden amber character.',
    tastingNotes: ['Toasted Oak', 'Mellow Malt'],
    imageUrl: '/images/products/whisky/rockford-reserve-whisky.webp',
    imageSource: 'Modi Illva India',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.4,
    reviewCount: 31,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_officers_choice',
    name: "Officer's Choice Deluxe Whisky",
    slug: 'officers-choice-deluxe-whisky',
    brandId: 'b_officerschoice',
    brandName: "Officer's Choice",
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Whisky',
    price: 490,
    mrp: 490,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Allied Blenders’ flagship blended grain whisky.',
    tastingNotes: ['Light Grain', 'Warm Oak'],
    imageUrl: '/images/products/whisky/officers-choice-deluxe-whisky.webp',
    imageSource: 'ABD India Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.2,
    reviewCount: 45,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_sterling_reserve_b7',
    name: 'Sterling Reserve B7 Premium Blended Whisky',
    slug: 'sterling-reserve-b7-whisky',
    brandId: 'b_sterlingreserve',
    brandName: 'Sterling Reserve',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Premium',
    price: 760,
    mrp: 760,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Blended with imported Scotch malts and charcoal filtered for clarity.',
    tastingNotes: ['Nutty Sweetness', 'Peat Smoke'],
    imageUrl: '/images/products/whisky/sterling-reserve-b7-whisky.webp',
    imageSource: 'Allied Blenders Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.5,
    reviewCount: 39,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- BEER ---
  {
    id: 'prod_kingfisher_premium',
    name: 'Kingfisher Premium Lager Beer',
    slug: 'kingfisher-premium-lager',
    brandId: 'b_kingfisher',
    brandName: 'Kingfisher',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Lager',
    price: 140,
    mrp: 140,
    volume: '650 ml Bottle',
    alcoholByVolume: 4.8,
    isAlcoholic: true,
    description: 'India’s favorite crisp and refreshing lager beer brewed with finest Saaz hops.',
    tastingNotes: ['Malted Barley', 'Saaz Hops', 'Clean Crisp'],
    imageUrl: '/images/products/beer/kingfisher-premium.webp',
    imageSource: 'United Breweries Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 220,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'UP State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
    variants: [
      { id: 'var_kf_330', productId: 'prod_kingfisher_premium', name: '330 ml Can', volume: '330 ml Can', price: 90, mrp: 90, sku: 'KF-PREM-330C', isActive: true },
      { id: 'var_kf_500', productId: 'prod_kingfisher_premium', name: '500 ml Can', volume: '500 ml Can', price: 120, mrp: 120, sku: 'KF-PREM-500C', isActive: true },
      { id: 'var_kf_650', productId: 'prod_kingfisher_premium', name: '650 ml Bottle', volume: '650 ml Bottle', price: 140, mrp: 140, sku: 'KF-PREM-650B', isActive: true },
    ],
  },
  {
    id: 'prod_kingfisher_strong',
    name: 'Kingfisher Strong Premium Beer',
    slug: 'kingfisher-strong-beer',
    brandId: 'b_kingfisher',
    brandName: 'Kingfisher',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Strong Beer',
    price: 150,
    mrp: 150,
    volume: '650 ml Bottle',
    alcoholByVolume: 7.2,
    isAlcoholic: true,
    description: 'Rich, full-bodied strong Indian lager brewed for maximum punch and crispness.',
    tastingNotes: ['Full Malt', 'Robust Bitter Hop'],
    imageUrl: '/images/products/beer/kingfisher-strong-beer.webp',
    imageSource: 'United Breweries Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.6,
    reviewCount: 180,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'UP State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_budweiser_premium',
    name: 'Budweiser Premium King of Beers',
    slug: 'budweiser-premium-lager',
    brandId: 'b_budweiser',
    brandName: 'Budweiser',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Lager',
    price: 190,
    mrp: 190,
    volume: '650 ml Bottle',
    alcoholByVolume: 5.0,
    isAlcoholic: true,
    description: 'Beechwood aged American style lager with smooth clean finish.',
    tastingNotes: ['Crisp Rice', 'Mild Barley', 'Gentle Hops'],
    imageUrl: '/images/products/beer/budweiser-premium-lager.webp',
    imageSource: 'AB InBev India Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'United States',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 195,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_budweiser_magnum',
    name: 'Budweiser Magnum Strong Beer',
    slug: 'budweiser-magnum-strong',
    brandId: 'b_budweiser',
    brandName: 'Budweiser',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Strong Beer',
    price: 210,
    mrp: 210,
    volume: '650 ml Bottle',
    alcoholByVolume: 6.5,
    isAlcoholic: true,
    description: 'Super-premium strong beer aged on beechwood chips for deep golden flavor.',
    tastingNotes: ['Malt Sweetness', 'Warm Alcohol Kick'],
    imageUrl: '/images/products/beer/budweiser-magnum-strong.webp',
    imageSource: 'AB InBev India Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'United States',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 210,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_heineken_silver',
    name: 'Heineken Silver Mild Lager Beer',
    slug: 'heineken-silver-lager',
    brandId: 'b_heineken',
    brandName: 'Heineken',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Lager',
    price: 220,
    mrp: 220,
    volume: '650 ml Bottle',
    alcoholByVolume: 5.0,
    isAlcoholic: true,
    description: 'Brewed at -1°C for crisp refreshing drinkability and low bitterness.',
    tastingNotes: ['Pure Malt', 'Fruity Yeast', 'Extra Crisp'],
    imageUrl: '/images/products/beer/heineken-silver-lager.webp',
    imageSource: 'Heineken Global Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Netherlands',
    rating: 4.7,
    reviewCount: 115,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_corona_extra',
    name: 'Corona Extra Imported Beer',
    slug: 'corona-extra-bottle',
    brandId: 'b_corona',
    brandName: 'Corona Extra',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Imported Beer',
    price: 240,
    mrp: 240,
    volume: '330 ml Bottle',
    alcoholByVolume: 4.5,
    isAlcoholic: true,
    description: 'Mexico’s classic sun-drenched pale lager, best served ice-cold with a wedge of lime.',
    tastingNotes: ['Faint Citrus', 'Crisp Corn', 'Clean Water Finish'],
    imageUrl: '/images/products/beer/corona-extra-330ml.webp',
    imageSource: 'Grupo Modelo / AB InBev',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Mexico',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 140,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_carlsberg_smooth',
    name: 'Carlsberg Smooth Premium Lager',
    slug: 'carlsberg-smooth-lager',
    brandId: 'b_carlsberg',
    brandName: 'Carlsberg',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Lager',
    price: 180,
    mrp: 180,
    volume: '650 ml Bottle',
    alcoholByVolume: 5.0,
    isAlcoholic: true,
    description: 'Danish all-malt pilsner double hopped for unique smoothness.',
    tastingNotes: ['Floral Hops', 'Golden Malt', 'Smooth Body'],
    imageUrl: '/images/products/beer/carlsberg-smooth-lager.webp',
    imageSource: 'Carlsberg India Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Denmark',
    rating: 4.6,
    reviewCount: 88,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_carlsberg_elephant',
    name: 'Carlsberg Elephant Strong Beer',
    slug: 'carlsberg-elephant-strong',
    brandId: 'b_carlsberg',
    brandName: 'Carlsberg',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Strong Beer',
    price: 195,
    mrp: 195,
    volume: '650 ml Bottle',
    alcoholByVolume: 7.2,
    isAlcoholic: true,
    description: 'Legendary full-bodied strong beer with rich European malt depth.',
    tastingNotes: ['Heavy Malt', 'Caramel Grain', 'Warm Bite'],
    imageUrl: '/images/products/beer/carlsberg-elephant-strong.webp',
    imageSource: 'Carlsberg India Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Denmark',
    rating: 4.7,
    reviewCount: 95,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_bira91_blonde',
    name: 'Bira 91 Blonde Summer Craft Lager',
    slug: 'bira-91-blonde-craft-lager',
    brandId: 'b_bira91',
    brandName: 'Bira 91',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Lager',
    price: 165,
    mrp: 165,
    volume: '500 ml Can',
    alcoholByVolume: 4.5,
    isAlcoholic: true,
    description: 'Sparkling golden craft lager with pleasant citrus hop notes.',
    tastingNotes: ['Summer Citrus', 'Golden Malt'],
    imageUrl: '/images/products/beer/bira-91-blonde-craft-lager.webp',
    imageSource: 'Bira 91 Craft Brewery',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 130,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_bira91_white',
    name: 'Bira 91 White Craft Wheat Beer',
    slug: 'bira-91-white-wheat-beer',
    brandId: 'b_bira91',
    brandName: 'Bira 91',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Craft Wheat',
    price: 185,
    mrp: 185,
    volume: '500 ml Can',
    alcoholByVolume: 4.7,
    isAlcoholic: true,
    description: 'Hazy Belgian style wheat beer brewed with coriander seeds and orange peel.',
    tastingNotes: ['Coriander Spice', 'Orange Peel', 'Wheat Haze'],
    imageUrl: '/images/products/beer/bira-91-white-wheat-beer.webp',
    imageSource: 'Bira 91 Craft Brewery',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 175,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_bira91_boom',
    name: 'Bira 91 Boom Super Strong Beer',
    slug: 'bira-91-boom-strong',
    brandId: 'b_bira91',
    brandName: 'Bira 91',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Strong Beer',
    price: 160,
    mrp: 160,
    volume: '650 ml Bottle',
    alcoholByVolume: 7.0,
    isAlcoholic: true,
    description: 'Crisp strong craft brew with rich malt body and punchy hop bitterness.',
    tastingNotes: ['Rich Barley', 'Solid Hop'],
    imageUrl: '/images/products/beer/bira-91-boom-strong.webp',
    imageSource: 'Bira 91 Craft Brewery',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.5,
    reviewCount: 65,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_tuborg_green',
    name: 'Tuborg Green Premium Quality Beer',
    slug: 'tuborg-green-lager',
    brandId: 'b_tuborg',
    brandName: 'Tuborg',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Lager',
    price: 160,
    mrp: 160,
    volume: '650 ml Bottle',
    alcoholByVolume: 4.8,
    isAlcoholic: true,
    description: 'Crisp European lager with easy-to-pull ring tab and thirst quenching taste.',
    tastingNotes: ['Mild Hop', 'Light Corn Malt'],
    imageUrl: '/images/products/beer/tuborg-green-lager.webp',
    imageSource: 'Carlsberg Tuborg Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Denmark',
    rating: 4.6,
    reviewCount: 78,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_fosters_lager',
    name: "Foster's Premium Lager Beer",
    slug: 'fosters-premium-lager',
    brandId: 'b_fosters',
    brandName: "Foster's",
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Lager',
    price: 150,
    mrp: 150,
    volume: '650 ml Bottle',
    alcoholByVolume: 4.8,
    isAlcoholic: true,
    description: 'Australian original full-flavored lager brewed with Pride of Ringwood hops.',
    tastingNotes: ['Pride of Ringwood Hops', 'Clean Grain'],
    imageUrl: '/images/products/beer/fosters-premium-lager.webp',
    imageSource: 'Foster’s Global Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Australia',
    rating: 4.5,
    reviewCount: 42,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_miller_high_life',
    name: 'Miller High Life Premium Beer',
    slug: 'miller-high-life',
    brandId: 'b_miller',
    brandName: 'Miller',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Lager',
    price: 175,
    mrp: 175,
    volume: '650 ml Bottle',
    alcoholByVolume: 4.8,
    isAlcoholic: true,
    description: 'The Champagne of Beers; pure refreshing effervescence with crystal clarity.',
    tastingNotes: ['Effervescent Bubble', 'Light Malt Crisp'],
    imageUrl: '/images/products/beer/miller-high-life.webp',
    imageSource: 'Molson Coors Global',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'United States',
    rating: 4.5,
    reviewCount: 36,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_hoegaarden_witbier',
    name: 'Hoegaarden Belgian Witbier',
    slug: 'hoegaarden-belgian-witbier',
    brandId: 'b_hoegaarden',
    brandName: 'Hoegaarden',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Imported Beer',
    price: 280,
    mrp: 280,
    volume: '330 ml Bottle',
    alcoholByVolume: 4.9,
    isAlcoholic: true,
    description: 'Unfiltered authentic Belgian white beer infused with Curaçao orange peel and coriander.',
    tastingNotes: ['Curaçao Orange', 'Coriander Spice', 'Unfiltered Creaminess'],
    imageUrl: '/images/products/beer/hoegaarden-belgian-witbier.webp',
    imageSource: 'Hoegaarden Brewery Belgium',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Belgium',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 95,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_asahi_super_dry',
    name: 'Asahi Super Dry Japanese Beer',
    slug: 'asahi-super-dry',
    brandId: 'b_asahi',
    brandName: 'Asahi',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Imported Beer',
    price: 290,
    mrp: 290,
    volume: '330 ml Can',
    alcoholByVolume: 5.0,
    isAlcoholic: true,
    description: 'Japan’s premier Karakuchi dry beer with super quick, clean and crisp palate.',
    tastingNotes: ['Ultra Dry', 'Clean Yeast', 'Fast Refreshing Finish'],
    imageUrl: '/images/products/beer/asahi-super-dry.webp',
    imageSource: 'Asahi Breweries Japan',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Japan',
    rating: 4.8,
    reviewCount: 68,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- VODKA ---
  {
    id: 'prod_smirnoff_triple',
    name: 'Smirnoff Triple Distilled Vodka',
    slug: 'smirnoff-triple-distilled',
    brandId: 'b_smirnoff',
    brandName: 'Smirnoff',
    categoryId: 'cat_vodka',
    categoryName: 'Vodka',
    subcategory: 'Grain Vodka',
    price: 920,
    mrp: 920,
    volume: '750 ml',
    alcoholByVolume: 37.5,
    isAlcoholic: true,
    description: 'Triple distilled and 10 times filtered through charcoal for purity.',
    tastingNotes: ['Neutral Spirit', 'Clean Charcoal', 'Subtle Pepper'],
    imageUrl: '/images/products/vodka/smirnoff-triple-distilled.webp',
    imageSource: 'Diageo India Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'United Kingdom',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 104,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_absolut_vodka',
    name: 'Absolut Swedish Pure Vodka',
    slug: 'absolut-swedish-vodka',
    brandId: 'b_absolut',
    brandName: 'Absolut',
    categoryId: 'cat_vodka',
    categoryName: 'Vodka',
    subcategory: 'Grain Vodka',
    price: 2100,
    mrp: 2100,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Crafted exclusively from winter wheat in Åhus, Sweden with zero added sugar.',
    tastingNotes: ['Winter Wheat', 'Dried Fruit', 'Smooth Grain'],
    imageUrl: '/images/products/vodka/absolut-swedish-vodka.webp',
    imageSource: 'Pernod Ricard Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Sweden',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 92,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_magic_moments',
    name: 'Magic Moments Grain Vodka',
    slug: 'magic-moments-vodka',
    brandId: 'b_magicmoments',
    brandName: 'Magic Moments',
    categoryId: 'cat_vodka',
    categoryName: 'Vodka',
    subcategory: 'Grain Vodka',
    price: 650,
    mrp: 650,
    volume: '750 ml',
    alcoholByVolume: 37.5,
    isAlcoholic: true,
    description: 'Triple-distilled pure grain spirit from Radico Khaitan.',
    tastingNotes: ['Clean Spirit', 'Light Pepper'],
    imageUrl: '/images/products/vodka/magic-moments-vodka.webp',
    imageSource: 'Radico Khaitan Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.5,
    reviewCount: 112,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_grey_goose',
    name: 'Grey Goose French Luxury Vodka',
    slug: 'grey-goose-vodka',
    brandId: 'b_greygoose',
    brandName: 'Grey Goose',
    categoryId: 'cat_premium',
    categoryName: 'Premium / Imported',
    subcategory: 'Luxury Vodka',
    price: 4100,
    mrp: 4100,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Distilled once using continuous column distillation in Picardy, France with Gensac spring water.',
    tastingNotes: ['French Winter Wheat', 'Delicate Floral', 'Silky Citrus'],
    imageUrl: '/images/products/alcohol/grey-goose-vodka.webp',
    imageSource: 'Bacardi Global Brands',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'France',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 84,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- RUM ---
  {
    id: 'prod_old_monk_xxx',
    name: 'Old Monk XXX Very Old Vatted Rum',
    slug: 'old-monk-xxx-rum',
    brandId: 'b_oldmonk',
    brandName: 'Old Monk',
    categoryId: 'cat_rum',
    categoryName: 'Rum',
    subcategory: 'Dark Rum',
    price: 520,
    mrp: 520,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Iconic dark Indian vatted rum blended and aged in oak vats for 7 years in Mohan Meakin.',
    tastingNotes: ['Vanilla', 'Molasses', 'Caramel', 'Sweet Spice'],
    imageUrl: '/images/products/rum/old-monk-xxx-rum.webp',
    imageSource: 'Mohan Meakin Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 310,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'UP State Excise Approved MRP',
    priceVerifiedAt: VERIFIED_AT,
    variants: [
      { id: 'var_om_180', productId: 'prod_old_monk_xxx', name: '180 ml', volume: '180 ml', price: 130, mrp: 130, sku: 'OM-XXX-180', isActive: true },
      { id: 'var_om_375', productId: 'prod_old_monk_xxx', name: '375 ml', volume: '375 ml', price: 260, mrp: 260, sku: 'OM-XXX-375', isActive: true },
      { id: 'var_om_750', productId: 'prod_old_monk_xxx', name: '750 ml', volume: '750 ml', price: 520, mrp: 520, sku: 'OM-XXX-750', isActive: true },
    ],
  },
  {
    id: 'prod_bacardi_white',
    name: 'Bacardi Carta Blanca Superior White Rum',
    slug: 'bacardi-carta-blanca-white-rum',
    brandId: 'b_bacardi',
    brandName: 'Bacardi',
    categoryId: 'cat_rum',
    categoryName: 'Rum',
    subcategory: 'White Rum',
    price: 950,
    mrp: 950,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Aged in white oak barrels and shaped through a secret blend of charcoal.',
    tastingNotes: ['Almond', 'Vanilla', 'Floral Fruit'],
    imageUrl: '/images/products/rum/bacardi-carta-blanca-white-rum.webp',
    imageSource: 'Bacardi Global Brands',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Puerto Rico',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 88,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_captain_morgan_spiced',
    name: 'Captain Morgan Original Spiced Gold Rum',
    slug: 'captain-morgan-spiced-gold',
    brandId: 'b_captainmorgan',
    brandName: 'Captain Morgan',
    categoryId: 'cat_rum',
    categoryName: 'Rum',
    subcategory: 'Spiced Gold Rum',
    price: 890,
    mrp: 890,
    volume: '750 ml',
    alcoholByVolume: 35.0,
    isAlcoholic: true,
    description: 'Caribbean rum blended with mellow spices and natural vanilla flavor.',
    tastingNotes: ['Warm Spice', 'Rich Vanilla', 'Brown Sugar'],
    imageUrl: '/images/products/rum/captain-morgan-spiced-gold.webp',
    imageSource: 'Diageo India Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Jamaica',
    rating: 4.7,
    reviewCount: 65,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- GIN ---
  {
    id: 'prod_bombay_sapphire',
    name: 'Bombay Sapphire London Dry Gin',
    slug: 'bombay-sapphire-gin',
    brandId: 'b_bombaysapphire',
    brandName: 'Bombay Sapphire',
    categoryId: 'cat_gin',
    categoryName: 'Gin',
    subcategory: 'London Dry',
    price: 2350,
    mrp: 2350,
    volume: '750 ml',
    alcoholByVolume: 47.0,
    isAlcoholic: true,
    description: 'Infused with 10 hand-selected exotic botanicals vapor-distilled in Carter-Head stills.',
    tastingNotes: ['Juniper', 'Lemon Peel', 'Coriander', 'Grains of Paradise'],
    imageUrl: '/images/products/gin/bombay-sapphire-gin.webp',
    imageSource: 'Bacardi Bombay Sapphire Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'United Kingdom',
    isBestseller: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 140,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_gordons_gin',
    name: "Gordon's London Dry Gin",
    slug: 'gordons-london-dry-gin',
    brandId: 'b_gordons',
    brandName: "Gordon's",
    categoryId: 'cat_gin',
    categoryName: 'Gin',
    subcategory: 'London Dry',
    price: 1650,
    mrp: 1650,
    volume: '750 ml',
    alcoholByVolume: 37.5,
    isAlcoholic: true,
    description: 'World’s favorite classic gin crafted to Alexander Gordon’s 1769 original recipe.',
    tastingNotes: ['Wild Juniper', 'Coriander Seed', 'Angelica Root'],
    imageUrl: '/images/products/gin/gordons-london-dry-gin.webp',
    imageSource: 'Diageo Official Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'United Kingdom',
    rating: 4.7,
    reviewCount: 78,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_greater_than_gin',
    name: 'Greater Than London Dry Craft Gin',
    slug: 'greater-than-craft-gin',
    brandId: 'b_greaterthan',
    brandName: 'Greater Than',
    categoryId: 'cat_gin',
    categoryName: 'Gin',
    subcategory: 'Craft Botanical',
    price: 1150,
    mrp: 1150,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'India’s first craft gin distilled in copper pot stills with juniper, ginger and citrus.',
    tastingNotes: ['Fennel', 'Ginger', 'Lemon Peel', 'Juniper'],
    imageUrl: '/images/products/gin/greater-than-craft-gin.webp',
    imageSource: 'NAO Spirits India',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 95,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_hendricks_gin',
    name: "Hendrick's Curiously Small Batch Gin",
    slug: 'hendricks-curious-gin',
    brandId: 'b_hendricks',
    brandName: "Hendrick's",
    categoryId: 'cat_premium',
    categoryName: 'Premium / Imported',
    subcategory: 'Craft Botanical',
    price: 4300,
    mrp: 4300,
    volume: '750 ml',
    alcoholByVolume: 41.4,
    isAlcoholic: true,
    description: 'Handcrafted in Ayrshire, Scotland with peculiar infusions of rose petals and cucumber.',
    tastingNotes: ['Bulgarian Rose', 'English Cucumber', 'Eleven Botanicals'],
    imageUrl: '/images/products/alcohol/hendricks-curious-gin.webp',
    imageSource: 'William Grant & Sons',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Scotland',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 88,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- WINE ---
  {
    id: 'prod_sula_shiraz_cabernet',
    name: 'Sula Shiraz Cabernet Red Wine',
    slug: 'sula-shiraz-cabernet',
    brandId: 'b_sula',
    brandName: 'Sula Vineyards',
    categoryId: 'cat_wine',
    categoryName: 'Wine',
    subcategory: 'Red Wine',
    price: 895,
    mrp: 895,
    volume: '750 ml',
    alcoholByVolume: 13.5,
    isAlcoholic: true,
    description: 'Medium-bodied red wine accented with ripe cherries, plums and black pepper spice.',
    tastingNotes: ['Black Pepper', 'Mocha', 'Ripe Plum'],
    imageUrl: '/images/products/wine/sula-shiraz-cabernet.webp',
    imageSource: 'Sula Vineyards Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 105,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'UP & Delhi Wine Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_sula_chenin_blanc',
    name: 'Sula Chenin Blanc White Wine',
    slug: 'sula-chenin-blanc',
    brandId: 'b_sula',
    brandName: 'Sula Vineyards',
    categoryId: 'cat_wine',
    categoryName: 'Wine',
    subcategory: 'White Wine',
    price: 795,
    mrp: 795,
    volume: '750 ml',
    alcoholByVolume: 12.0,
    isAlcoholic: true,
    description: 'Semi-dry crisp white wine with aromatic pineapple, passion fruit and clean acidity.',
    tastingNotes: ['Pineapple', 'Passion Fruit', 'Crisp Honey'],
    imageUrl: '/images/products/wine/sula-chenin-blanc.webp',
    imageSource: 'Sula Vineyards Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.6,
    reviewCount: 62,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'UP & Delhi Wine Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_jacobs_creek_shiraz',
    name: "Jacob's Creek Shiraz Cabernet Red Wine",
    slug: 'jacobs-creek-shiraz-cabernet',
    brandId: 'b_jacobscreek',
    brandName: "Jacob's Creek",
    categoryId: 'cat_wine',
    categoryName: 'Wine',
    subcategory: 'Red Wine',
    price: 1450,
    mrp: 1450,
    volume: '750 ml',
    alcoholByVolume: 13.9,
    isAlcoholic: true,
    description: 'Australian full-bodied red wine displaying ripe berry fruit flavors with spicy oak.',
    tastingNotes: ['Plum Berry', 'Spiced Oak', 'Soft Tannins'],
    imageUrl: '/images/products/wine/jacobs-creek-shiraz-cabernet.webp',
    imageSource: 'Pernod Ricard Winemakers',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Australia',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 88,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- BRANDY & TEQUILA & SPARKLING ---
  {
    id: 'prod_mansion_house_brandy',
    name: 'Mansion House French Pure Grape Brandy',
    slug: 'mansion-house-brandy',
    brandId: 'b_mansionhouse',
    brandName: 'Mansion House',
    categoryId: 'cat_brandy',
    categoryName: 'Brandy',
    subcategory: 'Indian Grape Brandy',
    price: 750,
    mrp: 750,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Warm blended French grape brandy aged in oak casks.',
    tastingNotes: ['Oak Wood', 'Sweet Grape'],
    imageUrl: '/images/products/brandy/mansion-house-brandy.webp',
    imageSource: 'Tilaknagar Industries',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.5,
    reviewCount: 52,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_jose_cuervo_reposado',
    name: 'Jose Cuervo Especial Reposado Tequila',
    slug: 'jose-cuervo-reposado-tequila',
    brandId: 'b_josecuervo',
    brandName: 'Jose Cuervo',
    categoryId: 'cat_tequila',
    categoryName: 'Tequila',
    subcategory: 'Reposado',
    price: 3200,
    mrp: 3200,
    volume: '750 ml',
    alcoholByVolume: 38.0,
    isAlcoholic: true,
    description: 'Golden blend of reposado and younger tequilas rested in oak casks.',
    tastingNotes: ['Agave', 'Oak Vanilla', 'Warm Spice'],
    imageUrl: '/images/products/tequila/jose-cuervo-reposado-tequila.webp',
    imageSource: 'Proximo Spirits Official',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Mexico',
    rating: 4.7,
    reviewCount: 71,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_chandon_brut',
    name: 'Chandon Brut Sparkling Wine',
    slug: 'chandon-brut-sparkling',
    brandId: 'b_chandon',
    brandName: 'Chandon',
    categoryId: 'cat_sparkling',
    categoryName: 'Sparkling Wine',
    subcategory: 'Sparkling Brut',
    price: 2100,
    mrp: 2100,
    volume: '750 ml',
    alcoholByVolume: 12.5,
    isAlcoholic: true,
    description: 'Méthode Traditionnelle sparkling wine with crisp citrus and toasted brioche notes.',
    tastingNotes: ['Green Apple', 'Brioche', 'Citrus Zest'],
    imageUrl: '/images/products/wine/chandon-brut-sparkling.webp',
    imageSource: 'Moët Hennessy India',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isFeatured: true,
    rating: 4.8,
    reviewCount: 84,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_moet_imperial_brut',
    name: 'Moët & Chandon Impérial Brut Champagne',
    slug: 'moet-chandon-imperial-brut',
    brandId: 'b_moetchandon',
    brandName: 'Moët & Chandon',
    categoryId: 'cat_premium',
    categoryName: 'Premium / Imported',
    subcategory: 'Champagne',
    price: 8200,
    mrp: 8200,
    volume: '750 ml',
    alcoholByVolume: 12.0,
    isAlcoholic: true,
    description: 'The world’s most loved Champagne created in 1869 in Épernay, France.',
    tastingNotes: ['Crisp Pear', 'White Peach', 'Toasted Brioche'],
    imageUrl: '/images/products/alcohol/moet-chandon-imperial-brut.webp',
    imageSource: 'Moët Hennessy Global',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'France',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 92,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'State Excise Schedule',
    priceVerifiedAt: VERIFIED_AT,
  }
];
