import { Product } from '../types.ts';

const VERIFIED_AT = '2026-09-26';

export const SEED_PRODUCTS: Product[] = [
  {
    id: 'prod_royal_stag_deluxe',
    name: 'Royal Stag Deluxe Whisky',
    slug: 'royal-stag-deluxe-whisky',
    brandId: 'b_royalstag',
    brandName: 'Royal Stag',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Whisky',
    price: 675,
    mrp: 675,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Royal Stag Deluxe blended Indian whisky.',
    tastingNotes: ['Malt', 'Oak', 'Warm finish'],
    imageUrl: 'https://www.bswliquor.com/cdn/shop/products/royal_stag_deluxe.png?v=1753126462&width=2400',
    imageSource: 'https://www.bswliquor.com/products/royal-stag-deluxe',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    isFeatured: true,
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Uttar Pradesh'],
    priceVerified: true,
    priceSource: 'https://www.likar.app/liquor-price-list/uttar-pradesh',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'Uttar Pradesh', state: 'Uttar Pradesh', price: 675, mrp: 675, currency: 'INR', source: 'https://www.likar.app/liquor-price-list/uttar-pradesh', sourceType: 'secondary_aggregator', verified: true, verifiedAt: VERIFIED_AT }],
    variants: [
      { id: 'var_rs_180', productId: 'prod_royal_stag_deluxe', name: '180 ml', volume: '180 ml', price: 165, mrp: 165, sku: 'RS-DELUXE-180-UP', isActive: true },
      { id: 'var_rs_375', productId: 'prod_royal_stag_deluxe', name: '375 ml', volume: '375 ml', price: 340, mrp: 340, sku: 'RS-DELUXE-375-UP', isActive: true },
      { id: 'var_rs_750', productId: 'prod_royal_stag_deluxe', name: '750 ml', volume: '750 ml', price: 675, mrp: 675, sku: 'RS-DELUXE-750-UP', isActive: true },
    ],
  },
  {
    id: 'prod_blenders_pride_rare',
    name: 'Blenders Pride Rare Premium Whisky',
    slug: 'blenders-pride-rare-premium-whisky',
    brandId: 'b_blenderspride',
    brandName: 'Blenders Pride',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Premium',
    price: 880,
    mrp: 880,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Blenders Pride Rare Premium blended whisky.',
    tastingNotes: ['Honey', 'Oak', 'Fruit'],
    imageUrl: 'https://www.bswliquor.com/cdn/shop/files/blenders-pride.png?v=1753126605&width=1400',
    imageSource: 'https://www.bswliquor.com/products/blenders-pride-rare-premium',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    isFeatured: true,
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Uttar Pradesh'],
    priceVerified: true,
    priceSource: 'https://www.likar.app/liquor-price-list/uttar-pradesh',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'Uttar Pradesh', state: 'Uttar Pradesh', price: 880, mrp: 880, currency: 'INR', source: 'https://www.likar.app/liquor-price-list/uttar-pradesh', sourceType: 'secondary_aggregator', verified: true, verifiedAt: VERIFIED_AT }],
    variants: [
      { id: 'var_bp_180', productId: 'prod_blenders_pride_rare', name: '180 ml', volume: '180 ml', price: 215, mrp: 215, sku: 'BP-RARE-180-UP', isActive: true },
      { id: 'var_bp_375', productId: 'prod_blenders_pride_rare', name: '375 ml', volume: '375 ml', price: 445, mrp: 445, sku: 'BP-RARE-375-UP', isActive: true },
      { id: 'var_bp_750', productId: 'prod_blenders_pride_rare', name: '750 ml', volume: '750 ml', price: 880, mrp: 880, sku: 'BP-RARE-750-UP', isActive: true },
    ],
  },
  {
    id: 'prod_imperial_blue',
    name: 'Imperial Blue Superior Grain Whisky',
    slug: 'imperial-blue-superior-grain-whisky',
    brandId: 'b_imperialblue',
    brandName: 'Imperial Blue',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Grain',
    price: 615,
    mrp: 615,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Imperial Blue Superior Grain Whisky.',
    tastingNotes: ['Grain', 'Caramel', 'Oak'],
    imageUrl: 'https://www.365drinks.co.uk/cdn/shop/products/imperial-blue-superior-grain-whisky-75cl-425_1024x1024.jpg?v=1650037568',
    imageSource: 'https://www.365drinks.co.uk/products/imperial-blue-superior-grain-whisky-75cl',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Uttar Pradesh'],
    priceVerified: true,
    priceSource: 'https://www.likar.app/liquor-price-list/uttar-pradesh',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'Uttar Pradesh', state: 'Uttar Pradesh', price: 615, mrp: 615, currency: 'INR', source: 'https://www.likar.app/liquor-price-list/uttar-pradesh', sourceType: 'secondary_aggregator', verified: true, verifiedAt: VERIFIED_AT }],
    variants: [
      { id: 'var_ib_180', productId: 'prod_imperial_blue', name: '180 ml', volume: '180 ml', price: 150, mrp: 150, sku: 'IB-180-UP', isActive: true },
      { id: 'var_ib_375', productId: 'prod_imperial_blue', name: '375 ml', volume: '375 ml', price: 310, mrp: 310, sku: 'IB-375-UP', isActive: true },
      { id: 'var_ib_750', productId: 'prod_imperial_blue', name: '750 ml', volume: '750 ml', price: 615, mrp: 615, sku: 'IB-750-UP', isActive: true },
    ],
  },
  {
    id: 'prod_mcdowells_no1',
    name: "McDowell's No.1 Whisky",
    slug: 'mcdowells-no1-whisky',
    brandId: 'b_mcdowell',
    brandName: "McDowell's No.1",
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Whisky',
    price: 620,
    mrp: 620,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: "McDowell's No.1 blended Indian whisky.",
    tastingNotes: ['Vanilla', 'Malt', 'Oak'],
    imageUrl: "https://commons.wikimedia.org/wiki/Special:Redirect/file/McDowell's_No.1,_Indian_whisky.jpg",
    imageSource: 'https://commons.wikimedia.org/wiki/File:McDowell%27s_No.1,_Indian_whisky.jpg',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Uttar Pradesh'],
    priceVerified: true,
    priceSource: 'https://www.livcheers.com/lucknow/liquor/mc-dowells-no-1-750ml',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'Lucknow', state: 'Uttar Pradesh', price: 620, mrp: 620, currency: 'INR', source: 'https://www.livcheers.com/lucknow/liquor/mc-dowells-no-1-750ml', sourceType: 'secondary_aggregator', verified: true, verifiedAt: VERIFIED_AT }],
    variants: [{ id: 'var_mcd_750', productId: 'prod_mcdowells_no1', name: '750 ml', volume: '750 ml', price: 620, mrp: 620, sku: 'MCD-NO1-750-UP', isActive: true }],
  },
  {
    id: 'prod_black_dog_triple_gold',
    name: 'Black Dog Triple Gold Reserve',
    slug: 'black-dog-triple-gold-reserve',
    brandId: 'b_blackdog',
    brandName: 'Black Dog',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Blended Scotch',
    price: 2190,
    mrp: 2190,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Black Dog Triple Gold Reserve blended Scotch whisky.',
    tastingNotes: ['Honey', 'Vanilla', 'Oak'],
    imageUrl: 'https://www.drinqs.in/admin/product_images/Black-Dog-Triple-Gold-Reserve_product_id_52_.png',
    imageSource: 'https://www.drinqs.in/product_details.php?product_id=BLACK+DOG+TRIPLE+GOLD+RESERVE+SCOTCH+WHISKY',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Scotland',
    isFeatured: true,
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Delhi'],
    priceVerified: true,
    priceSource: 'https://www.livcheers.com/delhi/liquor/black-dog-gold-reserve-750ml',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'Delhi', state: 'Delhi', price: 2190, mrp: 2190, currency: 'INR', source: 'https://www.livcheers.com/delhi/liquor/black-dog-gold-reserve-750ml', sourceType: 'secondary_aggregator', verified: true, verifiedAt: VERIFIED_AT }],
    variants: [{ id: 'var_bdg_750', productId: 'prod_black_dog_triple_gold', name: '750 ml', volume: '750 ml', price: 2190, mrp: 2190, sku: 'BD-TGR-750-DL', isActive: true }],
  },
  {
    id: 'prod_kingfisher_premium',
    name: 'Kingfisher Premium Lager Beer',
    slug: 'kingfisher-premium-lager-beer',
    brandId: 'b_kingfisher',
    brandName: 'Kingfisher',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Lager',
    price: 100,
    mrp: 100,
    volume: '650 ml',
    alcoholByVolume: 5,
    isAlcoholic: true,
    description: 'Kingfisher Premium Lager Beer, 650 ml bottle.',
    tastingNotes: ['Crisp malt', 'Light hops', 'Clean finish'],
    imageUrl: 'https://sipdirect-prod1.s3.ap-south-1.amazonaws.com/images/Category-Images2/Beer/Lager/Kingfisher-Premium-Lager-Beer-650mL_front.webp',
    imageSource: 'https://sipdirect.com/products/kingfisher-premium-lager-beer',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    isFeatured: true,
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Delhi'],
    priceVerified: true,
    priceSource: 'https://www.likar.app/liquor-price-list/delhi',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'Delhi', state: 'Delhi', price: 100, mrp: 100, currency: 'INR', source: 'https://www.likar.app/liquor-price-list/delhi', sourceType: 'secondary_aggregator', verified: true, verifiedAt: VERIFIED_AT }],
    variants: [
      { id: 'var_kf_500', productId: 'prod_kingfisher_premium', name: '500 ml Can', volume: '500 ml', price: 80, mrp: 80, sku: 'KF-PREMIUM-500-DL', isActive: true },
      { id: 'var_kf_650', productId: 'prod_kingfisher_premium', name: '650 ml Bottle', volume: '650 ml', price: 100, mrp: 100, sku: 'KF-PREMIUM-650-DL', isActive: true },
    ],
  },
  {
    id: 'prod_budweiser_magnum',
    name: 'Budweiser Magnum Beer',
    slug: 'budweiser-magnum-beer',
    brandId: 'b_budweiser',
    brandName: 'Budweiser',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Strong Lager',
    price: 140,
    mrp: 140,
    volume: '650 ml',
    alcoholByVolume: 6.5,
    isAlcoholic: true,
    description: 'Budweiser Magnum strong lager beer.',
    tastingNotes: ['Malt', 'Crisp', 'Smooth finish'],
    imageUrl: 'https://assets.gqindia.com/photos/5f32b0f26cf9e46d5f0f52a6/master/w_1600%2Cc_limit/Budweiser-Magnum-Strong.jpg',
    imageSource: 'https://www.gqindia.com/live-well/content/8-best-beers-under-rs-300-that-are-worth-the-hype-in-2020',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'United States',
    isBestseller: true,
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Delhi'],
    priceVerified: true,
    priceSource: 'https://www.likar.app/liquor-price-list/delhi',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'Delhi', state: 'Delhi', price: 140, mrp: 140, currency: 'INR', source: 'https://www.likar.app/liquor-price-list/delhi', sourceType: 'secondary_aggregator', verified: true, verifiedAt: VERIFIED_AT }],
    variants: [
      { id: 'var_bud_500', productId: 'prod_budweiser_magnum', name: '500 ml', volume: '500 ml', price: 115, mrp: 115, sku: 'BUD-MAG-500-DL', isActive: true },
      { id: 'var_bud_650', productId: 'prod_budweiser_magnum', name: '650 ml', volume: '650 ml', price: 140, mrp: 140, sku: 'BUD-MAG-650-DL', isActive: true },
    ],
  },
  {
    id: 'prod_carlsberg_elephant',
    name: 'Carlsberg Elephant Strong Beer',
    slug: 'carlsberg-elephant-strong-beer',
    brandId: 'b_carlsberg',
    brandName: 'Carlsberg',
    categoryId: 'cat_beer',
    categoryName: 'Beer',
    subcategory: 'Strong Lager',
    price: 175,
    mrp: 175,
    volume: '650 ml',
    alcoholByVolume: 7,
    isAlcoholic: true,
    description: 'Carlsberg Elephant strong beer.',
    tastingNotes: ['Malt', 'Fruit', 'Firm finish'],
    imageUrl: '/product-placeholder.svg',
    imageSource: 'https://www.gqindia.com/content/international-beer-day-7-super-strong-brews-under-rs-200-to-celebrate-with',
    imageVerified: false,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Denmark',
    isBestseller: true,
    rating: 0,
    reviewCount: 0,
    isActive: false,
    availableStates: ['Delhi'],
    priceVerified: true,
    priceSource: 'https://www.likar.app/liquor-price-list/delhi',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'Delhi', state: 'Delhi', price: 175, mrp: 175, currency: 'INR', source: 'https://www.likar.app/liquor-price-list/delhi', sourceType: 'secondary_aggregator', verified: true, verifiedAt: VERIFIED_AT }],
  },
  {
    id: 'prod_bisleri_1l',
    name: 'Bisleri Packaged Drinking Water',
    slug: 'bisleri-packaged-water-1l',
    brandId: 'b_bisleri',
    brandName: 'Bisleri',
    categoryId: 'cat_water',
    categoryName: 'Water',
    subcategory: 'Packaged Drinking Water',
    price: 20,
    mrp: 20,
    volume: '1 L',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Bisleri packaged drinking water with added minerals.',
    tastingNotes: [],
    imageUrl: 'https://prithvienterprises.co.in/cdn/shop/files/sliding_images_jpeg_10b8b01a_8b71_4448_becb_16d4247ef05cjpgts1707312326_c0082670-b46c-4a72-80a6-9ac911e3b778.jpg?v=1746382045',
    imageSource: 'https://prithvienterprises.co.in/products/bisleri-packaged-water-1-l-1-l',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'https://www.bigbasket.com/pd/265875/bisleri-mineral-water-1-l-bottle/',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'India', price: 20, mrp: 20, currency: 'INR', source: 'https://www.bigbasket.com/pd/265875/bisleri-mineral-water-1-l-bottle/', sourceType: 'licensed_retailer', verified: true, verifiedAt: VERIFIED_AT }],
  },
  {
    id: 'prod_kinley_1l',
    name: 'Kinley Drinking Water',
    slug: 'kinley-drinking-water-1l',
    brandId: 'b_kinley',
    brandName: 'Kinley',
    categoryId: 'cat_water',
    categoryName: 'Water',
    subcategory: 'Packaged Drinking Water',
    price: 20,
    mrp: 20,
    volume: '1 L',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Kinley drinking water with added minerals.',
    tastingNotes: [],
    imageUrl: 'https://www.jiomart.com/images/product/original/490001790/kinley-packaged-drinking-water-1-l-product-images-o490001790-p490001790-0-202203171141.jpg?im=Resize%3D%281000%2C1000%29',
    imageSource: 'https://www.jiomart.com/p/groceries/kinley-packaged-drinking-water-1-l/490001790',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'https://www.bigbasket.com/pd/265686/kinley-drinking-water-with-added-minerals-1-l-pet-bottle/',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'India', price: 20, mrp: 20, currency: 'INR', source: 'https://www.bigbasket.com/pd/265686/kinley-drinking-water-with-added-minerals-1-l-pet-bottle/', sourceType: 'licensed_retailer', verified: true, verifiedAt: VERIFIED_AT }],
  },
  {
    id: 'prod_redbull_250',
    name: 'Red Bull Energy Drink',
    slug: 'red-bull-energy-drink-250ml',
    brandId: 'b_redbull',
    brandName: 'Red Bull',
    categoryId: 'cat_energy',
    categoryName: 'Energy Drinks',
    subcategory: 'Energy Drinks',
    price: 125,
    mrp: 125,
    volume: '250 ml',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Red Bull Energy Drink 250 ml can.',
    tastingNotes: [],
    imageUrl: 'https://image.aapkabazar.co/product/401/1697090583516.png?type=png',
    imageSource: 'https://aapkabazar.co/401/pd/red-bull-energy-drink-250-ml',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Austria',
    isBestseller: true,
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'https://www.bigbasket.com/pb/red-bull/energy-soft-drinks/',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'India', price: 125, mrp: 125, currency: 'INR', source: 'https://www.bigbasket.com/pb/red-bull/energy-soft-drinks/', sourceType: 'licensed_retailer', verified: true, verifiedAt: VERIFIED_AT }],
  },
  {
    id: 'prod_haldiram_aloo_bhujia_200',
    name: "Haldiram's Aloo Bhujia",
    slug: 'haldirams-aloo-bhujia-200g',
    brandId: 'b_haldirams',
    brandName: "Haldiram's",
    categoryId: 'cat_snacks',
    categoryName: 'Chips & Namkeen',
    subcategory: 'Namkeen',
    price: 60,
    mrp: 60,
    volume: '200 g',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: "Haldiram's Aloo Bhujia namkeen.",
    tastingNotes: [],
    imageUrl: 'https://www.pankaj-boutique.com/31477-large_default/namkeen-indian-aloo-bhujia.jpg',
    imageSource: 'https://www.pankaj-boutique.com/en/indian-food/5770-namkeen-indian-aloo-bhujia.html',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'https://www.bigbasket.com/pb/haldirams/',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'India', price: 60, mrp: 60, currency: 'INR', source: 'https://www.bigbasket.com/pb/haldirams/', sourceType: 'licensed_retailer', verified: true, verifiedAt: VERIFIED_AT }],
  },
  {
    id: 'prod_kurkure_masala_munch_90',
    name: 'Kurkure Masala Munch',
    slug: 'kurkure-masala-munch-90g',
    brandId: 'b_kurkure',
    brandName: 'Kurkure',
    categoryId: 'cat_snacks',
    categoryName: 'Chips & Namkeen',
    subcategory: 'Chips',
    price: 20,
    mrp: 20,
    volume: '90 g',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Kurkure Masala Munch 90 g pack.',
    tastingNotes: [],
    imageUrl: '/product-placeholder.svg',
    imageSource: 'https://exoticsnacks.com/products/kurkure-masala-munch-chips-90g',
    imageVerified: false,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 0,
    reviewCount: 0,
    isActive: false,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'https://fetchnbuy.in/products/kurkure-masala-munch-90-g',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'India', price: 20, mrp: 20, currency: 'INR', source: 'https://fetchnbuy.in/products/kurkure-masala-munch-90-g', sourceType: 'licensed_retailer', verified: true, verifiedAt: VERIFIED_AT }],
  },
  {
    id: 'prod_pringles_original_107',
    name: 'Pringles Original',
    slug: 'pringles-original-107g',
    brandId: 'b_pringles',
    brandName: 'Pringles',
    categoryId: 'cat_snacks',
    categoryName: 'Chips & Namkeen',
    subcategory: 'Chips',
    price: 110,
    mrp: 125,
    volume: '107 g',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Pringles Original potato crisps, 107 g.',
    tastingNotes: [],
    imageUrl: '/product-placeholder.svg',
    imageSource: 'https://17mins.com/products/pringles-original-anantapur',
    imageVerified: false,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Malaysia',
    isBestseller: true,
    rating: 0,
    reviewCount: 0,
    isActive: false,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'https://www.kelloggs.com/en-in/revised-product-price-list.html',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'India', price: 110, mrp: 125, currency: 'INR', source: 'https://www.kelloggs.com/en-in/revised-product-price-list.html', sourceType: 'manufacturer', verified: true, verifiedAt: VERIFIED_AT }],
  },
  {
    id: 'prod_home_one_napkins_100',
    name: 'Home One Paper Napkins',
    slug: 'home-one-paper-napkins-100',
    brandId: 'b_homeone',
    brandName: 'Home One',
    categoryId: 'cat_party_napkins',
    categoryName: 'Napkins',
    subcategory: 'Paper Napkins',
    price: 45,
    mrp: 45,
    volume: '100 pcs',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Paper napkins, 29 x 29 cm, 100 pieces.',
    tastingNotes: [],
    imageUrl: 'https://www.jiomart.com/images/product/original/491963192/home-one-paper-napkin-29-x-29-cm-100-pcs-product-images-o491963192-p590441807-0-202203170913.jpg?im=Resize%3D%281000%2C1000%29',
    imageSource: 'https://www.jiomart.com/p/groceries/home-one-paper-napkin-29-x-29-cm-100-pcs/590441807',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'https://www.exportersindia.com/product-detail/royal-tissue-paper-napkin-3736748249.htm',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'India', price: 45, mrp: 45, currency: 'INR', source: 'https://www.exportersindia.com/product-detail/royal-tissue-paper-napkin-3736748249.htm', sourceType: 'secondary_aggregator', verified: true, verifiedAt: VERIFIED_AT }],
  },,
  {
    id: 'prod_haldiram_aloo_bhujia_400',
    name: "Haldiram's Aloo Bhujia",
    slug: 'haldirams-aloo-bhujia-400g',
    brandId: 'b_haldirams',
    brandName: "Haldiram's",
    categoryId: 'cat_snacks',
    categoryName: 'Chips & Namkeen',
    subcategory: 'Namkeen',
    price: 110,
    mrp: 110,
    volume: '400 g',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: "Haldiram's Aloo Bhujia, 400 g pack.",
    tastingNotes: [],
    imageUrl: 'https://www.pankaj-boutique.com/31477-large_default/namkeen-indian-aloo-bhujia.jpg',
    imageSource: 'https://haldirams.com/products/aloo-bhujia',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'https://www.zepto.com/pn/haldirams-aloo-bhujia-crunchy-savory-snack/pvid/9110b35f-5c01-4b29-8547-bcd5c01815f1',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'India', price: 110, mrp: 110, currency: 'INR', source: 'https://www.zepto.com/pn/haldirams-aloo-bhujia-crunchy-savory-snack/pvid/9110b35f-5c01-4b29-8547-bcd5c01815f1', sourceType: 'licensed_retailer', verified: true, verifiedAt: VERIFIED_AT }],
  },
  {
    id: 'prod_origami_paper_plates_23',
    name: 'Origami Disposable Paper Plates',
    slug: 'origami-disposable-paper-plates-23cm',
    brandId: 'b_origami',
    brandName: 'Origami',
    categoryId: 'cat_party_plates',
    categoryName: 'Disposable Plates',
    subcategory: 'Paper Plates',
    price: 211,
    mrp: 300,
    volume: '23 cm · 100 pcs',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Origami disposable paper plates, 23 cm, 100 pcs.',
    tastingNotes: [],
    imageUrl: 'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=900&auto=format&fit=crop&q=85',
    imageSource: 'https://www.zepto.com/pn/origami-disposable-paper-plates-23-cm/pvid/abd40632-39ca-4da1-b599-aac4d81c45a9',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'https://www.zepto.com/pn/origami-disposable-paper-plates-23-cm/pvid/abd40632-39ca-4da1-b599-aac4d81c45a9',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'India', price: 211, mrp: 300, currency: 'INR', source: 'https://www.zepto.com/pn/origami-disposable-paper-plates-23-cm/pvid/abd40632-39ca-4da1-b599-aac4d81c45a9', sourceType: 'licensed_retailer', verified: true, verifiedAt: VERIFIED_AT }],
  },
  {
    id: 'prod_origami_paper_bowls_10',
    name: 'Origami Paper Bowls',
    slug: 'origami-paper-bowls-165mm-10pcs',
    brandId: 'b_origami',
    brandName: 'Origami',
    categoryId: 'cat_party_bowls',
    categoryName: 'Bowls',
    subcategory: 'Disposable Bowls',
    price: 65,
    mrp: 65,
    volume: '16.5 cm · 10 pcs',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Origami paper bowls, 16.5 cm, pack of 10.',
    tastingNotes: [],
    imageUrl: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?w=900&auto=format&fit=crop&q=85',
    imageSource: 'https://www.jiomart.com/p/groceries/origami-paper-bowls-16-5-cm-10-pcs/612145404',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'https://www.jiomart.com/p/groceries/origami-paper-bowls-16-5-cm-10-pcs/612145404',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [{ market: 'India', price: 65, mrp: 65, currency: 'INR', source: 'https://www.jiomart.com/p/groceries/origami-paper-bowls-16-5-cm-10-pcs/612145404', sourceType: 'licensed_retailer', verified: true, verifiedAt: VERIFIED_AT }],
  },
  {
    id: 'prod_party_glasses_50',
    name: 'Disposable Party Glasses',
    slug: 'disposable-party-glasses-50pcs',
    brandId: 'b_origami',
    brandName: 'Origami',
    categoryId: 'cat_party_glasses',
    categoryName: 'Disposable Glasses',
    subcategory: '300 ml',
    price: 99,
    mrp: 129,
    volume: '300 ml · 50 pcs',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Disposable drinking glasses for parties and gatherings.',
    tastingNotes: [],
    imageUrl: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=900&auto=format&fit=crop&q=85',
    imageSource: 'https://www.toolsvilla.com/dp/disposable-paper-plates',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: false,
    priceSource: 'https://www.toolsvilla.com/dp/disposable-paper-plates',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [],
  },
  {
    id: 'prod_origami_napkins_50',
    name: 'Origami So Soft Luncheon Napkins',
    slug: 'origami-so-soft-luncheon-napkins-50',
    brandId: 'b_origami',
    brandName: 'Origami',
    categoryId: 'cat_party_napkins',
    categoryName: 'Napkins',
    subcategory: 'Paper Napkins',
    price: 75,
    mrp: 75,
    volume: '32 x 32 cm · 50 pcs',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Origami So Soft 1 ply printed luncheon napkins, 50 pcs.',
    tastingNotes: [],
    imageUrl: 'https://www.jiomart.com/images/product/original/590145676/origami-so-soft-1-ply-printed-luncheon-napkins-32x32-cm-50-pcs-product-images-o590145676-p590145676-0-202203170913.jpg',
    imageSource: 'https://www.jiomart.com/p/groceries/origami-so-soft-1-ply-printed-luncheon-napkins-50-pcs/590145676',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 0,
    reviewCount: 0,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: false,
    priceSource: 'https://www.jiomart.com/p/groceries/origami-so-soft-1-ply-printed-luncheon-napkins-50-pcs/590145676',
    priceVerifiedAt: VERIFIED_AT,
    regionalPrices: [],
  }

];
