import { Product } from '../types.ts';

export const SEED_PRODUCTS: Product[] = [
  // ==========================================
  // WHISKY (UP + DELHI REGIONAL FAVORITES)
  // ==========================================
  {
    id: 'prod_royal_stag',
    name: 'Royal Stag Deluxe Whisky',
    slug: 'royal-stag-deluxe-whisky',
    brandId: 'b_royalstag',
    brandName: 'Royal Stag',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Malt',
    price: 490,
    mrp: 520,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Seagram’s iconic blend of imported Scotch malts and select Indian grain spirits. Smooth, woody, with a distinctive rounded finish.',
    tastingNotes: ['Malt sweetness', 'Subtle smoke', 'Charred wood', 'Warm finish'],
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    isFeatured: true,
    rating: 4.6,
    reviewCount: 520,
    isActive: true,
    variants: [
      { id: 'var_rs_180', productId: 'prod_royal_stag', name: '180 ml (Quarter)', volume: '180 ml', price: 130, mrp: 140, isActive: true },
      { id: 'var_rs_375', productId: 'prod_royal_stag', name: '375 ml (Pint)', volume: '375 ml', price: 260, mrp: 275, isActive: true },
      { id: 'var_rs_750', productId: 'prod_royal_stag', name: '750 ml (Full)', volume: '750 ml', price: 490, mrp: 520, isActive: true },
    ]
  },
  {
    id: 'prod_blenders_pride',
    name: 'Blenders Pride Rare Premium Whisky',
    slug: 'blenders-pride-rare-premium-whisky',
    brandId: 'b_blenderspride',
    brandName: 'Blenders Pride',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Malt',
    price: 880,
    mrp: 940,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Expertly blended Indian grain spirits with Scottish malt concentrates. Known for rich, creamy fruit notes and exceptional smoothness.',
    tastingNotes: ['Honeyed malt', 'Peat undertones', 'Dried fruit', 'Velvety finish'],
    imageUrl: 'https://images.unsplash.com/photo-1582819509237-d5b75f20ff7a?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 680,
    isActive: true,
    variants: [
      { id: 'var_bp_180', productId: 'prod_blenders_pride', name: '180 ml (Quarter)', volume: '180 ml', price: 230, mrp: 245, isActive: true },
      { id: 'var_bp_375', productId: 'prod_blenders_pride', name: '375 ml (Pint)', volume: '375 ml', price: 450, mrp: 480, isActive: true },
      { id: 'var_bp_750', productId: 'prod_blenders_pride', name: '750 ml (Full)', volume: '750 ml', price: 880, mrp: 940, isActive: true },
    ]
  },
  {
    id: 'prod_imperial_blue',
    name: 'Imperial Blue Superior Grain Whisky',
    slug: 'imperial-blue-superior-grain-whisky',
    brandId: 'b_imperialblue',
    brandName: 'Imperial Blue',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Premium Grain',
    price: 430,
    mrp: 460,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'A benchmark in Indian grain whisky. Delivers a soft, medium-bodied experience with clean aroma and gentle sweetness.',
    tastingNotes: ['Light grain', 'Subtle vanilla', 'Sweet caramel', 'Clean palate'],
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.5,
    reviewCount: 390,
    isActive: true,
    variants: [
      { id: 'var_ib_180', productId: 'prod_imperial_blue', name: '180 ml (Quarter)', volume: '180 ml', price: 115, mrp: 125, isActive: true },
      { id: 'var_ib_375', productId: 'prod_imperial_blue', name: '375 ml (Pint)', volume: '375 ml', price: 225, mrp: 240, isActive: true },
      { id: 'var_ib_750', productId: 'prod_imperial_blue', name: '750 ml (Full)', volume: '750 ml', price: 430, mrp: 460, isActive: true },
    ]
  },
  {
    id: 'prod_mcdowells_no1',
    name: "McDowell's No.1 Reserve Whisky",
    slug: 'mcdowells-no-1-reserve-whisky',
    brandId: 'b_mcdowell',
    brandName: "McDowell's No.1",
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Malt',
    price: 440,
    mrp: 470,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'The classic Indian celebration whisky blended with imported scotch malts and selected Indian spirits.',
    tastingNotes: ['Sweet oak', 'Toasted cereal', 'Light butterscotch', 'Smooth warmth'],
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.5,
    reviewCount: 440,
    isActive: true,
    variants: [
      { id: 'var_mcd_180', productId: 'prod_mcdowells_no1', name: '180 ml (Quarter)', volume: '180 ml', price: 120, mrp: 130, isActive: true },
      { id: 'var_mcd_375', productId: 'prod_mcdowells_no1', name: '375 ml (Pint)', volume: '375 ml', price: 235, mrp: 250, isActive: true },
      { id: 'var_mcd_750', productId: 'prod_mcdowells_no1', name: '750 ml (Full)', volume: '750 ml', price: 440, mrp: 470, isActive: true },
    ]
  },
  {
    id: 'prod_royal_challenge',
    name: 'Royal Challenge Finest Premium Whisky',
    slug: 'royal-challenge-finest-premium-whisky',
    brandId: 'b_royalchallenge',
    brandName: 'Royal Challenge',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Indian Malt',
    price: 660,
    mrp: 720,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Matured in charred American oak casks. Characterized by deep amber tone and smooth toasted wood nuances.',
    tastingNotes: ['Charred oak', 'Honeyed fruit', 'Gentle spice', 'Warm finish'],
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    rating: 4.6,
    reviewCount: 310,
    isActive: true,
  },
  {
    id: 'prod_8pm_whisky',
    name: '8 PM Premium Indian Whisky',
    slug: '8-pm-premium-indian-whisky',
    brandId: 'b_8pm',
    brandName: '8 PM',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Premium Grain',
    price: 410,
    mrp: 440,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Radico Khaitan’s flagship Indian whisky blend with high repeat loyalty across Uttar Pradesh & Delhi.',
    tastingNotes: ['Grain sweetness', 'Nutty oak', 'Light malt'],
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    rating: 4.4,
    reviewCount: 260,
    isActive: true,
  },
  {
    id: 'prod_officers_choice',
    name: "Officer's Choice Blue Prestige Whisky",
    slug: 'officers-choice-blue-prestige-whisky',
    brandId: 'b_officerschoice',
    brandName: "Officer's Choice",
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Premium Grain',
    price: 430,
    mrp: 460,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Crafted with fine Scotch malts and neutral grain spirits for an approachable, crisp everyday sip.',
    tastingNotes: ['Caramel', 'Oak spice', 'Smooth sip'],
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    rating: 4.4,
    reviewCount: 195,
    isActive: true,
  },
  {
    id: 'prod_black_dog_reserve',
    name: 'Black Dog Triple Gold Reserve Blended Scotch',
    slug: 'black-dog-triple-gold-reserve',
    brandId: 'b_blackdog',
    brandName: 'Black Dog',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Blended Scotch',
    price: 1850,
    mrp: 2050,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Triple-matured blended Scotch whisky crafted with grain and malt whiskies matured in Oloroso sherry casks.',
    tastingNotes: ['Sherry fruit', 'Toffee', 'Rich wood', 'Mellow smoke'],
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=600&auto=format&fit=crop&q=80',
    country: 'Scotland',
    isFeatured: true,
    rating: 4.8,
    reviewCount: 380,
    isActive: true,
  },
  {
    id: 'prod_100_pipers',
    name: '100 Pipers 12 Year Old Deluxe Blended Scotch',
    slug: '100-pipers-12-yo-blended-scotch',
    brandId: 'b_100pipers',
    brandName: '100 Pipers',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Blended Scotch',
    price: 2150,
    mrp: 2400,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Smooth, gently peated Scotch blended from over 25 individual whiskies aged for minimum 12 years.',
    tastingNotes: ['Peat smoke', 'Honeyed oak', 'Fruity malt', 'Lingering warm finish'],
    imageUrl: 'https://images.unsplash.com/photo-1582819509237-d5b75f20ff7a?w=600&auto=format&fit=crop&q=80',
    country: 'Scotland',
    rating: 4.7,
    reviewCount: 290,
    isActive: true,
  },
  {
    id: 'prod_jw_black',
    name: 'Johnnie Walker Black Label 12 Year Old',
    slug: 'johnnie-walker-black-label-12-yo',
    brandId: 'b_jw',
    brandName: 'Johnnie Walker',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Blended Scotch',
    price: 3350,
    mrp: 3700,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'An iconic blended scotch crafted from whiskies aged at least 12 years across Scotland. Signature peat smoke and sweet vanilla.',
    tastingNotes: ['Sweet vanilla', 'Dark fruits', 'Creamy toffee', 'Signature peat smoke'],
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=600&auto=format&fit=crop&q=80',
    country: 'Scotland',
    isBestseller: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 540,
    isActive: true,
  },
  {
    id: 'prod_chivas_12',
    name: 'Chivas Regal 12 Year Old Blended Scotch',
    slug: 'chivas-regal-12-year-old',
    brandId: 'b_chivas',
    brandName: 'Chivas Regal',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Blended Scotch',
    price: 3100,
    mrp: 3450,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'A blend of many different malt and grain Scotch whiskies, matured for at least 12 years. Rich, smooth Speyside character.',
    tastingNotes: ['Wild herbs', 'Heather honey', 'Orchard fruits', 'Creamy vanilla'],
    imageUrl: 'https://images.unsplash.com/photo-1582819509237-d5b75f20ff7a?w=600&auto=format&fit=crop&q=80',
    country: 'Scotland',
    rating: 4.8,
    reviewCount: 310,
    isActive: true,
  },
  {
    id: 'prod_jameson_original',
    name: 'Jameson Triple Distilled Irish Whiskey',
    slug: 'jameson-irish-whiskey',
    brandId: 'b_jameson',
    brandName: 'Jameson',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Irish Whiskey',
    price: 2100,
    mrp: 2350,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Triple-distilled, twice as smooth. Perfect for easy sipping, highballs, and cocktails with ginger ale.',
    tastingNotes: ['Spicy wood', 'Sweet sherry', 'Green apple', 'Ultra smooth'],
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=600&auto=format&fit=crop&q=80',
    country: 'Ireland',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 420,
    isActive: true,
  },
  {
    id: 'prod_glenfiddich_12',
    name: 'Glenfiddich 12 Year Old Single Malt',
    slug: 'glenfiddich-12-year-old-single-malt',
    brandId: 'b_glenfiddich',
    brandName: 'Glenfiddich',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Single Malt',
    price: 5400,
    mrp: 5900,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Carefully matured in the finest American bourbon and European sherry oak casks for at least 12 years.',
    tastingNotes: ['Fresh pear', 'Subtle oak', 'Creamy butterscotch', 'Delicate malt'],
    imageUrl: 'https://images.unsplash.com/photo-1582819509237-d5b75f20ff7a?w=600&auto=format&fit=crop&q=80',
    country: 'Scotland',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 290,
    isActive: true,
  },
  {
    id: 'prod_indri_trini',
    name: 'Indri Trini Three Wood Single Malt Indian Whisky',
    slug: 'indri-trini-single-malt-indian-whisky',
    brandId: 'b_indri',
    brandName: 'Indri',
    categoryId: 'cat_whisky',
    categoryName: 'Whisky',
    subcategory: 'Single Malt',
    price: 3800,
    mrp: 4200,
    volume: '750 ml',
    alcoholByVolume: 46.0,
    isAlcoholic: true,
    description: 'Award-winning Indian single malt matured in ex-Bourbon, ex-French wine, and PX Sherry casks in northern India.',
    tastingNotes: ['Tropical fruits', 'Blackberry', 'Cinnamon spice', 'Rich oak finish'],
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isNewArrival: true,
    rating: 4.9,
    reviewCount: 180,
    isActive: true,
  },

  // ==========================================
  // BEER & CIDERS (UP + DELHI FAVORITES)
  // ==========================================
  {
    id: 'prod_kf_premium',
    name: 'Kingfisher Premium Lager Beer',
    slug: 'kingfisher-premium-lager-beer',
    brandId: 'b_kingfisher',
    brandName: 'Kingfisher',
    categoryId: 'cat_beer',
    categoryName: 'Beer & Ciders',
    subcategory: 'Premium Mild',
    price: 140,
    mrp: 155,
    volume: '650 ml Bottle',
    alcoholByVolume: 5.0,
    isAlcoholic: true,
    description: 'The King of Good Times. Crisp, clean, impeccably brewed with finest Saaz hops and malted barley.',
    tastingNotes: ['Crisp malt', 'Gentle hop bitterness', 'Clean refreshing finish'],
    imageUrl: 'https://images.unsplash.com/photo-1608270199182-4faeb9ff7584?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 820,
    isActive: true,
    variants: [
      { id: 'var_kf_can', productId: 'prod_kf_premium', name: '500 ml Can', volume: '500 ml', price: 130, mrp: 140, isActive: true },
      { id: 'var_kf_bottle', productId: 'prod_kf_premium', name: '650 ml Bottle', volume: '650 ml', price: 140, mrp: 155, isActive: true },
      { id: 'var_kf_pack6', productId: 'prod_kf_premium', name: 'Pack of 6 Cans (6 x 500ml)', volume: '3000 ml', price: 749, mrp: 840, isActive: true },
    ]
  },
  {
    id: 'prod_kf_ultra',
    name: 'Kingfisher Ultra Max Premium Beer',
    slug: 'kingfisher-ultra-max-beer',
    brandId: 'b_kingfisher',
    brandName: 'Kingfisher',
    categoryId: 'cat_beer',
    categoryName: 'Beer & Ciders',
    subcategory: 'Strong Lager',
    price: 180,
    mrp: 195,
    volume: '650 ml Bottle',
    alcoholByVolume: 6.8,
    isAlcoholic: true,
    description: 'Slow-brewed with imported European pilsen malts for a remarkably smooth strong beer experience.',
    tastingNotes: ['Golden malt', 'Crisp effervescence', 'Smooth strong body'],
    imageUrl: 'https://images.unsplash.com/photo-1608270199182-4faeb9ff7584?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 460,
    isActive: true,
  },
  {
    id: 'prod_tuborg_green',
    name: 'Tuborg Green Crisp Pilsner Beer',
    slug: 'tuborg-green-pilsner-beer',
    brandId: 'b_tuborg',
    brandName: 'Tuborg',
    categoryId: 'cat_beer',
    categoryName: 'Beer & Ciders',
    subcategory: 'Premium Mild',
    price: 130,
    mrp: 145,
    volume: '650 ml Bottle',
    alcoholByVolume: 4.8,
    isAlcoholic: true,
    description: 'Bottom-fermented European lager with signature pull-off cap. Lively carbonation and easy-drinking character.',
    tastingNotes: ['Cereal grain', 'Light floral hops', 'Crisp dryness'],
    imageUrl: 'https://images.unsplash.com/photo-1608270199182-4faeb9ff7584?w=600&auto=format&fit=crop&q=80',
    country: 'Denmark',
    isBestseller: true,
    rating: 4.6,
    reviewCount: 510,
    isActive: true,
  },
  {
    id: 'prod_tuborg_strong',
    name: 'Tuborg Classic Strong with Scotch Malts',
    slug: 'tuborg-classic-strong-scotch-malts',
    brandId: 'b_tuborg',
    brandName: 'Tuborg',
    categoryId: 'cat_beer',
    categoryName: 'Beer & Ciders',
    subcategory: 'Strong Lager',
    price: 150,
    mrp: 165,
    volume: '650 ml Bottle',
    alcoholByVolume: 7.0,
    isAlcoholic: true,
    description: 'A premium strong beer brewed with imported Scotch malts for a rich, satisfying, full-bodied taste.',
    tastingNotes: ['Malt punch', 'Caramel touch', 'Warm finish'],
    imageUrl: 'https://images.unsplash.com/photo-1608270199182-4faeb9ff7584?w=600&auto=format&fit=crop&q=80',
    country: 'Denmark',
    rating: 4.7,
    reviewCount: 410,
    isActive: true,
  },
  {
    id: 'prod_carlsberg_elephant',
    name: 'Carlsberg Elephant Strong Super Premium Beer',
    slug: 'carlsberg-elephant-strong-beer',
    brandId: 'b_carlsberg',
    brandName: 'Carlsberg',
    categoryId: 'cat_beer',
    categoryName: 'Beer & Ciders',
    subcategory: 'Strong Lager',
    price: 175,
    mrp: 190,
    volume: '650 ml Bottle',
    alcoholByVolume: 7.2,
    isAlcoholic: true,
    description: 'An iconic powerhouse Danish strong beer with vinous notes, rich barley malt, and balanced hop character.',
    tastingNotes: ['Deep malt', 'Corn sweetness', 'Firm hop finish'],
    imageUrl: 'https://images.unsplash.com/photo-1608270199182-4faeb9ff7584?w=600&auto=format&fit=crop&q=80',
    country: 'Denmark',
    rating: 4.7,
    reviewCount: 390,
    isActive: true,
  },
  {
    id: 'prod_budweiser_magnum',
    name: 'Budweiser Magnum Strong American Lager',
    slug: 'budweiser-magnum-strong-beer',
    brandId: 'b_budweiser',
    brandName: 'Budweiser',
    categoryId: 'cat_beer',
    categoryName: 'Beer & Ciders',
    subcategory: 'Strong Lager',
    price: 195,
    mrp: 215,
    volume: '650 ml Bottle',
    alcoholByVolume: 6.5,
    isAlcoholic: true,
    description: 'Beechwood-aged for extra smoothness and crispness. The undisputed king of strong lagers in Delhi NCR.',
    tastingNotes: ['Toasted malt', 'Beechwood aged clarity', 'Crisp punch'],
    imageUrl: 'https://images.unsplash.com/photo-1608270199182-4faeb9ff7584?w=600&auto=format&fit=crop&q=80',
    country: 'United States',
    isBestseller: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 650,
    isActive: true,
    variants: [
      { id: 'var_bud_can', productId: 'prod_budweiser_magnum', name: '500 ml Can', volume: '500 ml', price: 165, mrp: 180, isActive: true },
      { id: 'var_bud_bottle', productId: 'prod_budweiser_magnum', name: '650 ml Bottle', volume: '650 ml', price: 195, mrp: 215, isActive: true },
      { id: 'var_bud_pack6', productId: 'prod_budweiser_magnum', name: 'Party 6-Pack (6 x 500ml Cans)', volume: '3000 ml', price: 950, mrp: 1080, isActive: true },
    ]
  },
  {
    id: 'prod_bira_white',
    name: 'Bira 91 White Belgian Style Wheat Beer',
    slug: 'bira-91-white-wheat-beer',
    brandId: 'b_bira',
    brandName: 'Bira 91',
    categoryId: 'cat_beer',
    categoryName: 'Beer & Ciders',
    subcategory: 'Wheat Beer',
    price: 170,
    mrp: 185,
    volume: '500 ml Can',
    alcoholByVolume: 4.7,
    isAlcoholic: true,
    description: 'Deliciously refreshing craft wheat ale spiced with orange peel and fresh coriander. Low bitterness, bright citrus.',
    tastingNotes: ['Orange peel', 'Coriander seeds', 'Creamy wheat', 'Cloudy gold'],
    imageUrl: 'https://images.unsplash.com/photo-1608270199182-4faeb9ff7584?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 480,
    isActive: true,
  },
  {
    id: 'prod_corona_extra',
    name: 'Corona Extra Imported Mexican Beer',
    slug: 'corona-extra-mexican-beer',
    brandId: 'b_corona',
    brandName: 'Corona',
    categoryId: 'cat_beer',
    categoryName: 'Beer & Ciders',
    subcategory: 'Premium Mild',
    price: 240,
    mrp: 260,
    volume: '330 ml Bottle',
    alcoholByVolume: 4.5,
    isAlcoholic: true,
    description: 'Light, crisp Mexican pale lager best enjoyed ice-cold with a wedge of fresh lime in the neck.',
    tastingNotes: ['Corn sweetness', 'Light malt', 'Sparkling clean finish'],
    imageUrl: 'https://images.unsplash.com/photo-1608270199182-4faeb9ff7584?w=600&auto=format&fit=crop&q=80',
    country: 'Mexico',
    rating: 4.7,
    reviewCount: 310,
    isActive: true,
  },
  {
    id: 'prod_haywards_5000',
    name: 'Haywards 5000 Super Strong Beer',
    slug: 'haywards-5000-super-strong-beer',
    brandId: 'b_haywards',
    brandName: 'Haywards 5000',
    categoryId: 'cat_beer',
    categoryName: 'Beer & Ciders',
    subcategory: 'Strong Lager',
    price: 135,
    mrp: 150,
    volume: '650 ml Bottle',
    alcoholByVolume: 7.2,
    isAlcoholic: true,
    description: 'India’s legendary strong beer. High alcohol warmth with heavy malt profile and distinctive bold kick.',
    tastingNotes: ['Roasted grain', 'Heavy malt', 'Robust warmth'],
    imageUrl: 'https://images.unsplash.com/photo-1608270199182-4faeb9ff7584?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    rating: 4.5,
    reviewCount: 370,
    isActive: true,
  },

  // ==========================================
  // VODKA (MAGIC MOMENTS, SMIRNOFF, ABSOLUT)
  // ==========================================
  {
    id: 'prod_magic_moments_plain',
    name: 'Magic Moments Pure Grain Vodka',
    slug: 'magic-moments-pure-grain-vodka',
    brandId: 'b_magicmoments',
    brandName: 'Magic Moments',
    categoryId: 'cat_vodka',
    categoryName: 'Vodka',
    subcategory: 'Grain Vodka',
    price: 520,
    mrp: 560,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Radico Khaitan’s UP-distilled master vodka. Triple distilled through imported carbon filters for remarkable crystal clarity.',
    tastingNotes: ['Clean grain', 'Subtle sweetness', 'Smooth warming palate'],
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 460,
    isActive: true,
    variants: [
      { id: 'var_mm_180', productId: 'prod_magic_moments_plain', name: '180 ml (Quarter)', volume: '180 ml', price: 140, mrp: 150, isActive: true },
      { id: 'var_mm_375', productId: 'prod_magic_moments_plain', name: '375 ml (Pint)', volume: '375 ml', price: 270, mrp: 290, isActive: true },
      { id: 'var_mm_750', productId: 'prod_magic_moments_plain', name: '750 ml (Full)', volume: '750 ml', price: 520, mrp: 560, isActive: true },
    ]
  },
  {
    id: 'prod_magic_moments_apple',
    name: 'Magic Moments Remix Green Apple Vodka',
    slug: 'magic-moments-remix-green-apple',
    brandId: 'b_magicmoments',
    brandName: 'Magic Moments',
    categoryId: 'cat_vodka',
    categoryName: 'Vodka',
    subcategory: 'Green Apple',
    price: 550,
    mrp: 590,
    volume: '750 ml',
    alcoholByVolume: 37.5,
    isAlcoholic: true,
    description: 'Tart, crisp Granny Smith green apple infused vodka. Tremendously popular party shot and mixer across North India.',
    tastingNotes: ['Crisp green apple', 'Tart citrus', 'Refreshing candy finish'],
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 390,
    isActive: true,
  },
  {
    id: 'prod_smirnoff_triple',
    name: 'Smirnoff No. 21 Triple Distilled Vodka',
    slug: 'smirnoff-no-21-triple-distilled-vodka',
    brandId: 'b_smirnoff',
    brandName: 'Smirnoff',
    categoryId: 'cat_vodka',
    categoryName: 'Vodka',
    subcategory: 'Grain Vodka',
    price: 880,
    mrp: 950,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Triple distilled from grain and 10 times filtered through seven columns of charcoal for purity.',
    tastingNotes: ['Neutral grain', 'Peppery clean finish'],
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&auto=format&fit=crop&q=80',
    country: 'United Kingdom',
    rating: 4.7,
    reviewCount: 340,
    isActive: true,
  },
  {
    id: 'prod_absolut_blue',
    name: 'Absolut Original Swedish Vodka',
    slug: 'absolut-original-swedish-vodka',
    brandId: 'b_absolut',
    brandName: 'Absolut',
    categoryId: 'cat_vodka',
    categoryName: 'Vodka',
    subcategory: 'Grain Vodka',
    price: 1750,
    mrp: 1950,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: 'Crafted exclusively from southern Swedish winter wheat with zero added sugar. Ultra pure and rich.',
    tastingNotes: ['Winter wheat', 'Dried fruit hint', 'Silky smoothness'],
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&auto=format&fit=crop&q=80',
    country: 'Sweden',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 420,
    isActive: true,
  },

  // ==========================================
  // RUM (OLD MONK, BACARDI, CELEBRATION)
  // ==========================================
  {
    id: 'prod_old_monk_xxx',
    name: 'Old Monk The Legend XXX Dark Rum',
    slug: 'old-monk-xxx-dark-rum',
    brandId: 'b_oldmonk',
    brandName: 'Old Monk',
    categoryId: 'cat_rum',
    categoryName: 'Rum',
    subcategory: 'Dark Rum',
    price: 480,
    mrp: 520,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'The legendary Indian dark rum blended and aged in oak vats at Mohan Meakin, Ghaziabad (UP). Iconic vanilla, cocoa, and spice notes.',
    tastingNotes: ['Vanilla pods', 'Dark cocoa', 'Caramelized molasses', 'Toasted spices'],
    imageUrl: 'https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 940,
    isActive: true,
    variants: [
      { id: 'var_om_180', productId: 'prod_old_monk_xxx', name: '180 ml (Quarter)', volume: '180 ml', price: 125, mrp: 135, isActive: true },
      { id: 'var_om_375', productId: 'prod_old_monk_xxx', name: '375 ml (Pint)', volume: '375 ml', price: 250, mrp: 270, isActive: true },
      { id: 'var_om_750', productId: 'prod_old_monk_xxx', name: '750 ml (Full)', volume: '750 ml', price: 480, mrp: 520, isActive: true },
      { id: 'var_om_1000', productId: 'prod_old_monk_xxx', name: '1000 ml (1 Litre)', volume: '1000 ml', price: 620, mrp: 670, isActive: true },
    ]
  },
  {
    id: 'prod_bacardi_blanca',
    name: 'Bacardi Carta Blanca Superior White Rum',
    slug: 'bacardi-carta-blanca-white-rum',
    brandId: 'b_bacardi',
    brandName: 'Bacardi',
    categoryId: 'cat_rum',
    categoryName: 'Rum',
    subcategory: 'White Rum',
    price: 890,
    mrp: 960,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Aged in white oak barrels and charcoal filtered for delicate floral, almond, and vanilla accents. Ideal for Mojitos & Daiquiris.',
    tastingNotes: ['Almond', 'Subtle vanilla', 'Lime blossom', 'Clean finish'],
    imageUrl: 'https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=600&auto=format&fit=crop&q=80',
    country: 'Puerto Rico',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 380,
    isActive: true,
  },
  {
    id: 'prod_mcdowells_celebration',
    name: "McDowell's No.1 Celebration Dark Rum",
    slug: 'mcdowells-no-1-celebration-dark-rum',
    brandId: 'b_celebration',
    brandName: "McDowell's Celebration",
    categoryId: 'cat_rum',
    categoryName: 'Rum',
    subcategory: 'Dark Rum',
    price: 430,
    mrp: 460,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Warm, spiced dark rum with rich caramel undertones. A timeless favourite for winter get-togethers in UP and Delhi.',
    tastingNotes: ['Brown sugar', 'Clove spice', 'Warm oak'],
    imageUrl: 'https://images.unsplash.com/photo-1614313511387-1436a4480ebb?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    rating: 4.5,
    reviewCount: 310,
    isActive: true,
  },

  // ==========================================
  // GIN (GREATER THAN, BOMBAY SAPPHIRE, GORDON'S)
  // ==========================================
  {
    id: 'prod_greater_than',
    name: 'Greater Than London Dry Craft Gin',
    slug: 'greater-than-craft-gin',
    brandId: 'b_greaterthan',
    brandName: 'Greater Than',
    categoryId: 'cat_gin',
    categoryName: 'Gin',
    subcategory: 'Craft Botanical',
    price: 1150,
    mrp: 1250,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'India’s pioneering craft gin distilled with Macedonian juniper, coriander seeds, fennel, ginger, and fresh lemon peel.',
    tastingNotes: ['Juniper kick', 'Fresh citrus zest', 'Warm ginger', 'Clean crisp dry finish'],
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    isFeatured: true,
    rating: 4.8,
    reviewCount: 460,
    isActive: true,
  },
  {
    id: 'prod_bombay_sapphire',
    name: 'Bombay Sapphire Vapour Infused Gin',
    slug: 'bombay-sapphire-vapour-infused-gin',
    brandId: 'b_bombay',
    brandName: 'Bombay Sapphire',
    categoryId: 'cat_gin',
    categoryName: 'Gin',
    subcategory: 'London Dry',
    price: 2100,
    mrp: 2350,
    volume: '750 ml',
    alcoholByVolume: 40.0,
    isAlcoholic: true,
    description: '10 precious botanicals vapour infused in copper baskets for a bright, uplifting, and fragrant botanical character.',
    tastingNotes: ['Cubeb pepper', 'Almond sweetness', 'Juniper', 'Zesty lemon'],
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    country: 'United Kingdom',
    rating: 4.8,
    reviewCount: 390,
    isActive: true,
  },

  // ==========================================
  // BRANDY & WINE
  // ==========================================
  {
    id: 'prod_mansion_house',
    name: 'Mansion House French Grape Brandy',
    slug: 'mansion-house-french-grape-brandy',
    brandId: 'b_mansionhouse',
    brandName: 'Mansion House',
    categoryId: 'cat_brandy',
    categoryName: 'Brandy',
    subcategory: 'Grape Brandy',
    price: 680,
    mrp: 740,
    volume: '750 ml',
    alcoholByVolume: 42.8,
    isAlcoholic: true,
    description: 'Blended with fine French grape spirits and matured in oak casks. Warm, rich, and rounded palate.',
    tastingNotes: ['Ripe grape', 'Toasted oak', 'Gentle honey'],
    imageUrl: 'https://images.unsplash.com/photo-1527281400683-1aae777175f8?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    rating: 4.6,
    reviewCount: 220,
    isActive: true,
  },
  {
    id: 'prod_sula_shiraz',
    name: 'Sula Dindori Reserve Shiraz Red Wine',
    slug: 'sula-dindori-reserve-shiraz',
    brandId: 'b_sula',
    brandName: 'Sula Vineyards',
    categoryId: 'cat_wine',
    categoryName: 'Wine',
    subcategory: 'Red Wine',
    price: 1350,
    mrp: 1490,
    volume: '750 ml',
    alcoholByVolume: 13.5,
    isAlcoholic: true,
    description: 'A powerful Indian red aged in American oak barrels. Lush aromas of black cherry, dark plum, and black pepper.',
    tastingNotes: ['Black plum', 'Cracked pepper', 'Vanilla oak', 'Silky tannins'],
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 310,
    isActive: true,
  },
  {
    id: 'prod_fratelli_chenin',
    name: 'Fratelli Classic Chenin Blanc Crisp White Wine',
    slug: 'fratelli-classic-chenin-blanc',
    brandId: 'b_fratelli',
    brandName: 'Fratelli',
    categoryId: 'cat_wine',
    categoryName: 'Wine',
    subcategory: 'White Wine',
    price: 850,
    mrp: 920,
    volume: '750 ml',
    alcoholByVolume: 12.5,
    isAlcoholic: true,
    description: 'Fresh, mineral-rich Indian white wine with bright notes of green apple, pineapple, and lime zest.',
    tastingNotes: ['Green apple', 'Pineapple', 'Crisp mineral acid'],
    imageUrl: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    rating: 4.6,
    reviewCount: 190,
    isActive: true,
  },
  {
    id: 'prod_baileys_irish_cream',
    name: 'Baileys Original Irish Cream Liqueur',
    slug: 'baileys-original-irish-cream',
    brandId: 'b_baileys',
    brandName: 'Baileys',
    categoryId: 'cat_liqueurs',
    categoryName: 'Liqueurs',
    subcategory: 'Cream Liqueur',
    price: 2450,
    mrp: 2700,
    volume: '750 ml',
    alcoholByVolume: 17.0,
    isAlcoholic: true,
    description: 'The world’s favourite Irish cream. Premium Irish whiskey smoothly blended with real fresh dairy cream and rich cocoa.',
    tastingNotes: ['Velvety cream', 'Melted chocolate', 'Irish whiskey warmth'],
    imageUrl: 'https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=600&auto=format&fit=crop&q=80',
    country: 'Ireland',
    isFeatured: true,
    rating: 4.9,
    reviewCount: 260,
    isActive: true,
  },

  // ==========================================
  // NON-ALCOHOLIC: WATER & HYDRATION (0.0% ABV)
  // ==========================================
  {
    id: 'prod_bisleri_1l',
    name: 'Bisleri Mineral Water with Added Minerals',
    slug: 'bisleri-mineral-water-1l',
    brandId: 'b_bisleri',
    brandName: 'Bisleri',
    categoryId: 'cat_water',
    categoryName: 'Water & Hydration',
    subcategory: 'Packaged Drinking Water',
    price: 20,
    mrp: 20,
    volume: '1 Litre',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: '10-stage purification process with essential minerals (magnesium and potassium) for refreshing hydration.',
    tastingNotes: ['Pure', 'Crisp mineral taste', 'Chilled'],
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 1420,
    isActive: true,
    variants: [
      { id: 'var_bisleri_500', productId: 'prod_bisleri_1l', name: '500 ml Bottle', volume: '500 ml', price: 10, mrp: 10, isActive: true },
      { id: 'var_bisleri_1000', productId: 'prod_bisleri_1l', name: '1 Litre Bottle', volume: '1000 ml', price: 20, mrp: 20, isActive: true },
      { id: 'var_bisleri_pack6', productId: 'prod_bisleri_1l', name: 'Party Pack of 6 x 1L', volume: '6000 ml', price: 110, mrp: 120, isActive: true },
    ]
  },
  {
    id: 'prod_himalayan_natural',
    name: 'Himalayan Natural Mineral Spring Water',
    slug: 'himalayan-natural-mineral-spring-water',
    brandId: 'b_himalayan',
    brandName: 'Himalayan',
    categoryId: 'cat_water',
    categoryName: 'Water & Hydration',
    subcategory: 'Natural Mineral Water',
    price: 65,
    mrp: 70,
    volume: '1 Litre',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Naturally filtered through volcanic rock aquifers in the Shivalik range of the Himalayas for 20 years.',
    tastingNotes: ['Naturally alkaline', 'Pure mountain spring water', 'Smooth texture'],
    imageUrl: 'https://images.unsplash.com/photo-1548839140-29a749e1bc4e?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    rating: 4.8,
    reviewCount: 340,
    isActive: true,
  },

  // ==========================================
  // NON-ALCOHOLIC: SODA, TONICS & MIXERS
  // ==========================================
  {
    id: 'prod_schweppes_soda',
    name: 'Schweppes Master Club Soda',
    slug: 'schweppes-master-club-soda',
    brandId: 'b_schweppes',
    brandName: 'Schweppes',
    categoryId: 'cat_mixers',
    categoryName: 'Mixers & Tonics',
    subcategory: 'Club Soda',
    price: 25,
    mrp: 25,
    volume: '300 ml Can',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'High effervescence and extra fizz club soda. The ultimate mixer for whiskies, rums, and mocktails.',
    tastingNotes: ['Intense bubbles', 'Crisp clean effervescence'],
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 980,
    isActive: true,
    variants: [
      { id: 'var_soda_single', productId: 'prod_schweppes_soda', name: '300 ml Can', volume: '300 ml', price: 25, mrp: 25, isActive: true },
      { id: 'var_soda_pack6', productId: 'prod_schweppes_soda', name: 'Pack of 6 Cans', volume: '1800 ml', price: 140, mrp: 150, isActive: true },
    ]
  },
  {
    id: 'prod_schweppes_tonic',
    name: 'Schweppes Indian Tonic Water',
    slug: 'schweppes-indian-tonic-water',
    brandId: 'b_schweppes',
    brandName: 'Schweppes',
    categoryId: 'cat_mixers',
    categoryName: 'Mixers & Tonics',
    subcategory: 'Tonic Water',
    price: 55,
    mrp: 60,
    volume: '300 ml Can',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Classic botanical quinine and subtle citrus aroma. The world’s gold standard gin and cocktail companion.',
    tastingNotes: ['Quinine bitterness', 'Citrus zest', 'Sparkling carbonation'],
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    country: 'United Kingdom',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 520,
    isActive: true,
  },
  {
    id: 'prod_schweppes_gingerale',
    name: 'Schweppes Sparkling Ginger Ale',
    slug: 'schweppes-sparkling-ginger-ale',
    brandId: 'b_schweppes',
    brandName: 'Schweppes',
    categoryId: 'cat_mixers',
    categoryName: 'Mixers & Tonics',
    subcategory: 'Ginger Ale',
    price: 60,
    mrp: 65,
    volume: '300 ml Can',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Refreshing ginger extract with crisp carbonation. Perfect for Jameson Irish whiskey highballs or chilling on ice.',
    tastingNotes: ['Fiery ginger kick', 'Gentle sweetness', 'Bubbly finish'],
    imageUrl: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=600&auto=format&fit=crop&q=80',
    country: 'United Kingdom',
    rating: 4.7,
    reviewCount: 380,
    isActive: true,
  },
  {
    id: 'prod_jimmys_whiskey_sour',
    name: "Jimmy's Cocktails Whiskey Sour Mixer",
    slug: 'jimmys-cocktails-whiskey-sour-mixer',
    brandId: 'b_jimmys',
    brandName: "Jimmy's Cocktails",
    categoryId: 'cat_mixers',
    categoryName: 'Mixers & Tonics',
    subcategory: 'Cocktail Mixers',
    price: 99,
    mrp: 120,
    volume: '250 ml Bottle',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Crafted by India’s top mixologists with Indian lemons, Persian limes, and a dash of cinnamon. Zero artificial sweeteners.',
    tastingNotes: ['Persian lime', 'Subtle bitters', 'Cinnamon aroma'],
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 410,
    isActive: true,
  },

  // ==========================================
  // NON-ALCOHOLIC: SOFT DRINKS & ENERGY
  // ==========================================
  {
    id: 'prod_thums_up_can',
    name: 'Thums Up Charged Cola (Taste the Thunder)',
    slug: 'thums-up-charged-cola-can',
    brandId: 'b_thumsup',
    brandName: 'Thums Up',
    categoryId: 'cat_softdrinks',
    categoryName: 'Soft Drinks & Energy',
    subcategory: 'Colas & Sodas',
    price: 40,
    mrp: 40,
    volume: '300 ml Can',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'India’s hero strong fizzy cola with spicy punch. The undisputed pairing for Old Monk rum and whisky in UP and Delhi.',
    tastingNotes: ['Strong fizz', 'Spicy cola flavor', 'High kick'],
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 1650,
    isActive: true,
  },
  {
    id: 'prod_coca_cola_can',
    name: 'Coca-Cola Original Taste Chilled Can',
    slug: 'coca-cola-original-taste-can',
    brandId: 'b_cocacola',
    brandName: 'Coca-Cola',
    categoryId: 'cat_softdrinks',
    categoryName: 'Soft Drinks & Energy',
    subcategory: 'Colas & Sodas',
    price: 40,
    mrp: 40,
    volume: '300 ml Can',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'The world’s classic refreshing cola served ice-cold. Delicious alone or mixed.',
    tastingNotes: ['Caramel cola', 'Vanilla note', 'Sparkling carbonation'],
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80',
    country: 'United States',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 890,
    isActive: true,
  },
  {
    id: 'prod_sprite_can',
    name: 'Sprite Lemon-Lime Refreshment Can',
    slug: 'sprite-lemon-lime-can',
    brandId: 'b_sprite',
    brandName: 'Sprite',
    categoryId: 'cat_softdrinks',
    categoryName: 'Soft Drinks & Energy',
    subcategory: 'Colas & Sodas',
    price: 40,
    mrp: 40,
    volume: '300 ml Can',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Clear, crisp lemon-lime refreshment. Clean cut-through fizz.',
    tastingNotes: ['Zesty lemon', 'Lime juice', 'Crisp effervescence'],
    imageUrl: 'https://images.unsplash.com/photo-1622483767028-3f66f32aef97?w=600&auto=format&fit=crop&q=80',
    country: 'United States',
    rating: 4.8,
    reviewCount: 620,
    isActive: true,
  },
  {
    id: 'prod_red_bull_energy',
    name: 'Red Bull Energy Drink (Vitalizes Body and Mind)',
    slug: 'red-bull-energy-drink',
    brandId: 'b_redbull',
    brandName: 'Red Bull',
    categoryId: 'cat_softdrinks',
    categoryName: 'Soft Drinks & Energy',
    subcategory: 'Energy Drinks',
    price: 125,
    mrp: 125,
    volume: '250 ml Can',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Appreciated worldwide by top athletes, busy professionals, and party lovers. Contains caffeine, taurine, and B-group vitamins.',
    tastingNotes: ['Sweet alpine berry', 'Tart acidity', 'Energy kick'],
    imageUrl: 'https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=600&auto=format&fit=crop&q=80',
    country: 'Austria',
    isBestseller: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 1120,
    isActive: true,
    variants: [
      { id: 'var_rb_single', productId: 'prod_red_bull_energy', name: '250 ml Can', volume: '250 ml', price: 125, mrp: 125, isActive: true },
      { id: 'var_rb_pack4', productId: 'prod_red_bull_energy', name: 'Party 4-Pack (4 x 250ml)', volume: '1000 ml', price: 475, mrp: 500, isActive: true },
    ]
  },

  // ==========================================
  // ZERO-ALCOHOL BEER (0.0% ABV)
  // ==========================================
  {
    id: 'prod_heineken_zero',
    name: 'Heineken 0.0 Non-Alcoholic Malt Lager',
    slug: 'heineken-0-0-non-alcoholic-beer',
    brandId: 'b_heineken',
    brandName: 'Heineken',
    categoryId: 'cat_beer',
    categoryName: 'Beer & Ciders',
    subcategory: 'Craft Beer',
    price: 90,
    mrp: 99,
    volume: '330 ml Can',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Brewed with natural ingredients and gentle alcohol removal. Only 69 calories with authentic Heineken pilsner taste.',
    tastingNotes: ['Fruity notes', 'Gentle malt body', 'Zero alcohol freedom'],
    imageUrl: 'https://images.unsplash.com/photo-1608270199182-4faeb9ff7584?w=600&auto=format&fit=crop&q=80',
    country: 'Netherlands',
    isNewArrival: true,
    rating: 4.7,
    reviewCount: 280,
    isActive: true,
  },

  // ==========================================
  // PARTY ESSENTIALS & CRYSTAL ICE
  // ==========================================
  {
    id: 'prod_drinkit_ice_1kg',
    name: 'DrinkIt Pure Food-Grade Crystal Ice Cubes (1 kg)',
    slug: 'drinkit-food-grade-crystal-ice-1kg',
    brandId: 'b_drinkit',
    brandName: 'DrinkIt Essentials',
    categoryId: 'cat_party',
    categoryName: 'Party Essentials & Ice',
    subcategory: 'Party Ice Cubes',
    price: 60,
    mrp: 75,
    volume: '1 kg Pack',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Triple-purified RO water ice cubes frozen at -18°C. Slow melting, transparent, odourless, and 100% food-grade.',
    tastingNotes: ['Crystal clear', 'Slow melting', 'Zero chlorine odor'],
    imageUrl: 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    isFeatured: true,
    rating: 4.9,
    reviewCount: 1350,
    isActive: true,
    variants: [
      { id: 'var_ice_1kg', productId: 'prod_drinkit_ice_1kg', name: '1 kg Quick Bag', volume: '1 kg', price: 60, mrp: 75, isActive: true },
      { id: 'var_ice_2kg', productId: 'prod_drinkit_ice_1kg', name: '2 kg Mega Party Bag', volume: '2 kg', price: 105, mrp: 130, isActive: true },
    ]
  },
  {
    id: 'prod_red_solo_cups',
    name: 'DrinkIt Classic Red Party Solo Cups (Pack of 25)',
    slug: 'drinkit-classic-red-party-cups-25',
    brandId: 'b_drinkit',
    brandName: 'DrinkIt Essentials',
    categoryId: 'cat_party',
    categoryName: 'Party Essentials & Ice',
    subcategory: 'Glassware & Cups',
    price: 149,
    mrp: 199,
    volume: 'Pack of 25 (450 ml)',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Heavy-duty ribbed American-style red cups. Crack-resistant, reusable, and essential for house parties and beer pong.',
    tastingNotes: ['Food-grade plastic', 'Ribbed easy grip', 'Spill resistant'],
    imageUrl: 'https://images.unsplash.com/photo-1574096079513-d8259312b785?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 540,
    isActive: true,
  },
  {
    id: 'prod_cocktail_shaker_jigger',
    name: 'Stainless Steel Cocktail Shaker & Dual Peg Jigger Set',
    slug: 'cocktail-shaker-and-jigger-set',
    brandId: 'b_drinkit',
    brandName: 'DrinkIt Essentials',
    categoryId: 'cat_party',
    categoryName: 'Party Essentials & Ice',
    subcategory: 'Barware & Openers',
    price: 699,
    mrp: 999,
    volume: '750 ml + 30/60ml',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'High-polish 304 food-grade stainless steel Boston-style shaker with built-in strainer and double peg measure jigger.',
    tastingNotes: ['Mirror finish', 'Dishwasher safe', 'Leak proof seal'],
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    rating: 4.8,
    reviewCount: 220,
    isActive: true,
  },
  {
    id: 'prod_bottle_opener_corkscrew',
    name: 'Heavy Duty Waiters Wine Corkscrew & Bottle Opener',
    slug: 'heavy-duty-corkscrew-bottle-opener',
    brandId: 'b_drinkit',
    brandName: 'DrinkIt Essentials',
    categoryId: 'cat_party',
    categoryName: 'Party Essentials & Ice',
    subcategory: 'Barware & Openers',
    price: 199,
    mrp: 299,
    volume: '1 Piece',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Double-hinged fulcrum wine corkscrew with serrated foil cutter and crown cap bottle opener in matte black finish.',
    tastingNotes: ['Ergonomic grip', 'Smooth extraction', 'Pocket sized'],
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    rating: 4.9,
    reviewCount: 380,
    isActive: true,
  },

  // ==========================================
  // BAR SNACKS & CHAKNA (HALDIRAM'S, LAY'S, NACHOS)
  // ==========================================
  {
    id: 'prod_haldiram_aloo_bhujia',
    name: "Haldiram's Nagpur Spicy Aloo Bhujia",
    slug: 'haldirams-aloo-bhujia-crispy-namkeen',
    brandId: 'b_haldirams',
    brandName: "Haldiram's",
    categoryId: 'cat_snacks',
    categoryName: 'Bar Snacks & Munchies',
    subcategory: 'Traditional Namkeen',
    price: 55,
    mrp: 60,
    volume: '200g Pack',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Crispy crunchy potato and chickpea sev infused with spicy mint and tangy dry mango. North India’s quintessential chakna.',
    tastingNotes: ['Spicy mint', 'Tangy amchur', 'Crunchy crispy sev'],
    imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 1150,
    isActive: true,
    variants: [
      { id: 'var_bhujia_200', productId: 'prod_haldiram_aloo_bhujia', name: '200g Pouch', volume: '200g', price: 55, mrp: 60, isActive: true },
      { id: 'var_bhujia_400', productId: 'prod_haldiram_aloo_bhujia', name: '400g Party Pack', volume: '400g', price: 105, mrp: 115, isActive: true },
    ]
  },
  {
    id: 'prod_haldiram_salted_peanuts',
    name: "Haldiram's Salted & Roasted Peanuts (Chakna Special)",
    slug: 'haldirams-salted-peanuts-chakna',
    brandId: 'b_haldirams',
    brandName: "Haldiram's",
    categoryId: 'cat_snacks',
    categoryName: 'Bar Snacks & Munchies',
    subcategory: 'Roasted Chakna',
    price: 50,
    mrp: 55,
    volume: '200g Pack',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Golden roasted premium Gujarat groundnuts with clean rock salt. The indispensable pairing for chilled beers and whisky.',
    tastingNotes: ['Crunchy roast', 'Rock salt', 'Nutty goodness'],
    imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 780,
    isActive: true,
  },
  {
    id: 'prod_lays_magic_masala',
    name: "Lay's India's Magic Masala Potato Chips",
    slug: 'lays-indias-magic-masala-chips',
    brandId: 'b_lays',
    brandName: "Lay's",
    categoryId: 'cat_snacks',
    categoryName: 'Bar Snacks & Munchies',
    subcategory: 'Crisps & Chips',
    price: 30,
    mrp: 30,
    volume: '73g Pouch',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'India’s most loved potato chip bursting with spicy red chilli, coriander, cumin, and dried mango powder.',
    tastingNotes: ['Zesty masala', 'Crispy crunch', 'Spicy kick'],
    imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&auto=format&fit=crop&q=80',
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 920,
    isActive: true,
  },
  {
    id: 'prod_doritos_nachos_salsa',
    name: 'Doritos Cheese Supreme Nachos with Roasted Salsa Dip',
    slug: 'doritos-cheese-nachos-with-salsa-dip',
    brandId: 'b_doritos',
    brandName: 'Doritos',
    categoryId: 'cat_snacks',
    categoryName: 'Bar Snacks & Munchies',
    subcategory: 'Nachos & Dips',
    price: 110,
    mrp: 125,
    volume: '150g Combo',
    alcoholByVolume: 0.0,
    isAlcoholic: false,
    description: 'Triangular crunchy corn tortilla chips seasoned with rich cheddar cheese, served with tangy chunky tomato roasted salsa dip.',
    tastingNotes: ['Cheddar cheese', 'Toasted corn', 'Spicy tangy salsa'],
    imageUrl: 'https://images.unsplash.com/photo-1566478989037-eec170784d0b?w=600&auto=format&fit=crop&q=80',
    country: 'United States',
    isFeatured: true,
    rating: 4.8,
    reviewCount: 540,
    isActive: true,
  },
];
