import { Product } from '../types.ts';

const VERIFIED_AT = '2026-09-26';

export const PARTY_PRODUCTS: Product[] = [
  // --- CHIPS ---
  {
    id: 'prod_lays_classic_salted',
    name: "Lay's Classic Salted Potato Chips",
    slug: 'lays-classic-salted',
    brandId: 'b_lays',
    brandName: "Lay's",
    categoryId: 'cat_snacks',
    categoryName: 'Chips & Namkeen',
    subcategory: 'Potato Chips',
    price: 20,
    mrp: 20,
    volume: '50g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Thinly sliced farm-grown potatoes lightly sprinkled with pure crystal salt.',
    tastingNotes: ['Crispy Salted Potato'],
    imageUrl: '/images/products/snacks/lays-classic-salted.webp',
    imageSource: 'PepsiCo India Frito-Lay',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 290,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
    variants: [
      { id: 'var_lays_50g', productId: 'prod_lays_classic_salted', name: '50g Pack', volume: '50g', price: 20, mrp: 20, sku: 'LAYS-SALT-50', isActive: true },
      { id: 'var_lays_90g', productId: 'prod_lays_classic_salted', name: '90g Party Size', volume: '90g', price: 40, mrp: 40, sku: 'LAYS-SALT-90', isActive: true },
    ],
  },
  {
    id: 'prod_lays_magic_masala',
    name: "Lay's India's Magic Masala Potato Chips",
    slug: 'lays-magic-masala',
    brandId: 'b_lays',
    brandName: "Lay's",
    categoryId: 'cat_snacks',
    categoryName: 'Chips & Namkeen',
    subcategory: 'Potato Chips',
    price: 20,
    mrp: 20,
    volume: '50g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Wavy potato chips seasoned with authentic blend of Indian spices.',
    tastingNotes: ['Spicy Masala', 'Tangy Onion & Coriander'],
    imageUrl: '/images/products/snacks/lays-magic-masala.webp',
    imageSource: 'PepsiCo India Frito-Lay',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 380,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_pringles_sour_cream',
    name: 'Pringles Sour Cream & Onion Potato Crisps',
    slug: 'pringles-sour-cream-onion',
    brandId: 'b_pringles',
    brandName: 'Pringles',
    categoryId: 'cat_snacks',
    categoryName: 'Chips & Namkeen',
    subcategory: 'Potato Chips',
    price: 115,
    mrp: 125,
    volume: '107g Canister',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Crisp saddle-shaped stacked potato crisps packed in iconic protective party canister.',
    tastingNotes: ['Tangy Sour Cream', 'Savory Spring Onion'],
    imageUrl: '/images/products/snacks/pringles-sour-cream.webp',
    imageSource: 'Kellogg’s India Pringles',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'Malaysia',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 195,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- NAMKEEN ---
  {
    id: 'prod_haldirams_aloo_bhujia',
    name: "Haldiram's Nagpur Spicy Aloo Bhujia",
    slug: 'haldirams-aloo-bhujia',
    brandId: 'b_haldirams',
    brandName: "Haldiram's",
    categoryId: 'cat_snacks',
    categoryName: 'Chips & Namkeen',
    subcategory: 'Aloo Bhujia',
    price: 45,
    mrp: 45,
    volume: '150g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Crispy fried potato and chickpea flour strands flavored with fiery mint, red chilli and spices.',
    tastingNotes: ['Spicy Mint', 'Crispy Potato Bhujia'],
    imageUrl: '/images/products/snacks/haldirams-aloo-bhujia-150g.webp',
    imageSource: "Haldiram's India Brand Store",
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 420,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
    variants: [
      { id: 'var_hald_150', productId: 'prod_haldirams_aloo_bhujia', name: '150g Pack', volume: '150g', price: 45, mrp: 45, sku: 'HALD-ALOO-150', isActive: true },
      { id: 'var_hald_350', productId: 'prod_haldirams_aloo_bhujia', name: '350g Family Pack', volume: '350g', price: 95, mrp: 95, sku: 'HALD-ALOO-350', isActive: true },
    ],
  },
  {
    id: 'prod_haldirams_khatta_meetha',
    name: "Haldiram's Khatta Meetha Sweet & Sour Mixture",
    slug: 'haldirams-khatta-meetha',
    brandId: 'b_haldirams',
    brandName: "Haldiram's",
    categoryId: 'cat_snacks',
    categoryName: 'Chips & Namkeen',
    subcategory: 'Sev & Mixture',
    price: 50,
    mrp: 50,
    volume: '200g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Blend of puffed rice, green peas, peanuts and crisp chickpea noodles tossed in sweet & sour seasoning.',
    tastingNotes: ['Tangy Sweet', 'Crunchy Peanuts'],
    imageUrl: '/images/products/snacks/haldirams-khatta-meetha.webp',
    imageSource: "Haldiram's Official",
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 210,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_bikaji_bhujia',
    name: 'Bikaji Bikaneri Bhujia Aslee Bikaneri',
    slug: 'bikaji-bikaneri-bhujia',
    brandId: 'b_bikaji',
    brandName: 'Bikaji',
    categoryId: 'cat_snacks',
    categoryName: 'Chips & Namkeen',
    subcategory: 'Sev & Mixture',
    price: 55,
    mrp: 55,
    volume: '200g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Authentic Rajasthani moth dal and gram flour crispy bhujia seasoned with black pepper.',
    tastingNotes: ['Moth Dal', 'Coarse Black Pepper'],
    imageUrl: '/images/products/snacks/bikaji-bikaneri-bhujia.webp',
    imageSource: 'Bikaji Foods International',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.8,
    reviewCount: 145,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- PEANUTS & NUTS ---
  {
    id: 'prod_haldirams_salted_peanuts',
    name: "Haldiram's Classic Salted Peanuts",
    slug: 'haldirams-salted-peanuts',
    brandId: 'b_haldirams',
    brandName: "Haldiram's",
    categoryId: 'cat_nuts',
    categoryName: 'Peanuts & Nuts',
    subcategory: 'Salted Peanuts',
    price: 60,
    mrp: 60,
    volume: '200g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Golden roasted peanuts tossed in pure edible salt, the quintessential bar accompaniment.',
    tastingNotes: ['Roasted Nut', 'Savory Salt'],
    imageUrl: '/images/products/snacks/haldirams-salted-peanuts.webp',
    imageSource: "Haldiram's Brand Catalogue",
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 310,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_haldirams_nut_cracker',
    name: "Haldiram's Nut Cracker Coated Masala Peanuts",
    slug: 'haldirams-nut-cracker',
    brandId: 'b_haldirams',
    brandName: "Haldiram's",
    categoryId: 'cat_nuts',
    categoryName: 'Peanuts & Nuts',
    subcategory: 'Masala Peanuts',
    price: 65,
    mrp: 65,
    volume: '200g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Crunchy gram flour batter-coated spiced whole peanuts fried to golden perfection.',
    tastingNotes: ['Crispy Crust', 'Chilli Tang'],
    imageUrl: '/images/products/snacks/haldirams-nut-cracker.webp',
    imageSource: "Haldiram's Brand Catalogue",
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 260,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_roasted_salted_cashews',
    name: 'Nutraj Roasted & Salted Jumbo Cashews',
    slug: 'nutraj-roasted-salted-cashews',
    brandId: 'b_nutraj',
    brandName: 'Nutraj',
    categoryId: 'cat_nuts',
    categoryName: 'Peanuts & Nuts',
    subcategory: 'Cashews',
    price: 295,
    mrp: 325,
    volume: '200g Pouch',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Whole premium Grade W240 cashews slow-roasted and seasoned with rock salt.',
    tastingNotes: ['Buttery Crunch', 'Delicate Salt'],
    imageUrl: '/images/products/snacks/nutraj-jumbo-cashews.webp',
    imageSource: 'Nutraj Brand Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 145,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- NACHOS & POPCORN ---
  {
    id: 'prod_cornitos_cheese_herbs',
    name: 'Cornitos Nacho Crisps Cheese & Herbs',
    slug: 'cornitos-nacho-cheese-herbs',
    brandId: 'b_cornitos',
    brandName: 'Cornitos',
    categoryId: 'cat_nachos',
    categoryName: 'Nachos',
    subcategory: 'Cheese Nachos',
    price: 90,
    mrp: 90,
    volume: '150g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Crispy stone-ground Mexican corn tortilla chips flavored with cheddar cheese and parsley.',
    tastingNotes: ['Cheddar Cheese', 'Italian Herbs', 'Corn Crunch'],
    imageUrl: '/images/products/snacks/cornitos-nacho-cheese-herbs.webp',
    imageSource: 'Cornitos Official Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 175,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_doritos_nacho_cheese',
    name: 'Doritos Nacho Cheese Tortilla Chips',
    slug: 'doritos-nacho-cheese',
    brandId: 'b_doritos',
    brandName: 'Doritos',
    categoryId: 'cat_nachos',
    categoryName: 'Nachos',
    subcategory: 'Cheese Nachos',
    price: 50,
    mrp: 50,
    volume: '100g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Bold crunch triangular tortilla chips coated with savory cheese blend.',
    tastingNotes: ['Intense Cheddar', 'Garlic Onion Spice'],
    imageUrl: '/images/products/snacks/doritos-nacho-cheese.webp',
    imageSource: 'PepsiCo India Frito-Lay',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 220,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_act_ii_butter_lovers',
    name: 'Act II Butter Lovers Microwave Popcorn',
    slug: 'act-ii-butter-lovers-popcorn',
    brandId: 'b_actii',
    brandName: 'Act II',
    categoryId: 'cat_popcorn',
    categoryName: 'Popcorn',
    subcategory: 'Butter Lovers',
    price: 40,
    mrp: 40,
    volume: '85g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Fresh warm buttery movie theatre popcorn ready in 3 minutes.',
    tastingNotes: ['Hot Melted Butter', 'Crunchy Corn'],
    imageUrl: '/images/products/snacks/act-ii-butter-lovers-popcorn.webp',
    imageSource: 'ConAgra Brands Act II',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 160,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- READY-TO-EAT ---
  {
    id: 'prod_haldirams_dal_makhani',
    name: "Haldiram's Minute Khana Dal Makhani",
    slug: 'haldirams-dal-makhani-300g',
    brandId: 'b_haldirams',
    brandName: "Haldiram's",
    categoryId: 'cat_readytoeat',
    categoryName: 'Ready-to-Eat',
    subcategory: 'Dal Makhani & Gravies',
    price: 110,
    mrp: 115,
    volume: '300g Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Slow-cooked black lentils in creamy tomato gravy with white butter, heat and eat.',
    tastingNotes: ['Creamy Butter Lentil', 'Aromatic Kasuri Methi'],
    imageUrl: '/images/products/snacks/haldirams-dal-makhani-300g.webp',
    imageSource: "Haldiram's Minute Khana Official",
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.7,
    reviewCount: 92,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Manufacturer Retail Print MRP',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- PARTY ESSENTIALS: GLASSES ---
  {
    id: 'prod_disposable_glasses_250',
    name: 'Disposable Plastic Party Glasses 250ml',
    slug: 'disposable-plastic-glasses-250',
    brandId: 'b_homeone',
    brandName: 'Home One',
    categoryId: 'cat_party_glasses',
    categoryName: 'Disposable Glasses',
    subcategory: '250 ml',
    price: 65,
    mrp: 75,
    volume: '50 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Durable food-grade ribbed plastic glasses for water, juices, beer and mixers.',
    tastingNotes: ['Food Grade', 'Non-Toxic', 'Crack Resistant'],
    imageUrl: '/images/products/party/disposable-glasses-250ml.webp',
    imageSource: 'Home One Party Essentials Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 310,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_disposable_glasses_300',
    name: 'Disposable Plastic Party Glasses 300ml',
    slug: 'disposable-plastic-glasses-300',
    brandId: 'b_homeone',
    brandName: 'Home One',
    categoryId: 'cat_party_glasses',
    categoryName: 'Disposable Glasses',
    subcategory: '300 ml',
    price: 80,
    mrp: 90,
    volume: '50 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: '300ml crystal clear plastic glasses for parties, beer and cold cocktails.',
    tastingNotes: ['Heavy Duty', 'Recyclable'],
    imageUrl: '/images/products/party/disposable-glasses-250ml.webp',
    imageSource: 'Home One Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 220,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_red_solo_cups_450',
    name: 'American Red Solo Party Cups 450ml',
    slug: 'red-solo-party-cups-450',
    brandId: 'b_partytime',
    brandName: 'PartyTime Essentials',
    categoryId: 'cat_party_glasses',
    categoryName: 'Disposable Glasses',
    subcategory: 'Red Solo Cups',
    price: 140,
    mrp: 160,
    volume: '25 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Classic red solo beer pong party cups with white interior and grip ridges.',
    tastingNotes: ['Beer Pong Standard', 'Sturdy Rim'],
    imageUrl: '/images/products/party/red-solo-cups-450ml.webp',
    imageSource: 'PartyTime Catalogue',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 185,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- PARTY ESSENTIALS: PLATES & BOWLS ---
  {
    id: 'prod_paper_plates_9',
    name: 'Disposable Heavy Paper Plates 9"',
    slug: 'disposable-paper-plates-9',
    brandId: 'b_homeone',
    brandName: 'Home One',
    categoryId: 'cat_party_plates',
    categoryName: 'Disposable Plates',
    subcategory: '9" Plates',
    price: 60,
    mrp: 70,
    volume: '25 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Greaseproof and leakproof sturdy paper plates for snacks, dinner and party food.',
    tastingNotes: ['Grease Resistant', 'Bio Degradable'],
    imageUrl: '/images/products/party/paper-plates-9in.webp',
    imageSource: 'Home One Official Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 240,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_areca_leaf_plates_10',
    name: 'Eco-Friendly Areca Palm Leaf Plates 10"',
    slug: 'areca-leaf-plates-10',
    brandId: 'b_ecosoul',
    brandName: 'EcoSoul',
    categoryId: 'cat_party_plates',
    categoryName: 'Disposable Plates',
    subcategory: 'Areca Palm Leaf',
    price: 120,
    mrp: 140,
    volume: '10 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: '100% natural, chemical-free fallen areca palm leaf plates. Microwave safe and ultra sturdy.',
    tastingNotes: ['Chemical Free', '100% Compostable'],
    imageUrl: '/images/products/party/paper-plates-9in.webp',
    imageSource: 'EcoSoul Home Products',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.9,
    reviewCount: 110,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_paper_bowls_200',
    name: 'Disposable Deep Paper Snack Bowls 200ml',
    slug: 'disposable-paper-bowls-200',
    brandId: 'b_homeone',
    brandName: 'Home One',
    categoryId: 'cat_party_bowls',
    categoryName: 'Bowls',
    subcategory: 'Paper Bowls',
    price: 40,
    mrp: 45,
    volume: '25 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Leak-resistant food grade paper bowls for namkeen, peanuts, chips and dips.',
    tastingNotes: ['Deep Well', 'No Sagging'],
    imageUrl: '/images/products/party/disposable-paper-bowls-200.webp',
    imageSource: 'Home One Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 155,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- PARTY ESSENTIALS: CUTLERY & NAPKINS & STRAWS ---
  {
    id: 'prod_cutlery_combo_set',
    name: 'All-in-One Cutlery Combo Pack (Spoon, Fork, Napkin)',
    slug: 'cutlery-combo-set-20',
    brandId: 'b_partytime',
    brandName: 'PartyTime Essentials',
    categoryId: 'cat_party_cutlery',
    categoryName: 'Cutlery',
    subcategory: 'Combo Sets',
    price: 75,
    mrp: 90,
    volume: '20 Sets',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Individually wrapped hygiene packs with heavy duty white spoon, fork and soft napkin.',
    tastingNotes: ['Hygienic Seal', 'Rigid Plastic'],
    imageUrl: '/images/products/party/cutlery-combo-set.webp',
    imageSource: 'PartyTime Essentials Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 170,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_home_one_napkins_100',
    name: 'Home One Table Paper Napkins 29x29cm',
    slug: 'home-one-paper-napkins-100',
    brandId: 'b_homeone',
    brandName: 'Home One',
    categoryId: 'cat_party_napkins',
    categoryName: 'Napkins',
    subcategory: 'Table Napkins',
    price: 55,
    mrp: 65,
    volume: '100 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: '100% virgin pulp soft absorbent table napkins for party food and cocktails.',
    tastingNotes: ['High Absorbency', 'Food Contact Safe'],
    imageUrl: '/images/products/party/paper-napkins.webp',
    imageSource: 'JioMart Home One Product Listing',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 380,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_bendable_straws_50',
    name: 'Neon Flexible Bendable Cocktail Straws',
    slug: 'bendable-cocktail-straws-50',
    brandId: 'b_partytime',
    brandName: 'PartyTime Essentials',
    categoryId: 'cat_party_straws',
    categoryName: 'Straws',
    subcategory: 'Bendable Straws',
    price: 40,
    mrp: 45,
    volume: '50 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Multi-colored neon flexible neck drinking straws for drinks and cocktails.',
    tastingNotes: ['Flexible Accordion Neck', 'Smooth Edge'],
    imageUrl: '/images/products/party/cocktail-straws.webp',
    imageSource: 'PartyTime Essentials Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 120,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },

  // --- OTHER PARTY ESSENTIALS ---
  {
    id: 'prod_ice_bags_5',
    name: 'Food Grade Clear Ice Cube Storage Bags',
    slug: 'food-grade-ice-cube-bags-5',
    brandId: 'b_partytime',
    brandName: 'PartyTime Essentials',
    categoryId: 'cat_party',
    categoryName: 'Other Party Essentials',
    subcategory: 'Ice Bags & Accessories',
    price: 45,
    mrp: 50,
    volume: '5 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Thick food grade ice freezer bags with drawstring closure for chilling bottles and drinks.',
    tastingNotes: ['Heavy Micron Poly', 'Drawstring Tie'],
    imageUrl: '/images/products/party/ice-bags.webp',
    imageSource: 'PartyTime Essentials Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 165,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_steel_bottle_opener',
    name: 'Stainless Steel Heavy Duty Flat Bottle Opener',
    slug: 'steel-flat-bottle-opener',
    brandId: 'b_partytime',
    brandName: 'PartyTime Essentials',
    categoryId: 'cat_party',
    categoryName: 'Other Party Essentials',
    subcategory: 'Bottle Openers & Corkscrews',
    price: 75,
    mrp: 95,
    volume: '1 Piece',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Bartender speed bar blade opener made of solid stainless steel.',
    tastingNotes: ['Stainless Steel 304', 'Speed Blade'],
    imageUrl: '/images/products/party/bottle-opener.webp',
    imageSource: 'PartyTime Essentials Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.9,
    reviewCount: 190,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_wine_corkscrew_opener',
    name: 'Deluxe Winged Wine Corkscrew & Bottle Opener',
    slug: 'deluxe-winged-wine-corkscrew',
    brandId: 'b_partytime',
    brandName: 'PartyTime Essentials',
    categoryId: 'cat_party',
    categoryName: 'Other Party Essentials',
    subcategory: 'Bottle Openers & Corkscrews',
    price: 185,
    mrp: 225,
    volume: '1 Piece',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Ergonomic dual-wing cork extractor with built-in crown cap bottle opener.',
    tastingNotes: ['Chrome Plated Zinc Alloy', 'Effortless Cork Pull'],
    imageUrl: '/images/products/party/wine-corkscrew.webp',
    imageSource: 'PartyTime Essentials Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.8,
    reviewCount: 85,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_cocktail_toothpicks_100',
    name: 'Wooden Cocktail Toothpicks with Frill',
    slug: 'wooden-cocktail-toothpicks-100',
    brandId: 'b_partytime',
    brandName: 'PartyTime Essentials',
    categoryId: 'cat_party',
    categoryName: 'Other Party Essentials',
    subcategory: 'Other Party Essentials',
    price: 35,
    mrp: 40,
    volume: '100 Pack',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Natural birchwood cocktail picks with colorful cellophane frilled tops for olives and finger snacks.',
    tastingNotes: ['Smooth Birchwood', 'Food Grade'],
    imageUrl: '/images/products/party/wooden-cocktail-toothpicks-100.webp',
    imageSource: 'PartyTime Essentials Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    rating: 4.7,
    reviewCount: 95,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  },
  {
    id: 'prod_garbage_bags_30',
    name: 'Heavy Duty Black Garbage Bags Large 30 Pcs',
    slug: 'heavy-duty-garbage-bags-30',
    brandId: 'b_homeone',
    brandName: 'Home One',
    categoryId: 'cat_party',
    categoryName: 'Other Party Essentials',
    subcategory: 'Garbage Bags & Wipes',
    price: 85,
    mrp: 100,
    volume: '30 Pcs Roll',
    alcoholByVolume: 0,
    isAlcoholic: false,
    description: 'Extra strong tear-resistant trash bags for hassle-free post-party cleanup.',
    tastingNotes: ['Leakproof Bottom', 'High Micron Strength'],
    imageUrl: '/images/products/party/heavy-duty-garbage-bags-30.webp',
    imageSource: 'Home One Essentials Store',
    imageVerified: true,
    imageVerifiedAt: VERIFIED_AT,
    country: 'India',
    isBestseller: true,
    rating: 4.8,
    reviewCount: 140,
    isActive: true,
    availableStates: ['Uttar Pradesh', 'Delhi'],
    priceVerified: true,
    priceSource: 'Retail Packaging MRP',
    priceVerifiedAt: VERIFIED_AT,
  }
];
